import { makeAugust20Article } from './august20-article';
const title = 'Expansion signal qualification brief';
const service = 'upsell-opportunity-tracking';
const slug = 'philippines-account-management-expansion-signal-qualification-brief';
const published = '2026-08-20';
const focus = 'expansion discovery';
const paragraphs = [
  "Publication date: August 20, 2026. For expansion discovery, start with the account, the period under review, and the question the owner needs answered. a qualification brief records a client need without turning a passing comment into a sales commitment. The record should help a Philippines-based account manager prepare assigned work while the accountable business owner keeps authority for consequential choices.",
  "The first useful field is not a status color. It is the client effect. Write what may change for the account if the item waits, what evidence supports that concern, and what remains uncertain. This keeps expansion discovery tied to actual account work instead of a label that grows more urgent each time someone opens it.",
  "Preserve the client’s wording when it changes the meaning of the request. A paraphrase can hide whether the client reported an outcome, asked for a change, expressed a preference, or described a risk. Keep the source, date, channel, and affected work beside the internal interpretation.",
  "Set a narrow time window. A current account question should not quietly absorb every historical note in the CRM. Older material may explain context, but it should be marked as background. The work owner can collect it; the decision owner can decide whether it still controls the present account.",
  "Use one record for the question and one row for each relevant fact. Record the source link or approved record name, the checked date, the fact supported, and its limitation. If a source is indirect or stale, say so. A visible gap is safer than a smooth conclusion that no one can reproduce.",
  "For expansion discovery, distinguish preparation from decision authority. The support role may reconcile assigned records, prepare a draft, arrange a meeting, remind an owner, or send wording that has already been approved. It should not change a contract, approve money movement, make a legal or security judgment, grant broad access, or promise unapproved work.",
  "Name a work owner and a decision owner when the two jobs differ. The work owner moves the record; the decision owner determines what the business can accept. Put both names beside the next action, along with the deadline and the consequence of waiting. Assignment is not approval.",
  "A useful review asks what would disprove the current interpretation. If the account looks healthy because the last touch field is populated, check whether the client actually received the promised work. If a request looks simple, check dependencies, scope, permissions, and any other account affected by the response.",
  "Do not use activity as a substitute for an outcome. A meeting, message, updated field, or delivered file shows that work happened. It does not by itself prove that the client’s intended result was achieved or accepted. Keep activity evidence and outcome evidence in separate fields.",
  "The record should support a calm owner conversation. Put the question first, then the confirmed facts, then the uncertainty, then the available next actions. This order lets a reviewer make a bounded choice without searching through a long narrative or asking the support specialist to reconstruct the account from memory.",
  "Client communication should match the evidence. State what was checked, what is confirmed, what is still open, who is reviewing the open point, and when the next update will arrive. Do not use a confident phrase to cover a missing source or imply that silence equals agreement.",
  "If the client corrects the record, preserve the correction and update the current state. Do not erase the earlier wording simply because the later version is more convenient. A future account manager needs to see what changed, why it changed, and which owner accepted the correction.",
  "Review dependencies explicitly. A client request may wait on an internal decision, a missing client answer, a delivery check, a permissions review, or a source record maintained elsewhere. Naming the dependency stops the support queue from assigning the same work repeatedly to people who cannot unblock it.",
  "Use the smallest useful permission for the assigned task. Account support should work in approved systems with named access and clear boundaries. When a task ends, record whether access should expire or be reviewed. Broad administrative access is not a substitute for a well-defined routine.",
  "When a choice affects commercial terms, credits, refunds, legal wording, security, privacy, or work outside scope, route it to the authorized owner. Give that owner the source, account effect, options, and timing. Do not forward an urgent question without enough context to decide it safely.",
  "A review cadence should match the risk. A near-term renewal, unresolved client impact, or expiring permission deserves a dated check. A stable reference field may need a less frequent review. Avoid one blanket cadence that makes low-risk maintenance noisy and high-risk exceptions invisible.",
  "Closure needs proof. State the result, the source that supports it, the owner action, the approved client communication, and any remaining exception. If one of those pieces is missing, keep the item open or transfer it with a new owner and review date.",
  "A transfer is not a close. Explain why the work moved, which facts were checked, what the receiving owner must decide, which permissions are required, and what the client has been told. This makes the handoff usable by another authorized account manager without asking them to guess.",
  "Patterns in the record should improve the routine. Repeated stale fields may call for a freshness rule. Repeated scope confusion may call for an intake question. Repeated escalations may call for a severity boundary. Fix the operating rule rather than asking one person to remember more exceptions.",
  "Keep public guidance factually bounded. Examples should describe the operating problem without inventing a company location, credential, result, testimonial, client name, or internal performance claim. The point of expansion discovery is a usable method, not a promise about what any particular account will achieve.",
  "Before sending the final update, read it as the client would. Remove private commentary, guesses, and unresolved internal debate. Keep the practical limit visible. A short truthful message that names the next check is more useful than a polished paragraph that suggests the answer is already approved.",
  "The final review for expansion discovery should ask whether the source, current state, authority boundary, owner action, and next communication agree. If they do, close the record with the date and proof. If they do not, carry the exception. That discipline keeps account support dependable when priorities change.",
];
export const article = makeAugust20Article(title, service, slug, paragraphs, focus, published);
