import type { RichArticle } from './rich-articles';
type Topic=readonly[string,string,string,string,string];
const topics:Topic[]=[
['client-decision-expiry-register','Client decision expiry register','client-request-routing','stop an old approval controlling work after assumptions change','approval source, effective window, expiry trigger, affected work, and reapproval owner'],
['renewal-evidence-freeze','Renewal evidence freeze','renewal-administration','freeze a renewal packet while keeping late facts visible','cutoff, included evidence, late-evidence lane, commercial owner, and reopening rule'],
['qbr-question-backlog','QBR question backlog','customer-qbr-preparation','turn unresolved review questions into dated follow-through','client question, consequence, evidence request, response owner, and closure proof'],
['crm-correction-provenance-log','CRM correction provenance log','crm-account-maintenance','preserve why a material account fact changed','old value, new value, controlling source, editor, and affected records'],
['stakeholder-absence-plan','Stakeholder absence plan','client-onboarding-coordination','keep routine work safe while a decision maker is unavailable','absence window, delegate, authority limit, prohibited decisions, and return review'],
['client-silence-follow-up-rule','Client silence follow-up rule','client-request-routing','follow up without treating silence as consent','last contact, unanswered question, consequence, cadence, stop rule, and escalation owner'],
['portfolio-exception-budget','Portfolio exception budget','account-health-monitoring','show when exceptions displace scheduled reviews','exception class, attention estimate, displaced review, consequence, and portfolio owner'],
['service-credit-preparation-boundary','Service credit preparation boundary','escalation-coordination','assemble evidence without granting commercial authority','client request, agreement source, incident evidence, calculation inputs, and approver'],
['client-metric-definition-card','Client metric definition card','account-reporting','keep measures comparable when definitions change','metric purpose, formula, population, exclusions, refresh time, and owner'],
['handoff-shadow-review','Handoff shadow review','implementation-handoff-support','test a handoff through observed first work','sample task, expected source, observer, mismatch, boundary, and acceptance decision'],
['escalation-audience-map','Escalation audience map','escalation-coordination','limit escalation facts to people who need them','issue class, decision audience, informed audience, sensitivity, channel, and removal rule'],
['client-commitment-sunset-review','Client commitment sunset review','contract-milestone-tracking','close or renew recurring commitments deliberately','commitment source, purpose, recurrence, latest proof, owner decision, and sunset date'],
];
const sources=[{name:'NIST Cybersecurity Framework 2.0',date:'February 26, 2024',url:'https://www.nist.gov/publications/cybersecurity-framework-csf-20',note:'Governance vocabulary, not a performance benchmark.'},{name:'NIST accountability glossary',date:'accessed August 31, 2026',url:'https://csrc.nist.gov/glossary/term/accountability',note:'Supports traceable responsibility.'},{name:'ISO quality management principles',date:'accessed August 31, 2026',url:'https://www.iso.org/quality-management/principles',note:'Supports evidence-based process review.'}];
function sections(name:string,focus:string,fields:string){const subject=name.toLowerCase();return[
{heading:`Define the purpose of the ${subject}`,paragraphs:[`The operating need is to ${focus}. Start with the affected account, review window, client consequence, and exact decision the record must support. A status label cannot show whether the client asked for something, whether the business accepted it, or whether a later condition invalidated it. Record ${fields}. Mark any unavailable field as unknown and name the smallest source check that can resolve it.`,`Keep the unit of work narrow enough to review. One row should describe one decision, expectation, exception, or evidence question. If several accounts or commitments share a cause, link their rows to a controlled parent record rather than collapsing their different dates and consequences. This structure lets the owner change one item without silently changing the rest.`]},
{heading:'Preserve source language and timing',paragraphs:[`Link the approved CRM record, agreement, client message, meeting note, or delivery evidence behind every material statement. Preserve the original wording when it creates an expectation, and write the team interpretation separately. A concise rewrite can accidentally remove a condition or convert a preference into a promise. The source date and effective period make that difference inspectable.`,`Freshness depends on purpose. A signed scope record may remain authoritative for approved work while being unable to describe current delivery. When sources conflict, retain both, rank their authority for this decision, and route the unresolved difference. Do not select the newer or friendlier answer automatically. Record who will reconcile it and the date of the next check.`]},
{heading:'Use observable states',paragraphs:[`Use states tied to evidence: captured, source checking, ready for owner, approved to communicate, waiting for client, action verified, and closed or carried forward. Define what moves the item. Labels such as progressing or nearly done describe confidence rather than a reproducible condition, leaving the next shift without a safe instruction.`,`Write the entry condition, exit proof, allowed editor, and review trigger beside the workflow. Keep acknowledgment separate from resolution. A client can receive a prompt note that the team is checking an item while the underlying decision stays open. The sent message proves communication occurred; it does not prove approval, restoration, acceptance, or completion.`]},
{heading:'Separate preparation from authority',paragraphs:[`A Philippines-based account manager can gather approved facts, maintain the assigned record, request a missing source, organize options, schedule review, and draft neutral client wording. Those tasks improve follow-through without granting authority to change an agreement, approve a credit, make legal or security judgments, provision broad access, or promise work outside approved scope.`,`Name the work owner and decision owner separately. The work owner prepares evidence and the next question. The decision owner accepts the consequence and approves action or client language. If that person is unavailable, use a documented delegation with a limit and expiry; do not infer authority from seniority, calendar access, system permissions, or prior participation.`]},
{heading:'Prepare a truthful client update',paragraphs:[`When the client needs an update before the answer is ready, state what was received, the fact currently confirmed, what is being checked, who owns the review, and when the next update will arrive. Avoid wording that implies cause, approval, completion, or recovery while evidence remains open. A specific next check is more useful than unsupported reassurance.`,`Compare the draft with the ${subject}, source record, and approval note. Remove speculation and sensitive internal detail the audience does not need. Save the approved message or recap back to the account record so communication remains linked to the decision it described. If the client corrects the statement, preserve the correction and its date.`]},
{heading:'Protect access and history',paragraphs:[`Use named accounts and only permissions required to maintain this record. Link controlled material instead of copying private client data into a broad note. Export, deletion, access administration, retention exceptions, and sensitive disclosure remain with authorized owners even when account support prepares the request. Data minimization makes the record easier to hand off as well as safer to store.`,`When a material fact changes, append the correction date, controlling source, editor, reviewer, and affected downstream records. Do not silently rewrite the earlier entry. A later reviewer may need to understand why an update was sent or why work paused. The correction trail supports accountability without forcing each reader to reconstruct the entire account history.`]},
{heading:'Test the handoff',paragraphs:[`At the daily review, inspect new entries, triggered items, and passed next-check dates. At the weekly account review, sample consequential open and closed rows. The purpose is not to reward volume; it is to detect missing sources, unclear owners, stale decisions, and closure claims the available proof cannot reproduce.`,`Ask a receiving person to locate the source, explain the current state, identify the decision owner, prepare a neutral update, and state the closure rule without coaching. Record misunderstandings as workflow findings. Improve the field or instruction that allowed the mismatch instead of adding unstructured prose to every later handoff.`]},
{heading:'Measure without overclaiming',paragraphs:[`A team may inspect completeness, elapsed time between defined states, reopened items, overdue checks, or reviewer disagreement. Each measure needs a fixed population, time window, denominator, and exclusion rule. A high completion percentage does not establish client satisfaction or account performance, and elapsed time alone does not identify who caused a delay.`,`NIST and ISO materials provide governance and evidence vocabulary, not proof that a ${subject} produces a guaranteed result. Contract terms, account complexity, source quality, response time, tool configuration, and owner availability change interpretation. Put those limits beside any finding so a process observation is not repeated later as a client outcome.`]},
{heading:'Close with proof and a reopening trigger',paragraphs:[`Close the entry only when the stated action occurred, the proper owner accepted the decision, evidence is linked, and the client received approved communication where required. If the result is partial, carry the remaining item forward with its own owner and date. A closed task with an unresolved client consequence should fail the next review.`,`Add a reopening trigger such as a client correction, scope change, expired approval, contradictory source, or failed verification. Sample closed items against their original rule. Repeated reopenings show where intake, authority, evidence, or communication design needs repair. The record is complete when another authorized person can reproduce the decision path.`]},
]}
function make([short,name,service,focus,fields]:Topic):RichArticle{return{title:`Philippines account management ${name.toLowerCase()}`,description:`Published August 31, 2026: a detailed operating guide to ${focus}.`,published:'2026-08-31',updated:'2026-08-31',readMinutes:14,heroImage:`/blog-heroes/2026-08-31-${short}.png`,intro:[`Published August 31, 2026. A ${name.toLowerCase()} helps an outsourced account team ${focus}.`,`Build the route-specific record around ${fields}; each field should point to a dated source, authorized decision, or explicit unknown.`],takeaways:[`Use ${fields} as the minimum record.`,'Separate evidence, interpretation, preparation, approval, communication, and closure.','Keep consequential decisions with authorized owners.','Carry uncertainty with a source request, owner, and date.'],sections:sections(name,focus,fields),banners:[{label:'Source',title:'Use a dated record',body:'Keep source and interpretation separate.',href:`/services/${service}`,link:'See related support'},{label:'Owner',title:'Separate work and decisions',body:'Preparation does not grant approval.',href:'/services/account-reporting',link:'See reporting support'},{label:'Proof',title:'Verify closure',body:'A message is not resolution.',href:'/contact-us',link:'Contact Us'}],table:{caption:`${name} control fields`,headers:['Layer','Minimum record','Limit'],rows:[['Purpose','Account, period, consequence','Not a performance claim'],['Evidence','Source, date, fact, limitation','Not cause'],['Authority','Work owner, decision owner, state','Not permission'],['Closure','Rule, proof, reopen trigger','Not a message']]},chart:[{label:'Source',value:100,color:'#e8c98e'},{label:'Owner',value:75,color:'#b9dfce'},{label:'Proof',value:50,color:'#ffd9ce'}],chartMeta:{title:name,desc:'Source, owner, proof workflow.',heading:'Control path',method:'Process aid, not measured performance.'},quote:{text:'Accountability allows actions to be traced to an entity.',source:'NIST accountability glossary',url:'https://csrc.nist.gov/glossary/term/accountability'},script:[`We reviewed ${focus} against [source] on [date]. [Owner] is deciding [open item].`,'The next approved update is [date]; closure requires [proof].'],faqs:[{q:`What belongs in a ${name.toLowerCase()}?`,a:`At minimum: ${fields}, plus consequence and closure rule.`},{q:'What remains with the owner?',a:'Commercial, legal, security, access, and scope decisions.'},{q:'When is it complete?',a:'When evidence, authority, communication, and closure agree.'}],sources};}
export const august31BlogPosts=topics.map(t=>({slug:`philippines-account-management-${t[0]}`,title:`Philippines account management ${t[1].toLowerCase()}`,published:'2026-08-31' as const,excerpt:`A practical guide to ${t[3]}.`,minutes:14}));
export const august31RichArticles:Array<[string,RichArticle]>=topics.map(t=>[`philippines-account-management-${t[0]}`,make(t)]);
