import type { ResearchPost } from './research-data';

type Topic=readonly[string,string,'Hiring Controls'|'Scope Benchmarks'|'Workflow Design',string,string,string,string];
const topics:Topic[]=[
 ['client-commitment-reopen-consistency-study','When do reviewers reopen a closed client commitment?','Workflow Design','whether reviewers apply the same reopen rule when new evidence challenges a closed commitment','give independent reviewers matched closure packets plus later evidence, then compare reopen decisions, cited rules, uncertainty, and proposed client updates','The later evidence must be presented with its original timestamp and source. Agreement can show reproducibility under this protocol, but it cannot prove the original owner acted reasonably or predict the client outcome.','2026-08-31-handoff-shadowing-error-detection.png'],
 ['account-contact-authority-decay-research','How quickly does client contact authority evidence become unreliable?','Hiring Controls','where stored contact roles stop matching current approval authority','sample decisions across a fixed period and compare the recorded role, contemporaneous authority source, requested decision class, response, and later correction','A changed title is not the only decay event. Delegation, leave, reorganization, and decision-specific limits can alter authority without a CRM role change.','2026-08-31-client-decision-expiry-bias-study.png'],
 ['duplicate-client-request-promise-loss','Do merged client requests lose distinct promises?','Workflow Design','whether duplicate-request merging hides a recipient, promised response, deadline, or acceptance condition','trace matched request groups from each original message through merge, assignment, updates, claimed closure, and recipient acknowledgement','Similarity of subject matter is insufficient for merging. Code differences in recipient, requested outcome, deadline, authority, and promise before treating two records as one unit.','2026-08-31-account-queue-invisible-work-analysis.png'],
 ['qbr-claim-approval-reproducibility','Can reviewers reproduce approval decisions for QBR claims?','Scope Benchmarks','whether reviewers reach consistent approval decisions from the same frozen metric and source packet','ask independent reviewers to assess identical claims using a predefined rubric for definition, population, period, calculation, uncertainty, and authority','A shared approve-or-reject result may hide different reasoning. Retain cited evidence and limitations so agreement on the label is not mistaken for agreement on meaning.','2026-08-31-account-metric-definition-drift-study.png'],
 ['temporary-account-coverage-acceptance-study','What proves that temporary account coverage returned cleanly?','Scope Benchmarks','whether returning owners can reconstruct decisions, client wording, open risks, and next actions after temporary coverage','compare the pre-coverage snapshot, activity record, return brief, independent owner reconstruction, acceptance response, and first post-return action','A reassignment event proves only a system change. This protocol treats return as accepted only when the usual owner can reconstruct the bounded record and explicitly accepts or rejects its open items.','2026-08-31-handoff-shadowing-error-detection.png'],
];
const sources=[
 {name:'NIST Cybersecurity Framework 2.0',date:'February 26, 2024',url:'https://www.nist.gov/publications/cybersecurity-framework-csf-20',note:'Governance and control vocabulary, not an account-management benchmark.'},
 {name:'ISO quality management principles',date:'accessed September 7, 2026',url:'https://www.iso.org/quality-management/principles',note:'Evidence-based decisions, process review, and improvement principles.'},
 {name:'NIST accountability glossary',date:'accessed September 7, 2026',url:'https://csrc.nist.gov/glossary/term/accountability',note:'Vocabulary for tracing actions to responsible entities.'},
 {name:'FTC Start with Security',date:'June 2015',url:'https://www.ftc.gov/business-guidance/resources/start-security-guide-business',note:'Access-control and data-minimization guidance.'},
];
function study([slug,title,cluster,question,method,analysis,hero]:Topic):ResearchPost{return {slug,title,cluster,excerpt:`A September 7, 2026 research design examining ${question}.`,headlineStat:'A workflow status cannot by itself prove evidence quality, authority, acceptance, cause, or client outcome',statSource:'Route-specific synthesis of NIST, ISO, and FTC control principles',published:'2026-09-07',datePublished:'2026-09-07',updated:'2026-09-07',hero:`/research-heroes/${hero}`,
 takeaways:[`Study ${question} as a bounded record-level question.`,'Freeze definitions, population, exclusions, evidence cutoff, and analysis rules before sampling.','Use an independent reviewer and retain disagreement.','Report observations separately from interpretation, authority, communication, and outcome.'],
 sections:[
  {heading:'Research question and decision boundary',paragraphs:[`Published September 7, 2026. This report examines ${question}. The unit is one dated account-work record at a defined decision point, not a judgment about a person or company.`,`State which operating decision the result may inform. A finding may support a changed field, owner route, trigger, or acceptance check; it cannot by itself establish retention, revenue, satisfaction, or individual performance.`]},
  {heading:'Population and sampling frame',paragraphs:[`Define the eligible records, study period, inclusion rule, exclusion rule, denominator, and source hierarchy before inspecting outcomes. Include routine, incomplete, disputed, corrected, and reopened records.`,`Stratify where client consequence, channel, contract, owner type, or source system could change interpretation. Count unavailable records and explain missingness rather than silently dropping them.`]},
  {heading:'Route-specific procedure',paragraphs:[`The procedure is to ${method}. Freeze the coding guide first, then retain each source, timestamp, observed fact, uncertainty, work owner, decision owner, client consequence, communication state, and later correction.`,analysis]},
  {heading:'Independent reproduction test',paragraphs:[`Give a second reviewer the same frozen inputs without the first conclusion. Compare decisions and supporting fields, and preserve every disagreement.`,`Classify differences by unclear definition, missing source, inaccessible evidence, stale ownership, authority ambiguity, or judgment. Agreement shows reproducibility under this method; it does not prove accuracy or cause.`]},
  {heading:'Timing and competing explanations',paragraphs:[`Analyze evidence as it existed at the decision point. Preserve later corrections separately so hindsight does not rewrite the tested record.`,`Sequence cannot explain motive. Client dependency, careful approval, access limits, source correction, tool behavior, and internal delay may produce a similar pattern.`]},
  {heading:'Privacy, access, and authority',paragraphs:[`Use the minimum client information needed for the question, work in approved systems, and aggregate results when row-level detail adds no analytical value.`,`A Philippines-based account specialist may prepare evidence and analysis. Contract, financial, legal, security, privacy, access, and scope decisions remain with authorized owners.`]},
  {heading:'Limitations',paragraphs:[`A local sample may omit calls, private messages, inaccessible systems, undocumented work, or later context. Account size, contract wording, tools, geography, and stakeholder availability limit transfer to another portfolio.`,`This design describes evidence patterns. It cannot set a universal threshold, guarantee improvement, or attribute commercial outcomes to account support. Report sample size, missingness, disagreements, and corrections.`]},
  {heading:'Using the finding',paragraphs:[`Report observations separately from explanations. Place plausible alternatives beside the preferred reading and name the evidence that could distinguish them.`,`Any control change needs an owner, effective date, review point, expected proof, and rollback condition. Re-measure with the same definitions.`]},
 ],table:{headers:['Research layer','Required record','Boundary'],rows:[['Design','Question, unit, population, period','Not an outcome claim'],['Evidence','Source, date, fact, missingness','Not a causal explanation'],['Review','Independent coding and disagreement','Agreement is not proof'],['Decision','Owner, action, recheck, rollback','Research does not confer authority']]},sources,
 faqs:[{q:'What is the first research step?',a:'Define the decision, unit, population, period, source hierarchy, exclusions, and evidence cutoff before sampling.'},{q:'What should the finding not claim?',a:'Do not infer motive, cause, revenue, retention, satisfaction, or individual performance from a workflow pattern alone.'},{q:'Who acts on the result?',a:'The named authorized owner decides any contract, commercial, legal, security, privacy, access, or scope response.'}],related:[],internalLinks:[{label:'See account reporting support',href:'/services/account-reporting'},{label:'Review controlled account support',href:'/services/account-health-monitoring'}]};}
export const research20260907=topics.map(study);
