import type { ResearchPost } from './research-data';
type Topic=readonly[string,string,'Hiring Controls'|'Scope Benchmarks'|'Workflow Design',string,string,string,string];
const topics:Topic[]=[
 ['client-commitment-proof-gap-study','Where does proof disappear between a client commitment and closure?','Workflow Design','how a recorded client commitment can reach closed status without matching completion evidence','trace each commitment from its source wording through assignment, claimed completion, owner review, and client acknowledgement','Start with the exact promise. A ticket label may compress away timing, conditions, or the client\'s acceptance test. Code each change in meaning before judging the final status.','2026-08-31-handoff-shadowing-error-detection.png'],
 ['account-risk-label-carryover-bias','Do old account risk labels bias the next portfolio review?','Scope Benchmarks','whether an earlier risk label continues to shape attention after its evidence has expired or been replaced','give reviewers identical current evidence with and without the prior label, then compare ranking, cited reasons, uncertainty, and follow-up choices','The comparison must hide only the historical label, not relevant account facts. A difference can show anchoring under this test, but it cannot explain the reviewer\'s motive or predict a client outcome.','2026-08-31-client-decision-expiry-bias-study.png'],
 ['shared-inbox-ownership-loss-study','How often does shared-inbox routing create invisible account work?','Workflow Design','where client requests lose an accountable owner between receipt, classification, assignment, and response','sample eligible messages and reconstruct receipt, routing events, account linkage, owner acceptance, reply, and closure proof','An assignment event is not owner acceptance. The study should test whether the named person could see the message, understood the expected action, and had authority to take it.','2026-08-31-account-queue-invisible-work-analysis.png'],
 ['qbr-metric-definition-divergence','When do QBR reviewers read the same metric differently?','Hiring Controls','how definition, population, period, and source choices change the meaning of a client-review number','ask independent reviewers to rebuild each selected metric from a frozen source packet and record every definition choice and disagreement','Agreement on the displayed number is a weak test. Reviewers may use the same calculation while attaching different business meaning, so the coding must include the claim the number is meant to support.','2026-08-31-account-metric-definition-drift-study.png'],
 ['temporary-coverage-handoff-loss','What gets lost when temporary account coverage returns to the usual owner?','Scope Benchmarks','whether decisions, client wording, and unresolved exceptions survive a short-term coverage handback','compare the coverage-start snapshot, activity history, return brief, owner reconstruction, and first post-return client action','Temporary coverage has two boundaries: what the substitute may decide and what the returning owner must accept back. Treat a reassigned account as incomplete until both are observable.','2026-08-31-handoff-shadowing-error-detection.png'],
];
const sources=[
 {name:'NIST Cybersecurity Framework 2.0',date:'February 26, 2024',url:'https://www.nist.gov/publications/cybersecurity-framework-csf-20',note:'Governance and control vocabulary, not an account-management benchmark.'},
 {name:'ISO quality management principles',date:'accessed September 4, 2026',url:'https://www.iso.org/quality-management/principles',note:'Evidence-based decisions, process review, and improvement principles.'},
 {name:'NIST accountability glossary',date:'accessed September 4, 2026',url:'https://csrc.nist.gov/glossary/term/accountability',note:'Vocabulary for tracing actions to responsible entities.'},
 {name:'FTC Start with Security',date:'June 2015',url:'https://www.ftc.gov/business-guidance/resources/start-security-guide-business',note:'Access-control and data-minimization guidance.'},
];
function study([slug,title,cluster,question,method,analysis,hero]:Topic):ResearchPost{return {slug,title,cluster,excerpt:`A September 4, 2026 research design examining ${question}.`,headlineStat:'A workflow label alone cannot prove evidence quality, authority, cause, acceptance, or outcome',statSource:'Route-specific synthesis of NIST, ISO, and FTC control principles',published:'2026-09-04',datePublished:'2026-09-04',updated:'2026-09-04',hero:`/research-heroes/${hero}`,
 takeaways:[`Study ${question} as a bounded record-level question.`,'Freeze the population, definitions, exclusions, and evidence cutoff before sampling.','Use a second reviewer and retain disagreement.','Keep observation, interpretation, authority, communication, and outcome in separate fields.'],
 sections:[
  {heading:'Question and decision boundary',paragraphs:[`Published September 4, 2026. This report examines ${question}. The unit is one dated account-work record at a defined decision point, not a person or company.`,`State the operating decision the result may inform. A finding may support a changed field, trigger, owner route, or acceptance check. It cannot by itself establish retention, revenue, satisfaction, or individual performance.`]},
  {heading:'Population and sampling frame',paragraphs:[`Define the eligible records, period, inclusion rule, exclusion rule, denominator, and source hierarchy before looking at outcomes. Include routine, incomplete, disputed, corrected, and reopened records.`,`Stratify when client consequence, channel, contract, owner type, or source system could change interpretation. Count unavailable records rather than quietly dropping them.`]},
  {heading:'Route-specific method',paragraphs:[`The procedure is to ${method}. Freeze the coding guide first. Retain the source, timestamp, observed fact, uncertainty, work owner, decision owner, client consequence, communication state, and later correction.`,analysis]},
  {heading:'Independent reproduction test',paragraphs:[`Give a second reviewer the same frozen inputs without the first conclusion. Compare field-level agreement and keep the disagreements.`,`Classify differences by unclear definition, missing source, inaccessible evidence, stale ownership, authority ambiguity, or judgment. Agreement shows reproducibility under the stated method; it does not prove accuracy or cause.`]},
  {heading:'Timing and competing explanations',paragraphs:[`Record evidence as it existed at the decision point. Preserve later corrections separately so hindsight does not rewrite the test.`,`Sequence cannot prove why something happened. Client dependency, careful approval, access limits, source correction, tool behavior, and internal delay may create a similar pattern.`]},
  {heading:'Privacy and authority',paragraphs:[`Use the minimum client information needed for this question. Work in approved systems and aggregate results when row-level detail adds nothing.`,`A Philippines-based account specialist may prepare evidence and analysis. Contract, financial, legal, security, privacy, access, and scope decisions remain with authorized owners.`]},
  {heading:'Limitations',paragraphs:[`A local sample may omit calls, private messages, inaccessible systems, or undocumented work. Account size, contract wording, tools, geography, and stakeholder availability may limit transfer to another portfolio.`,`This design describes evidence patterns. It cannot set a universal threshold, guarantee improvement, or attribute commercial outcomes to account support. Report sample size, missingness, disagreements, and corrections.`]},
  {heading:'Using the finding',paragraphs:[`Report observations separately from explanations. Put plausible alternatives beside the preferred reading and name the evidence that would distinguish them.`,`Any control change needs an owner, effective date, review point, expected proof, and rollback condition. Re-measure with the same definitions.`]},
 ],table:{headers:['Research layer','Required record','Boundary'],rows:[['Design','Question, unit, population, period','Not an outcome claim'],['Evidence','Source, date, fact, missingness','Not a causal explanation'],['Review','Independent coding and disagreement','Agreement is not proof'],['Decision','Owner, action, recheck, rollback','Research does not confer authority']]},sources,
 faqs:[{q:'What should the study define first?',a:'Define the decision, eligible records, source hierarchy, and evidence cutoff before reviewing outcomes.'},{q:'Why retain disagreement?',a:'It shows where definitions, sources, or authority are not reproducible.'},{q:'What can the result prove?',a:'It can describe bounded evidence patterns under this method, not causation or commercial outcomes.'}],related:topics.filter(t=>t[0]!==slug).slice(0,2).map(t=>t[0]),internalLinks:[{label:'See account reporting support',href:'/services/account-reporting'},{label:'Review account health monitoring',href:'/services/account-health-monitoring'}]};}
export const research20260904:ResearchPost[]=topics.map(study);
