import type { ResearchPost } from './research-data';

const src = (name: string, url: string, note: string) => ({ name, url, date: 'accessed August 20, 2026', note });
const nist = src('NIST Cybersecurity Framework 2.0','https://www.nist.gov/publications/cybersecurity-framework-csf-20','Governance and evidence vocabulary for identifying, protecting, responding, and recovering.');
const iso = src('ISO quality management principles','https://www.iso.org/quality-management/principles','Customer focus, process approach, evidence, and continual improvement context.');
const accountability = src('NIST accountability glossary','https://csrc.nist.gov/glossary/term/accountability','Defines the ability to trace an action to an entity.');
const sba = src('U.S. Small Business Administration, manage your business','https://www.sba.gov/business-guide/manage-your-business','General guidance on written processes, records, and management decisions.');
const privacy = src('Philippine National Privacy Commission, Data Privacy Act','https://privacy.gov.ph/data-privacy-act/','Local personal-data governance context; not a substitute for legal advice.');
const least = src('NIST least privilege glossary','https://csrc.nist.gov/glossary/term/least_privilege','Access should be limited to what assigned work requires.');

export const research20260820: ResearchPost[] = [
  {
    slug:'outsourced-account-handoff-acceptance-evidence', title:'When is an outsourced account handoff actually accepted?', hero:'/research-heroes/2026-08-20-handoff-acceptance.png',
    excerpt:'A research design for distinguishing a sent handoff from a handoff another account owner can safely use.', cluster:'Workflow Design', published:'2026-08-20', datePublished:'2026-08-20', updated:'2026-08-20',
    headlineStat:'A handoff is a state change, not merely a message', statSource:'NIST accountability glossary',
    takeaways:['Test whether the receiving owner can reproduce the account situation from the handoff record.','Separate transfer of context from approval of pending commercial, legal, security, or scope decisions.','Treat missing acceptance evidence as an open transition risk, not as proof that the sender failed.'],
    sections:[
      {heading:'Research question and method',paragraphs:['When is an outsourced account handoff actually accepted? In account management, the question matters whenever a client portfolio, renewal thread, open issue, or reporting cycle changes hands. This study treats the handoff record as the unit of analysis: it asks whether the receiving owner can identify current facts, unresolved decisions, access boundaries, client expectations, and the next review without relying on memory or a private conversation.','Use a purposive sample of ordinary transitions, urgent transitions, and transitions that later required clarification. For each, preserve the source record, transfer timestamp, sender, receiver, open commitments, decision owners, and the evidence used to close the transition. Have a second reviewer attempt reconstruction from the saved record alone, then record which missing fields caused a question. This method measures usability of evidence, not the personal quality of either worker.']},
      {heading:'What acceptance should mean',paragraphs:['A sent note proves that a note was sent. Acceptance should require a separate signal: the receiving owner confirms the account facts, lists unresolved items, identifies any access or approval dependency, and names the next check. A reply such as “got it” is weaker than a bounded confirmation because it does not show whether the receiving person understood a renewal date, a client-sensitive issue, or an authority limit.','The distinction is especially important for outsourced account management. A support specialist may assemble the brief, reconcile approved records, highlight gaps, and request confirmation. The accountable owner still controls contract interpretation, refunds, pricing, security exceptions, staffing promises, and commitments outside the approved scope. Acceptance transfers operational context; it does not silently transfer authority.']},
      {heading:'Evidence interpretation',paragraphs:['A strong handoff record contains the source and date for each material fact, the current state, an owner for every open action, the exact decision still pending, and a rule for what counts as closed. It should preserve uncertainty rather than convert “awaiting client reply” into “on track.” A reviewer can then distinguish absent evidence from a negative outcome.','NIST describes accountability as tracing actions to an entity, while ISO quality principles connect evidence with improvement. Those ideas support a practical test: can the next owner trace why the status was recorded, what was observed, and who must decide? They do not establish a universal handoff format or prove that a client will experience continuity.']},
      {heading:'Operational boundaries',paragraphs:['The safest handoff design uses two lanes. The preparation lane carries account facts, links, dates, prior approved wording, and an inventory of pending tasks. The authority lane names decisions that require an owner, such as changing scope, accepting a risk, approving money movement, granting access, or responding to a legal or security question. Keeping those lanes visible reduces the chance that a polished summary becomes an accidental approval.','For a Philippines-based support role, access should match the assigned account work and should be reviewed when the account or assignment changes. Avoid copying personal information into a handoff merely for completeness. The Data Privacy Act supplies local governance context, while the authorized client instructions and accountable privacy or security owner determine the actual control.']},
      {heading:'How to use the finding',paragraphs:['A transition review should produce a small decision record rather than a score that obscures the evidence. List the fields that were present, the fields that required a follow-up, the owner who resolved each ambiguity, and the date on which the receiving person could safely act. If the account is moving during a live client issue, preserve the earlier state and attach the new decision rather than overwriting the narrative. This lets a later reviewer see whether the handoff itself was incomplete or whether the account changed after acceptance.','The finding should also inform role design. A support specialist may own the completeness check and reminder queue, while the account owner decides which missing facts are material. That division is not bureaucracy: it makes the cost of an unresolved item visible and prevents a handoff checklist from becoming a substitute for judgment.']},
    ], table:{headers:['Acceptance signal','What to inspect','Boundary'],rows:[['Context','Source, date, current state','Not a complete history'],['Ownership','Receiver and open-action owners','Not decision approval'],['Authority','Pending choices and approver','Not delegated commercial power'],['Closure','Evidence against the rule','Not a sent message']]},
    sources:[nist,accountability,iso,privacy], faqs:[{q:'Is a reply enough to accept a handoff?',a:'Only if the approved rule defines the reply as a substantive confirmation and the record shows what was checked.'},{q:'Who owns a risky decision?',a:'The named business, legal, security, finance, or client owner; the coordinator prepares and routes evidence.'}], related:[], internalLinks:[{label:'See implementation handoff support',href:'/services/implementation-handoff-support'},{label:'Read account reporting support',href:'/services/account-reporting'}]
  },
  {
    slug:'outsourced-account-review-sample-bias', title:'Does an account review sample represent the outsourced portfolio?', hero:'/research-heroes/2026-08-20-review-sampling.png',
    excerpt:'How to test whether routine reviews hide delayed, disputed, or low-visibility client account work.', cluster:'Scope Benchmarks', published:'2026-08-20', datePublished:'2026-08-20', updated:'2026-08-20',
    headlineStat:'A convenient sample answers a narrower question than a portfolio sample', statSource:'ISO quality management principles',
    takeaways:['Define the portfolio frame before selecting records.','Stratify by account state, not only by account size or activity volume.','Report what the sample excludes before interpreting a pattern.'],
    sections:[
      {heading:'Question and evidence scope',paragraphs:['Does an account review sample represent the outsourced portfolio? A manager may review the newest, easiest, or most visible accounts and then describe the result as portfolio health. This study asks a more precise question: how does the sampling frame change what a reviewer can legitimately say about client follow-up, open commitments, escalations, renewals, and reporting records?','Build the frame from an approved account list and a fixed observation window. Label each account by activity level, open commitment state, renewal proximity, escalation state, and whether the source record is complete enough to locate. Draw one sample from the whole frame and comparison samples from quiet, delayed, and exception strata. Record exclusions before looking at outcomes so the selection rule does not move after the result appears.']},
      {heading:'Why visibility distorts the review',paragraphs:['High-activity accounts generate more notes and more opportunities to appear healthy because the team can point to recent work. Quiet accounts may be stable, neglected, waiting on a client, or missing from the system. An exception queue may contain the greatest operational risk while representing a small share of records. Treating volume as importance creates a predictable blind spot for outsourced account management.','The account manager can assemble the frame, identify missing records, and code observable states. A decision owner should approve the definitions for “active,” “at risk,” “waiting,” and “closed,” because those labels can affect staffing, client communication, and escalation. A sample can reveal record conditions; it cannot settle a disputed client sentiment or infer a commercial outcome.']},
      {heading:'A defensible sampling design',paragraphs:['Start with an inclusion rule that another reviewer could apply: for example, accounts assigned during the window and present in the authorized portfolio record at the frame date. Stratify only on fields available before selection. Keep a log of selected and excluded records, the reason for exclusion, and whether the exclusion itself indicates a data-quality issue. For small portfolios, review all exception records and sample routine records rather than pretending that a random draw solves every risk.','Analyze the result by stratum and show the denominator. A finding that three of four delayed accounts lacked a next check is different from a finding that three of four accounts overall lacked one. Avoid turning a local descriptive rate into a benchmark for all outsourced teams. Repeat the frame after a defined change so differences in selection do not masquerade as improvement.']},
      {heading:'Evidence, privacy, and role limits',paragraphs:['Keep source links, dates, coding notes, and reviewer disagreements with the study record, but minimize personal information. The Philippine privacy framework is relevant to handling account contacts and correspondence; it does not prescribe a sampling statistic. Access should be limited to the records needed for the review, and any export or retention decision should remain with the authorized owner.','External quality guidance supports a factual approach and continual improvement, but it cannot tell an account team which accounts deserve priority under a particular contract. The support role may surface a quiet account, reconcile the record, draft an owner-ready question, and schedule a review. It should not independently label a client relationship unhealthy, promise remediation, or alter scope.']},
      {heading:'Limitations and conclusion',paragraphs:['Sampling from one portfolio cannot establish a market rate or causal relationship between review design and retention. Labels may be inconsistent, the frame may omit informal work, and a quiet account may be quiet for a legitimate reason. A second reviewer can improve coding consistency but cannot recover evidence that was never recorded.','The conclusion is evidence-led and bounded: a portfolio review is representative only for the frame, strata, and time window it declares. Outsourced account management teams should publish exclusions, inspect exception strata deliberately, and state the question each sample can answer.']},
      {heading:'A decision rule for managers',paragraphs:['Managers should decide in advance what a sample is allowed to change. It may trigger a source cleanup, a targeted account review, a revised definition, or a capacity conversation. It should not silently change a client status, create a service commitment, or become a performance judgment about an individual. Preserve the selected records and the selection rule so a later review can distinguish a changed portfolio from a changed lens.','When evidence is thin, the correct output is a bounded unknown: which accounts were observed, which were not, why the exclusions matter, and who will close the gap. That answer is more useful than a precise-looking percentage with no denominator.']},
    ], table:{headers:['Sampling choice','Reveals','Does not prove'],rows:[['Whole-frame draw','Overall record mix','Portfolio outcome'],['Exception stratum','Rare-risk evidence','Risk prevalence'],['Quiet-account stratum','Visibility gaps','Neglect cause'],['Repeated frame','Change over time','Causation']]}, sources:[iso,nist,sba,privacy], faqs:[{q:'Should every account be sampled equally?',a:'Not for every question; preserve the frame and stratify when rare exceptions or quiet accounts matter.'},{q:'Can a sample score client health?',a:'It can describe observed evidence under a defined rule, but health judgments and commitments need accountable owner review.'}], related:[], internalLinks:[{label:'See account health monitoring',href:'/services/account-health-monitoring'},{label:'Read customer QBR preparation',href:'/services/customer-qbr-preparation'}]
  },
  {
    slug:'outsourced-account-renewal-evidence-timing', title:'When should renewal evidence be frozen for an outsourced account review?', hero:'/research-heroes/2026-08-20-renewal-evidence.png',
    excerpt:'A research question about cutoffs, late-arriving facts, and the difference between a snapshot and a forecast.', cluster:'Renewal Evidence', published:'2026-08-20', datePublished:'2026-08-20', updated:'2026-08-20',
    headlineStat:'A renewal packet is a dated view, not a timeless verdict', statSource:'NIST Cybersecurity Framework 2.0',
    takeaways:['Set a snapshot cutoff and a separate late-evidence rule.','Keep observed delivery, relationship signals, and owner forecasts distinct.','Route commercial choices to the accountable owner.'],
    sections:[
      {heading:'Research question and method',paragraphs:['When should renewal evidence be frozen for an outsourced account review? Renewal packets often mix delivered work from last month, a client message from yesterday, and a forecast written today. This study asks whether a defined evidence cutoff makes the packet more reproducible without hiding material information that arrives afterward.','Compare three packet versions for a sample of accounts: evidence at the stated cutoff, late-arriving evidence logged after the cutoff, and the final owner decision record. Code each item by source, event date, receipt date, confidence, commercial relevance, and decision authority. A second reviewer should reconstruct the packet as it stood at the cutoff and list what could not have been known then.']},
      {heading:'Snapshot versus decision',paragraphs:['A cutoff answers “what was available for this review?” It does not answer “what will the client do?” The packet should separate verified delivery or activity, unresolved commitments, client-supplied signals, and forecasts. A late client reply can be material without changing the truth of the earlier snapshot. Add it as a dated update rather than rewriting history.','For outsourced account management, the preparation role can gather approved reports, reconcile dates, flag missing evidence, and draft neutral questions. It should not infer a renewal probability, change commercial terms, offer a discount, or promise a remedy. The decision owner can decide what the evidence means under the contract and relationship context.']},
      {heading:'Timing controls',paragraphs:['Set the cutoff in the packet header and record the time zone, source systems, and inclusion rule. Define a late-evidence channel with a materiality test: new information should be attached when it changes a stated fact, open commitment, risk, or owner decision. If it does not change the decision record, retain it as context rather than silently merging it into the snapshot.','NIST’s lifecycle framing is useful here because identification, response, and recovery are different activities. A renewal packet identifies evidence; an owner chooses a response; later follow-up checks what happened. Combining those stages into one green or red status makes the report easier to read but harder to audit.']},
      {heading:'Limitations and safeguards',paragraphs:['Client sentiment is not a stable field, contracts differ, and late evidence can arrive through channels that are not in the authorized system. A cutoff may create false confidence if the sample excludes informal conversations. Conversely, continuous edits can make it impossible to know what the owner saw. Keep a versioned evidence trail and state what remains unknown.','Use least-privilege access for source systems and minimize copied personal information. The local privacy framework and approved client instructions govern handling; public frameworks provide context, not a legal conclusion. A packet is decision support, not a guarantee of retention, revenue, satisfaction, or service performance.']},
      {heading:'Evidence-led conclusion',paragraphs:['The best cutoff is the one that matches the owner’s review event and is applied consistently, with a transparent lane for material late evidence. That makes a renewal packet reproducible while preserving the reality that account conditions change.','For outsourced account management, freeze the snapshot, log late facts separately, and ask the accountable owner to approve any change to the recommendation or client language. This conclusion supports traceability without pretending that timing controls can predict a commercial decision.']},
      {heading:'What a reviewer should challenge',paragraphs:['A reviewer should challenge any packet that uses a forecast as though it were an observed result, combines events from different periods without labels, or removes a late fact because it arrived after the cutoff. Ask what the owner knew, when the owner knew it, which evidence was unavailable, and what decision would change if the late fact were confirmed. These questions make the packet useful for both a renewal conversation and a later retrospective.','The review should end with a named follow-up and a recheck date. If the account owner chooses not to change the recommendation, record that choice and its basis. The purpose is not to force one commercial answer; it is to ensure the answer is traceable to the evidence available at the decision point. A dated packet also makes it easier to explain a later change without accusing the earlier review of being wrong.']},
    ], table:{headers:['Evidence class','Date to keep','Interpretation'],rows:[['Delivered work','Event and source date','Observed fact'],['Client message','Sent and received dates','Signal, not forecast'],['Owner forecast','Decision timestamp','Analysis, not fact'],['Late evidence','Receipt and linked cutoff','Update, not rewrite']]}, sources:[nist,accountability,iso], faqs:[{q:'Does freezing evidence hide new information?',a:'No. A material late-evidence lane preserves the original snapshot and makes the update visible.'},{q:'Who approves renewal wording?',a:'The accountable commercial or client owner under the applicable scope and contract.'}], related:[], internalLinks:[{label:'See renewal administration',href:'/services/renewal-administration'},{label:'Read account reporting support',href:'/services/account-reporting'}]
  },
  {
    slug:'outsourced-account-communication-authority-boundaries', title:'Can an outsourced account manager send a client update without creating a commitment?', hero:'/research-heroes/2026-08-20-communication-authority.png',
    excerpt:'Research on how preparation, approval, delivery, and recordkeeping can be separated in client communication.', cluster:'Hiring Controls', published:'2026-08-20', datePublished:'2026-08-20', updated:'2026-08-20',
    headlineStat:'Message speed and decision authority are different controls', statSource:'NIST least privilege glossary',
    takeaways:['Classify messages by the decision they imply, not by channel alone.','Keep approved wording attached to the exact fact and scope.','Measure the trace from draft to sent message to avoid confusing activity with authorization.'],
    sections:[
      {heading:'Research question and evidence scope',paragraphs:['Can an outsourced account manager send a client update without creating a commitment? The question is not whether a coordinator can write clearly. It is whether the record makes a safe distinction between preparing a factual update, sending approved language, and making a statement that changes a client’s reasonable expectation.','Review a sample of routine updates, delay notices, risk messages, and scope-related requests. For each, record the source fact, intended audience, implied commitment, preparation owner, approval owner, sender, version, and resulting client record. Have a second reviewer classify authority from the message alone, then compare that classification with the approved matrix.']},
      {heading:'Four communication states',paragraphs:['A practical model separates preparation, approval, delivery, and archive. Preparation turns approved facts into a draft. Approval confirms the wording, audience, timing, and boundaries. Delivery sends the approved message through an authorized channel. Archive preserves the sent version and any reply. A coordinator may own the first and fourth states while only sending from the third when the matrix permits it.','The model matters because “please update the client” is ambiguous. A status update may be routine; a statement about credits, contract scope, data exposure, staffing, or a resolution may create a material expectation. Least privilege applies to communication authority as well as system access: the role should have only the ability needed for assigned work.']},
      {heading:'Methodological interpretation',paragraphs:['Code the message for what it says, what it implies, and what approval evidence exists. Do not judge tone as a proxy for risk. A friendly sentence can still promise an unapproved date; a terse sentence can accurately state that a decision is pending. Compare the original draft with the approved and sent versions so edits remain visible.','NIST accountability supports tracing who prepared and approved an action. The evidence can show whether the path was followed; it cannot prove the client interpreted every sentence as intended or that a later outcome was caused by the message. Record a reply as new evidence, not as proof that the original authority boundary was adequate.']},
      {heading:'Boundaries for account support',paragraphs:['A Philippines-based account specialist can gather approved facts, prepare a draft, schedule a message, update the CRM, and flag a request that needs an owner. Contract changes, discounts, refunds, legal or security conclusions, access decisions, staffing promises, and out-of-scope commitments remain with the named owner. The communication record should make that boundary visible to the sender and reviewer.','Minimize copied personal information and use only approved channels. The privacy source provides governance context; the client’s authorization, retention rules, and incident route control actual handling. Keep the matrix current when services, systems, or account assignments change.']},
      {heading:'Limitations and conclusion',paragraphs:['Message classification is context-dependent. A phrase harmless in one contract may create a promise in another. Reviewers may disagree about implied commitment, and a sample from one team cannot establish a universal error rate. Use disagreements to sharpen definitions and require owner review where the cost of ambiguity is high.','The evidence-led conclusion is that an outsourced account manager can send a client update safely when the message class, source fact, approved wording, authority, and archive rule are explicit. Speed should come from a clear matrix, not from assuming that every update is routine.']},
      {heading:'Testing the matrix in practice',paragraphs:['Pilot the authority matrix on messages that look routine but carry different consequences: a meeting confirmation, a delayed deliverable notice, a request for a new feature, and a question about a sensitive record. Ask independent reviewers to classify them before discussing the answer. Where they disagree, revise the class definition or add an approval gate. The aim is a matrix that a busy account team can apply under pressure without guessing.','Track the transition from draft to archive. If a message was changed after approval, record who changed it and whether the revised version required a new review. This creates a useful audit trail while keeping the coordinator responsible for disciplined preparation rather than for promises outside the role.']},
    ], table:{headers:['State','Required evidence','Authority boundary'],rows:[['Prepare','Source and draft version','No new promise'],['Approve','Named owner and scope','Decision remains owner'],['Send','Authorized channel and sender','Only approved class'],['Archive','Sent copy and reply','Not outcome proof']]}, sources:[least,accountability,privacy,iso], faqs:[{q:'Can the coordinator send routine updates?',a:'Yes when the message class and approved wording explicitly authorize that action.'},{q:'What if the client asks for a new commitment?',a:'Record the request and route it to the accountable owner; do not imply approval.'}], related:[], internalLinks:[{label:'See client request routing',href:'/services/client-request-routing'},{label:'Read account reporting support',href:'/services/account-reporting'}]
  },
  {
    slug:'outsourced-account-record-freshness-decay', title:'How quickly does account context become stale after a client change?', hero:'/research-heroes/2026-08-20-record-freshness.png',
    excerpt:'A bounded research design for field-specific freshness rules across CRM notes, commitments, access, and reporting.', cluster:'Data Quality', published:'2026-08-20', datePublished:'2026-08-20', updated:'2026-08-20',
    headlineStat:'Freshness is a property of a field’s decision use, not a single universal age limit', statSource:'NIST Cybersecurity Framework 2.0',
    takeaways:['Test freshness against a change trigger, not only a calendar age.','Separate stale evidence from incorrect evidence.','Ask the owner to define the recheck required before reuse.'],
    sections:[
      {heading:'Research question and method',paragraphs:['How quickly does account context become stale after a client change? An account record can contain a correct fact that is no longer safe to reuse: a contact role changes, a renewal date moves, an access assignment ends, or a client preference is superseded. This study asks whether field-specific freshness triggers outperform one blanket rule such as “review everything monthly.”','Sample account fields by use: client contacts, open commitments, renewal dates, current scope, access assignments, health signals, and reporting definitions. For each field, record the last verified date, the next decision that relied on it, the change event that could invalidate it, and the recheck performed. Ask a second reviewer whether the field remained usable at the decision time and why.']},
      {heading:'Freshness versus accuracy',paragraphs:['A stale record is not necessarily false. It is evidence whose age or change exposure makes reuse uncertain. A client contact can remain correct for months; an access assignment may become unsafe immediately after a role change. A report definition can be accurate but unsuitable after the measurement scope changes. The trigger and the decision determine the required recheck.','This distinction prevents an account team from creating pointless updates while still protecting high-consequence fields. The support role can flag dates, compare approved sources, and route a recheck. It should not infer a new contract scope, grant or revoke access, or declare a security or privacy status without the authorized owner.']},
      {heading:'A field-specific test',paragraphs:['For each field, define a freshness event before reviewing records. Examples include a client-notified role change for contacts, an owner decision for scope, a system-assignment change for access, and a revised metric definition for reporting. Then test whether the record shows the event, the source, the reviewer, and the resulting state. If no event is known, record the uncertainty instead of treating age alone as proof.','NIST’s governance and protection concepts offer a vocabulary for identifying what must be known and limiting exposure. ISO quality principles support using evidence for decisions. Neither source establishes a universal number of days. Local contracts, tools, client processes, and risk owners determine the appropriate threshold.']},
      {heading:'Operational implications',paragraphs:['Freshness checks belong at the moment a field is reused, not only during a periodic cleanup. Before a QBR, renewal packet, handoff, or client update, the account manager can run a targeted recheck of the fields that support that decision. Keep the old value and its source date visible, then append the new verified state so history is not erased.','Use least privilege and data minimization when checking records. Personal information should remain in approved systems and be copied only when necessary. The privacy source is a governance reference, not permission to export data. Any incident, retention, or access-administration choice should be routed to the designated owner.']},
      {heading:'Prioritizing freshness work',paragraphs:['Not every field deserves the same review burden. Start with fields that can change authority, client expectation, privacy exposure, or the interpretation of a report. For lower-consequence context, a periodic review may be sufficient. For a renewal date, access assignment, or approved scope, the triggering event should create a visible recheck task. This prioritization keeps the routine practical while protecting the decisions most likely to be affected by stale context.','Record why a field was considered fresh, not only the date it was checked. A reviewer should be able to see the source, the trigger considered, the current value, and the owner who accepted the evidence for the next use. When the trigger cannot be verified, the record should say “not confirmed” and route a dated question rather than silently passing the old value forward.']},
      {heading:'Using stale-context findings',paragraphs:['A freshness finding should lead to a targeted owner decision: refresh a source, confirm a client instruction, review an access assignment, or mark the field unavailable for the current report. Do not solve every stale value by copying it into a new system. The evidence record should show whether the value was reverified, superseded, or intentionally excluded. That preserves a clear boundary between cleanup work and a substantive account decision.','For a distributed account team, the best control is often a small trigger list attached to the event that uses the data. Handoff, renewal, QBR preparation, and access changes can each invoke a different set of checks. This is more defensible than a universal age rule because it links effort to the decision at risk.']},
    ], table:{headers:['Field','Possible invalidator','Recheck'],rows:[['Contact role','Client role change','Approved source'],['Scope','Owner decision','Current authorization'],['Access','Assignment change','Named access owner'],['Metric','Definition revision','Current data dictionary']]}, sources:[nist,least,iso,privacy], faqs:[{q:'Is monthly review enough?',a:'Not for every field; high-consequence fields may need an event-triggered check.'},{q:'Who decides the threshold?',a:'The accountable owner for the process, contract, privacy, security, or reporting decision.'}], related:[], internalLinks:[{label:'See CRM account maintenance',href:'/services/crm-account-maintenance'},{label:'Read account reporting support',href:'/services/account-reporting'}]
  }
];
