import type { ResearchPost } from './research-data';

type Topic = readonly [string, string, 'Hiring Controls' | 'Scope Benchmarks' | 'Workflow Design', string, string, string];
const topics: Topic[] = [
  ['account-context-decay-study', 'How quickly does account context become unsafe to reuse?', 'Scope Benchmarks', 'dated account context being reused after its operating assumptions change', 'compare source age, purpose, intervening events, reviewer confidence, and later corrections', '2026-08-31-account-metric-definition-drift-study.png'],
  ['client-reply-promise-reliability-study', 'Reliability of promised client reply dates', 'Workflow Design', 'promised response dates losing ownership between preparation and approval', 'trace each promise through source, decision dependency, owner handoff, sent evidence, and any revised date', '2026-08-31-client-silence-interpretation-research.png'],
  ['escalation-fact-interpretation-agreement', 'Do reviewers agree on escalation facts and interpretations?', 'Hiring Controls', 'different reviewers converting the same account evidence into incompatible escalation summaries', 'independently code observed facts, interpretations, unknowns, consequence, audience, and decision route', '2026-08-31-account-queue-invisible-work-analysis.png'],
  ['qbr-action-closure-validity-study', 'Validity of closure claims for QBR actions', 'Workflow Design', 'meeting actions being marked complete without evidence of the intended outcome', 'compare the original decision, assigned action, due date, completion artifact, acceptance evidence, and reopening events', '2026-08-31-handoff-shadowing-error-detection.png'],
  ['crm-conflict-resolution-reproducibility', 'Can CRM source-conflict decisions be reproduced?', 'Hiring Controls', 'account data corrections depending on private memory instead of a reviewable source hierarchy', 'replay sampled corrections from competing sources, field purpose, authority rules, timestamps, and reviewer rationale', '2026-08-31-account-metric-definition-drift-study.png'],
];

const sources = [
  { name: 'NIST Cybersecurity Framework 2.0', date: 'February 26, 2024', url: 'https://www.nist.gov/publications/cybersecurity-framework-csf-20', note: 'Governance and control vocabulary, not an account-management benchmark.' },
  { name: 'ISO quality management principles', date: 'accessed September 1, 2026', url: 'https://www.iso.org/quality-management/principles', note: 'Evidence-based decision and improvement principles.' },
  { name: 'NIST accountability glossary', date: 'accessed September 1, 2026', url: 'https://csrc.nist.gov/glossary/term/accountability', note: 'Traceable responsibility vocabulary.' },
  { name: 'FTC Start with Security', date: 'June 2015', url: 'https://www.ftc.gov/business-guidance/resources/start-security-guide-business', note: 'Access-control and data-minimization guidance.' },
];

function study([slug, title, cluster, question, method, hero]: Topic): ResearchPost {
  return {
    slug, title, cluster, excerpt: `A bounded research design examining ${question}.`, headlineStat: 'A recorded status is not evidence of cause, authority, acceptance, or outcome', statSource: 'Route-specific synthesis of NIST, ISO, and FTC control principles', published: '2026-09-01', datePublished: '2026-09-01', updated: '2026-09-01', hero: `/research-heroes/${hero}`,
    takeaways: ['Define the decision, unit, population, and competing explanations before sampling.', 'Include missing, disputed, reopened, and apparently successful records.', 'Use independent recoding to test whether a second reviewer can reproduce the finding.', 'Separate facts, interpretation, preparation, authority, communication, and verified closure.'],
    sections: [
      { heading: 'Research question and boundary', paragraphs: [`Published September 1, 2026. This report examines ${question}. The unit is one dated account record at a defined decision point. It is designed to improve an operating control, not estimate industry performance, satisfaction, retention, revenue, or individual productivity.`, `Name the management decision that a finding could inform before records are selected. Legitimate responses may include changing a field, source rule, review trigger, owner route, or communication control.`] },
      { heading: 'Sampling design', paragraphs: [`Define the population, time window, inclusion rule, exclusion rule, denominator, and source hierarchy in advance. Include incomplete, conflicting, returned, reopened, and clean records so the sample does not remove the cases most likely to expose ambiguity.`, `Stratify when account consequence, channel, contract type, workflow state, or source system may change interpretation. Preserve the reason for every exclusion. Missing evidence is a result when the process requires that evidence at the decision point.`] },
      { heading: 'Route-specific method', paragraphs: [`The procedure is to ${method}. Freeze the coding guide before reviewing outcomes. Record source, source date, actor, observed fact, interpretation, work owner, decision owner, client consequence, communication state, closure rule, and reopening trigger.`, `Have a second reviewer independently code a defined subset. Retain disagreements and determine whether unclear definitions, inaccessible evidence, stale ownership, or ambiguous authority caused them. Agreement supports reproducibility; it does not prove causation.`] },
      { heading: 'Observation versus explanation', paragraphs: [`An observation reports what an approved source contained during the stated window. Preserve later corrections and remembered conversations separately. Combining them into one fact prevents a decision owner from seeing which part is direct evidence and which remains a hypothesis.`, `Sequence alone does not establish cause. Waiting may reflect a client dependency, careful approval, missing access, source correction, or avoidable internal delay. A quick result may still be unsafe if its authority or evidence was weak.`] },
      { heading: 'Freshness and definition controls', paragraphs: [`Freshness is purpose-specific. An agreement may remain authoritative for scope but cannot prove current delivery. Define freshness by field purpose and consequence, then record the exact as-of time rather than labeling the whole account current.`, `Keep formulas, populations, exclusions, states, and completion rules stable during the study. If a definition changes, version it and analyze the periods separately. A familiar label can conceal a materially different measure.`] },
      { heading: 'Privacy, access, and authority', paragraphs: [`Use the minimum account data needed for the research question. Work in approved systems with named access, and report aggregated patterns when row-level detail is unnecessary. Do not copy credentials, identity records, financial data, or sensitive personnel information into the study file.`, `Researchers may prepare evidence and identify control questions. Commercial, legal, privacy, security, contract, and client-commitment decisions remain with authorized owners. The study does not confer operational authority.`] },
      { heading: 'Analysis and competing explanations', paragraphs: [`Report counts with their denominator and missingness. Separate active work time from client waiting, owner waiting, unavailable evidence, and verification. Present distributions or case classes when an average would hide consequential variation.`, `Test at least one competing explanation for each pattern. Reviewer disagreement may reflect a weak coding guide rather than weak execution; high completion may reflect a permissive closure rule rather than reliable outcomes.`] },
      { heading: 'Limitations and use', paragraphs: [`This documentary design cannot establish causation, universal benchmarks, worker performance, legal compliance, financial impact, or client satisfaction. Records may be incomplete, later corrections may change interpretation, and one company’s systems may not generalize to another.`, `Use findings to propose a bounded control change, assign an owner, and define the evidence that will show whether the change worked. Re-sample after implementation and preserve negative or mixed results instead of turning a process observation into a guarantee.`] },
    ],
    table: { headers: ['Evidence layer', 'Record', 'Analytical limit'], rows: [['Population', 'Window, inclusion, exclusion, denominator', 'Not an industry sample'], ['Observation', 'Source, timestamp, exact fact', 'Not cause'], ['Interpretation', 'Code, reviewer, disagreement', 'Not owner authority'], ['Outcome', 'Closure proof and reopen event', 'Not satisfaction or revenue']] }, sources,
    faqs: [{ q: 'What can this design establish?', a: 'It can show whether sampled records support a reproducible operating interpretation under the stated definitions.' }, { q: 'What can it not establish?', a: 'It cannot establish universal rates, causality, worker performance, compliance, satisfaction, retention, or financial impact.' }, { q: 'Why retain disagreement?', a: 'Disagreement shows where definitions, sources, or authority boundaries do not yet support consistent review.' }],
    related: [], internalLinks: [{ label: 'See account reporting support', href: '/services/account-reporting' }, { label: 'Review client request routing support', href: '/services/client-request-routing' }],
  };
}

export const research20260901: ResearchPost[] = topics.map(study);
