import type { ResearchPost } from './research-data';

const checked = 'checked October 5, 2026';
const sources = [
  {name:'NIST Cybersecurity Framework 2.0',date:`February 26, 2024; ${checked}`,url:'https://www.nist.gov/cyberframework',note:'Primary governance framework used to structure ownership, monitoring, response, and improvement; it does not prescribe account-management outcomes.'},
  {name:'NIST SP 800-53 Rev. 5, Release 5.2.0',date:`August 27, 2025; ${checked}`,url:'https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final',note:'Primary control catalog used for audit, least privilege, information integrity, monitoring, and change-control concepts; controls require local tailoring.'},
  {name:'Standards for Internal Control in the Federal Government',date:`May 15, 2025; ${checked}`,url:'https://www.gao.gov/products/gao-25-107721',note:'Authoritative source for quality information, control activities, monitoring, remediation, and segregation of duties.'},
  {name:'Start with Security: A Guide for Business',date:`June 2015; ${checked}`,url:'https://www.ftc.gov/business-guidance/resources/start-security-guide-business',note:'Authoritative business guidance on data minimization, access, retention, and service-provider oversight.'},
  {name:'Data Privacy Act of 2012',date:checked,url:'https://privacy.gov.ph/data-privacy-act/',note:'Primary Philippine legal source for personal-information context; qualified owners determine applicability and required handling.'},
  {name:'Quality management principles',date:checked,url:'https://www.iso.org/quality-management/principles',note:'Authoritative overview of customer focus, process approach, evidence-based decisions, improvement, and relationship management.'},
];

type Draft={slug:string;title:string;cluster:string;excerpt:string;headline:string;hero:string;service:string;related:string[];sections:{heading:string;paragraphs:string[]}[];rows:string[][]};
const drafts:Draft[]=[
  {
    slug:'client-evidence-expiry-trigger-study',title:'When should an account team stop relying on old client evidence?',cluster:'Hiring Controls',hero:'/research-heroes/2026-09-24-evidence-lineage.png',service:'account-health-monitoring',related:['outsourced-account-record-freshness-decay','client-stakeholder-authority-drift-study'],
    excerpt:'A decision-specific study of evidence expiry, event-triggered review, conflicting sources, and the point at which an account record must be confirmed rather than reused.',headline:'Evidence does not become unsafe at one universal age; expiry depends on the decision, consequence, source, and intervening events',
    sections:[
      {heading:'Freshness belongs to a decision, not a database field',paragraphs:[
        'Account teams often treat a recent timestamp as proof that a fact remains usable. That shortcut fails when the underlying subject can change without a scheduled edit. A stakeholder title, approval right, delivery acceptance, renewal date, contact preference, system-access need, and commercial instruction each have different change mechanisms. This study asks a narrower question: at a declared decision time, was the available evidence still fit for that particular use? It does not label a whole account “stale,” infer client sentiment from silence, or assume that a newer entry is more authoritative than an approved older record.',
        'The unit is one evidence-dependent action: sending a status, routing an approval, closing a commitment, preparing a renewal packet, or requesting access. Freeze the action, cutoff, consequence tier, source hierarchy, and facts visible to the operator. Record the evidence creation time, last confirmation, responsible owner, expected review event, and any intervening signal. Later corrections belong in a later view. Preserving the historical snapshot prevents hindsight from making a weak decision look well supported and lets reviewers distinguish a stale source from an operator who correctly followed the approved record.'
      ]},
      {heading:'Build expiry rules from change mechanisms',paragraphs:[
        'For each evidence class, identify how it can cease to be reliable. Authority can change through delegation, role movement, revocation, or conflicting instruction. Scope can change through an approved amendment. A milestone can change through rejection, reopening, or correction. Contact information can change through explicit notice or delivery failure. Define a maximum review interval only where owners approve one, then add event triggers that require earlier review. An interval is a backstop, not a warranty that no relevant event occurred. Missing triggers or inaccessible systems remain visible limitations rather than grounds to extend use.',
        'Use consequence to set the confirmation threshold. Reusing an address for a routine meeting reminder is different from relying on an old approval to change scope, export data, interpret a contract, or make a new promise. State which reversible preparation may continue while confirmation is pending. A specialist can assemble the record, draft neutral questions, and flag a conflict; the designated owner decides whether consequential evidence remains sufficient. This separation lets the team stay responsive without converting operational access into authority that the source never granted.'
      ]},
      {heading:'Sample ordinary cases and disruptive events',paragraphs:[
        'Construct a bounded sample from actions eligible during the observation period, not merely from records that were later corrected. Include ordinary reuse, scheduled reviews, role changes, returned messages, reopened work, conflicting instructions, and actions paused for confirmation. Define duplicates, cancellations, and inaccessible client-held records before review. Report the eligible, inspected, complete, expired, conflicted, and unresolved counts with separate denominators. A low correction count is not proof of quality if the workflow rarely detects change; a high confirmation count is not proof of waste if the sample intentionally contains consequential transitions.',
        'Test counterexamples. An old contract date may remain authoritative because no amendment exists, while a contact verified yesterday may already be unusable after an explicit role change. A newer chat message may lack authority that an older approved matrix possesses. Independent reviewers should classify a subset using the same evidence hierarchy and consequence rules. Preserve disagreement about expiry and its cause. Forced consensus can conceal vague definitions, incomplete visibility, or an owner decision that the method cannot legitimately replace.'
      ]},
      {heading:'Trace the operational cost of getting freshness wrong',paragraphs:[
        'A false-fresh decision can route work to the wrong approver, repeat a superseded promise, expose information to an outdated recipient, or close work against an obsolete acceptance rule. A false-stale decision can interrupt routine service, create unnecessary confirmation traffic, or delay reversible preparation. Trace only consequences supported by the record. Do not claim that a stale field caused churn, revenue loss, or a privacy breach merely because those outcomes are conceivable. Record the action, dependency, actual downstream state, and uncertainty so owners can judge proportional correction.',
        'Separate detection latency from correction latency. The first runs from the change event, when observable, to the point the team recognized it. The second runs from recognition to approved propagation across affected destinations. The clocks can differ by system and may overlap. State timezones, business calendars, unavailable event times, and pause rules. This makes a review useful for process design without turning elapsed time into unsupported individual blame. It also exposes where a source owner needs a better notification interface rather than another reminder to operators.'
      ]},
      {heading:'Design the confirmation and propagation path',paragraphs:[
        'A confirmation request should name the exact fact, current source, intended use, consequence of waiting, and answer required. It should avoid internal scoring language and unnecessary sensitive detail. Once confirmed, update operational destinations according to purpose: current records may change, derived reminders may need recomputation, active drafts may need correction, and historical decisions should retain the evidence that governed them. Blind synchronization can erase lineage. Record the approving source, effective time, affected items, and destinations outside the team’s visibility.',
        'Use dispositions that preserve uncertainty: confirmed for this use, expired pending owner review, conflicting sources, superseded, outside visibility, or restricted to reversible preparation. A color alone is inadequate because it does not state the decision or authority. Define closure as propagation to the named active destinations plus a residual list for anything inaccessible. The objective is not to certify every stored copy. It is to make current consequential use defensible, keep history truthful, and show owners where an unresolved copy could still influence work.'
      ]},
      {heading:'Bounded conclusion and replication',paragraphs:[
        'The evidence supports a modest conclusion: a record remains usable only when its source, purpose, confirmation rule, intervening events, and consequence threshold still align. Outsourced account specialists may maintain assigned evidence registers, run approved freshness checks, prepare confirmation requests, and coordinate updates. They should not extend authority, reinterpret a contract, approve access, decide legal or security sufficiency, or silently choose between conflicting client sources. Those decisions remain with the accountable owner named in the operating model.',
        'Replication requires the same action classes, cutoff, evidence hierarchy, consequence tiers, interval rules, triggers, missingness codes, and independent review procedure. Disclose private channels and client systems the reviewer could not inspect. Report late corrections as late corrections. The reader outcome is a practical expiry design that tells an account team which facts may be reused, which need confirmation, what work may continue safely, and how a confirmed change reaches active decisions without rewriting the historical record.'
      ]}
    ],rows:[['Decision','Named action and consequence tier','Freshness is use-specific'],['Trigger','Interval plus intervening events','A recent timestamp is not enough'],['Confirmation','Exact fact, source, owner, intended use','Preparation is not approval'],['Propagation','Active destinations and residual limits','Preserve historical lineage']]
  },
  {
    slug:'client-meeting-action-survivorship-study',title:'Which client meeting commitments disappear before the action register?',cluster:'Workflow Design',hero:'/research-heroes/2026-09-22-meeting-decision-traceability.png',service:'meeting-follow-up',related:['meeting-action-item-closure-study','meeting-decision-traceability-analysis'],
    excerpt:'A survivorship-bias study comparing meeting evidence with the smaller set of actions that reach trackers, updates, and closure reports.',headline:'A clean action register can conceal commitments that were omitted, merged, softened, or lost before registration',
    sections:[
      {heading:'The tracker shows survivors, not the full meeting population',paragraphs:[
        'Meeting follow-up is often evaluated from the action register alone. That design observes only statements that someone recognized, translated, and entered. It excludes requests left in notes, decisions expressed indirectly, conditional commitments, disputed wording, and items removed during summarization. This study treats registration as an outcome to examine rather than the starting population. The question is not whether every sentence should become a task. It is whether consequential commitments and owner decisions can be traced from approved meeting evidence to an explicit disposition.',
        'Define the unit as one candidate commitment or decision in a bounded set of client meetings. A candidate needs an actor, requested or promised change, condition, or decision consequence; greetings and general discussion do not qualify. Freeze meeting eligibility, approved evidence sources, cutoff, transcription limits, and the person authorized to resolve ambiguous wording. A support specialist may identify candidates, but client intent and contractual meaning cannot be invented from conversational fragments. Ambiguous items remain candidates pending confirmation.'
      ]},
      {heading:'Reconstruct candidates before looking at the register',paragraphs:[
        'Use approved recordings, transcripts, minutes, chat, shared documents, and presenter notes in the declared source order. Two reviewers independently mark candidates before either sees the final tracker. For each candidate, preserve exact wording, timestamp or page, speaker if permitted, condition, proposed owner, due cue, and confidence in the extraction. Data minimization still applies: the research record can cite a controlled source location without copying unrelated discussion or personal information into a broader system.',
        'Reconcile reviewer differences with a reason code: indirect language, overlapping speakers, unclear pronoun, conditional request, implied date, duplicate of an existing commitment, or outside meeting scope. Agreement is not automatically truth; both reviewers can miss the same quietly stated decision. Sample sections with no identified candidates as a negative control and ask the accountable meeting owner to review consequential ambiguity. Preserve unresolved language instead of converting it into a polished task that neither party actually accepted.'
      ]},
      {heading:'Follow each candidate through translation',paragraphs:[
        'Map every candidate to registered as stated, registered with a material change, merged, routed for confirmation, deliberately excluded, or absent without disposition. A material change includes altered scope, owner, condition, deadline, acceptance test, or authority. Merging may be sensible, but the parent item must retain the distinct obligations and evidence needed for closure. Count each disposition separately. A high registration percentage can still be unsafe if conditions were stripped or several promises were collapsed into one vague line.',
        'Then trace downstream appearance in the approved meeting recap, operational queue, client update, escalation record, and closure evidence. These destinations serve different purposes; exact wording need not be duplicated everywhere. The test is semantic continuity: can a reviewer determine what was agreed, who owns preparation, who owns the decision, what condition applies, and what proves completion? A message saying “handled” does not establish acceptance. A sent recap does not prove the recipient agreed with a rewritten commitment.'
      ]},
      {heading:'Measure omissions without manufacturing precision',paragraphs:[
        'Report meetings sampled, source completeness, candidates identified, candidates registered, material translations, explicit exclusions, unresolved candidates, and candidates missing from downstream records. Give denominators and confidence limits where suitable, but do not call the result a universal capture rate. The sample may overrepresent recorded meetings, formal reviews, one language, or one account type. Private side conversations and inaccessible client notes create a visibility boundary that belongs beside the finding.',
        'Stratify by language form and consequence rather than individual employee. Direct assignments, questions, conditional offers, recap statements, and corrections may survive differently. Commercial, access, data, scope, and client-communication consequences may warrant different confirmation thresholds. Do not infer negligence from an omission: the speaker may have withdrawn the request, another system may hold it, or the statement may never have been an agreement. Investigate the source trail and decision owner before attributing cause.'
      ]},
      {heading:'Test a safer meeting-to-register control',paragraphs:[
        'A practical intervention is a short candidate-disposition pass before publishing minutes. The preparer lists consequential candidates with source anchors, while the meeting owner confirms the wording, owner, conditions, and whether client confirmation is required. Only then does the operational register receive accepted actions. Compare pre- and post-intervention meetings using the same eligibility rules. Examine correction traffic and time to approved recap alongside registration, because indiscriminate capture can create noise rather than reliability.',
        'Client-facing follow-up should distinguish confirmed decisions, proposed actions, questions awaiting confirmation, and information-only notes. That vocabulary prevents a draft from becoming an accidental promise. If the client corrects the recap, preserve the original, correction, effective decision, and propagated changes. Never use the study to expose internal scoring or suggest that silence constitutes acceptance unless a governing agreement and accountable owner explicitly establish that rule.'
      ]},
      {heading:'Conclusion, boundaries, and reader outcome',paragraphs:[
        'The bounded conclusion is that action-register quality cannot be judged from registered items alone. A defensible review begins with meeting evidence, records candidate dispositions, and tests whether meaning survives into closure. An outsourced specialist may prepare evidence anchors, draft minutes, maintain an assigned register, request confirmation, and flag missing dispositions. The role should not decide ambiguous client intent, accept new scope, assign commercial authority, or close a consequential commitment without the approved proof.',
        'Replication requires identical meeting eligibility, candidate definition, source order, cutoff, independent extraction, translation codes, consequence tiers, and downstream destinations. Disclose meetings without approved records and any automated transcript limitations. The reader leaves with a method to find the commitments a neat tracker cannot show, correct the meeting-to-work interface, and produce client updates that remain faithful to what was actually decided rather than what was easiest to summarize.'
      ]}
    ],rows:[['Population','Approved meeting evidence','Do not begin with tracker survivors'],['Candidate','Source anchor and consequential statement','Ambiguity remains visible'],['Disposition','Registered, changed, merged, excluded, unresolved','Every candidate gets a state'],['Closure','Proof tied to preserved meaning','Sent recap is not acceptance']]
  },
  {
    slug:'escalation-severity-reviewer-agreement-study',title:'Would two account managers escalate the same client issue the same way?',cluster:'Scope Benchmarks',hero:'/research-heroes/2026-09-24-owner-continuity.png',service:'client-escalation-management',related:['client-escalation-threshold-study','escalation-response-evidence-lag-study'],
    excerpt:'An inter-reviewer agreement study for escalation severity, evidence thresholds, consequence tiers, and safe routing under uncertainty.',headline:'A severity rubric is operational only when independent reviewers can apply it consistently and explain material disagreement',
    sections:[
      {heading:'A rubric can look precise while reviewers use different rules',paragraphs:[
        'Escalation labels compress evidence, consequence, urgency, and authority into a small set of categories. Two reviewers may select the same label for incompatible reasons or different labels from the same facts. This study evaluates application consistency, not whether people are naturally “good at judgment.” The unit is one frozen issue packet containing the information available at the historical decision time. The study asks which rubric terms produce agreement, where uncertainty changes routing, and which decisions require an accountable owner regardless of score.',
        'Predeclare the eligible issue classes, observation window, consequence dimensions, escalation destinations, and exclusions. Include delivery exceptions, stakeholder conflicts, access concerns, data questions, disputed commitments, and commercial requests only where the rubric purports to cover them. Remove outcome information that was not available at decision time. Preserve later facts separately to test whether the original action was reasonable with contemporaneous evidence rather than rewarding hindsight.'
      ]},
      {heading:'Create packets that test the difficult boundaries',paragraphs:[
        'Sample routine cases, clear high-consequence cases, incomplete records, contradictory sources, repeated low-level events, and near-boundary examples. Oversampling difficult cases is useful for calibration but makes the resulting agreement rate unsuitable as a portfolio prevalence estimate. Each packet should include source dates, exact observations, known affected scope, time sensitivity, prior related events available then, existing owner, and missing facts. Do not add emotional summaries or the historical label, which can anchor reviewers.',
        'Protect client and personal information by substituting stable case identifiers and retaining only fields needed for judgment. Reviewers should have the same authorized visibility. If one role would normally see a different system, either construct role-specific analyses or classify access as part of the experimental condition. An agreement result is uninterpretable when reviewers unknowingly receive different evidence. Qualified owners determine privacy, security, employment, and legal handling; the research method does not replace those decisions.'
      ]},
      {heading:'Score dimensions before the overall route',paragraphs:[
        'Ask reviewers to code evidence confidence, potential consequence, observed scope, time sensitivity, reversibility, client-communication need, and required decision owner before choosing severity. This reveals whether disagreement comes from facts, definitions, or aggregation. Require a short source-linked rationale and the next safe action. A numeric category alone can hide that one reviewer saw a data issue while another saw a schedule issue. The rationale also exposes when a reviewer imported an unsupported assumption.',
        'Use an approved agreement measure suited to category type and report raw cross-tabs as well. Weighted agreement may recognize that adjacent categories differ less than opposite ones, but weights are a policy choice and must be declared before results. Small samples and rare severe events can make a single coefficient unstable. Present counts, uncertainty, and the consequence of disagreement. Never convert a calibration statistic into a claim that the escalation process prevented client harm or proves compliance.'
      ]},
      {heading:'Investigate disagreement as design evidence',paragraphs:[
        'For every material disagreement, compare cited facts, missingness treatment, rubric clauses, assumed owner, and selected interim action. Common causes include undefined words such as “material,” confusion between possible and observed impact, disagreement about repeated events, and mixing response urgency with final severity. Route substantive domain judgments to the appropriate owner. The facilitator should not force consensus merely to improve the metric; unresolved disagreement is often the clearest evidence that the rubric needs a decision.',
        'Also inspect false agreement. Reviewers may converge because the packet contains a prominent but irrelevant field, because training examples overfit one scenario, or because the rubric always routes uncertainty upward. Ask reviewers to identify the decisive fact before group discussion and include counterexamples where the obvious cue should not control. A calibration process that produces identical labels without defensible reasoning can create consistency at the cost of useful discrimination.'
      ]},
      {heading:'Revise the operating interface, then retest',paragraphs:[
        'Turn findings into specific changes: define a term, add a source requirement, separate urgency from consequence, create an explicit unknown state, clarify the destination, or state which reversible action is permitted while waiting. Version the rubric with an effective date and preserve historical decisions under the prior version. Retest a held-out set rather than only the cases used during discussion. Improvement on memorized examples does not show that the interface generalizes.',
        'Operationally, escalation should preserve the issue, evidence, current consequence, uncertainty, immediate containment or reversible step, requested decision, owner, communication state, and next checkpoint. A specialist may capture and route those fields and send approved messages. They should not make legal, security, commercial, access, or contractual determinations merely because a rubric produces a category. High-severity routing transfers the decision; it does not confer authority on the preparer.'
      ]},
      {heading:'Limitations and practical conclusion',paragraphs:[
        'Historical packets omit tone, tacit context, and private client information; simulated review differs from live time pressure; reviewers may learn across rounds; and rare consequences limit precision. Team composition, client contracts, service scope, and escalation channels also constrain transfer. State these limits beside results. Compare versions only when the sampling and reviewer design are sufficiently aligned, and do not rank employees from a calibration exercise built to diagnose the rubric.',
        'The practical conclusion is that an escalation model becomes safer when reviewers can identify the same consequential facts, expose uncertainty, and route decisions consistently—not when they merely choose matching colors. Replication requires the same packets, masking, rubric version, order controls, dimensions, agreement method, and adjudication rules. The reader receives a calibration plan that strengthens account-management continuity while preserving the boundary between evidence preparation and accountable judgment.'
      ]}
    ],rows:[['Packet','Contemporaneous facts and explicit missingness','No hindsight outcomes'],['Dimensions','Confidence, consequence, urgency, reversibility','Score before overall route'],['Agreement','Cross-tab, declared statistic, rationale','Matching labels can still be wrong'],['Revision','Versioned rule and held-out retest','Calibration does not confer authority']]
  },
  {
    slug:'account-portfolio-interruption-load-study',title:'How much account-management capacity is lost to interruption and restart?',cluster:'Workflow Design',hero:'/research-heroes/2026-09-24-sampling-bias.png',service:'account-health-monitoring',related:['outsourced-account-manager-queue-aging-causality-study','account-priority-override-outcome-study'],
    excerpt:'A portfolio-level method for separating active work, waiting, interruption, restart, and hidden coordination demand without turning activity logs into surveillance.',headline:'Open-item counts omit the restart and coordination work created when urgent account requests repeatedly displace planned reviews',
    sections:[
      {heading:'Capacity is a flow question, not an inbox count',paragraphs:[
        'A portfolio can show a manageable number of open items while account managers repeatedly abandon and reconstruct work. An interruption may be justified, yet it still creates coordination, context recovery, evidence refresh, and rescheduling. This study examines the flow impact without assuming that busyness proves value or that every switch is waste. The unit is one planned work episode and any interruption that changes its timing, evidence state, or owner. The aim is to make service-design choices visible, not to measure keystrokes or police individual attention.',
        'Freeze the observation period, eligible accounts, work classes, service calendars, planned cadence, and approved data sources. Define active work, authorized waiting, interruption, restart, handoff, cancellation, and closure before extraction. Exclude private message content when timestamps and reason codes suffice. Inform affected people of the measurement purpose and access boundary. Operational research should follow approved privacy and employment practices; a useful capacity model does not require uncontrolled monitoring.'
      ]},
      {heading:'Reconstruct episodes from decision-relevant events',paragraphs:[
        'Build each episode from an approved source event, intended outcome, starting evidence state, work owner, decision owner where needed, and closure rule. When work stops, code the observed reason: higher-consequence client need, missing input, owner decision, access problem, scheduled boundary, technical failure, or unclassified. On restart, record whether evidence was still current, the plan changed, another person reconstructed context, or the item was re-scoped. Time alone cannot distinguish these states.',
        'Avoid inferring cognition from application events. A window change does not prove a meaningful context switch, and a long inactive interval does not prove disengagement. Prefer explicit workflow transitions and small diary samples approved for the study. Triangulate queue records, scheduled reviews, escalation logs, and closure evidence. Where clocks conflict, preserve both sources and their authority rather than manufacturing a precise duration. The model should become less confident as observability decreases.'
      ]},
      {heading:'Separate demand, waiting, and recovery',paragraphs:[
        'Report newly eligible work, carried work, completed work, canceled work, and work still open at cutoff. Partition elapsed periods into active preparation, awaiting client evidence, awaiting internal decision, blocked access, scheduled delay, displaced by another approved priority, and restart preparation. Intervals can overlap, so document whether the method uses exclusive states or parallel clocks. Do not sum incompatible durations. A queue-aging figure that includes client waiting and active work under one label cannot support a sound staffing conclusion.',
        'Measure restart through observable reconstruction: sources reopened, evidence revalidated, draft changes required after intervening events, duplicate briefing, or ownership transfer. These are proxies, not direct measures of mental load. Present median and distribution where sample size supports them; averages can be dominated by a few long holds. Stratify only across comparable work classes and consequence levels. Never claim a particular headcount requirement from a convenience sample without demand forecasts, service targets, skills, calendars, and uncertainty.'
      ]},
      {heading:'Study priority overrides as governed decisions',paragraphs:[
        'An override should identify the incoming need, consequence, source, approving rule or owner, displaced work, client-communication effect, and next reassessment. Sample overrides that worked well alongside those followed by missed reviews, duplicate effort, or silent rollover. The purpose is not to eliminate urgent response. It is to determine whether displaced obligations remained visible and whether the portfolio had an explicit way to restore them after the interruption.',
        'Look for cascading displacement: an urgent request moves a review, the moved review collides with a renewal deadline, and the collision creates a second escalation. Map the sequence without declaring the first request the sole cause. Preexisting backlog, incomplete intake, unavailable approvers, or an unrealistic cadence may also be necessary conditions. Preserve competing explanations and identify the exact interface an owner can change. Causal business claims require a stronger design than an operational sequence review.'
      ]},
      {heading:'Test portfolio-level protections',paragraphs:[
        'Candidate protections include consequence-based intake, protected review windows, explicit work-in-progress limits, a visible displaced-work list, backup evidence summaries, and a return checkpoint after urgent work. For each, state the targeted failure mode, authority needed, potential downside, and proof of improvement. Protected time can reduce responsiveness if applied rigidly; broad cross-training can expand data access unnecessarily; summary records can become stale. Controls need proportionate design rather than universal adoption.',
        'Compare a bounded before-and-after period only when seasonality, account mix, staffing, and policy changes are disclosed. Useful outcomes include fewer orphaned episodes, faster restoration of displaced work, lower duplicate reconstruction, and more complete client updates. These are process observations, not proof of retention or productivity gains. If the intervention changes what gets recorded, apparent improvement may reflect visibility rather than performance. Keep that measurement change in the result.'
      ]},
      {heading:'Decision boundaries and reader outcome',paragraphs:[
        'An outsourced account specialist may maintain the approved queue, record dependencies, prepare prioritization options, flag displaced commitments, and coordinate authorized follow-up. They should not unilaterally waive service obligations, redefine client priority, approve overtime, expand access, or promise a date beyond delegated scope. The capacity brief ends with evidence, scenarios, constraints, and named owner decisions rather than a hidden optimization score that decides for the business.',
        'Replication requires the same episode definitions, calendars, observation sources, visibility limits, state rules, overlap treatment, work classes, and cutoff. Disclose missing private channels and any workflow changes during measurement. The reader outcome is a defensible portfolio model that shows where interruption produces recoverable coordination work, where waiting belongs to another dependency, and which operating change an owner can test—without turning account management into invasive activity surveillance.'
      ]}
    ],rows:[['Episode','Outcome, source, owner, closure rule','Do not infer from app activity'],['Interruption','Reason, authority, displaced work','Urgency may be legitimate'],['Restart','Observable reconstruction and revalidation','Proxy, not mental-load proof'],['Portfolio decision','Scenario, constraint, owner, test','No automatic staffing claim']]
  },
  {
    slug:'client-offboarding-residual-obligation-study',title:'What remains unfinished after a client account is marked offboarded?',cluster:'Hiring Controls',hero:'/research-heroes/2026-09-24-evidence-lineage.png',service:'client-onboarding-coordination',related:['client-relationship-owner-continuity-study','account-handoff-knowledge-decay'],
    excerpt:'A residual-obligation study of open promises, retained evidence, access removal, scheduled communications, and decision ownership after account offboarding.',headline:'An offboarding status can close the primary workflow while commitments, access, records, and scheduled messages remain active elsewhere',
    sections:[
      {heading:'Offboarding is a transition, not one completed task',paragraphs:[
        'A client account can be labeled closed while operational effects persist: an unanswered request, a pending correction, a scheduled report, retained access, a shared file, a meeting invite, a vendor dependency, or evidence required for later review. This study examines residual obligations after the approved relationship transition. It does not interpret termination rights, retention law, financial settlement, or contractual survival clauses. Qualified owners supply those decisions; the account team maps their operational consequences.',
        'Define one offboarding event by the governing source, effective time, scope, accountable transition owner, and declared completion rule. Freeze the systems and work classes visible to the review. Distinguish account closure, service stop, access change, communication stop, data disposition, and residual commitment closure. These events may occur at different times. A single “offboarded” timestamp should not be allowed to erase that sequence or imply that every downstream obligation ended simultaneously.'
      ]},
      {heading:'Create the residual population before changing records',paragraphs:[
        'At the transition cutoff, inventory open client requests, accepted commitments, disputed items, scheduled communications, recurring tasks, approvals in flight, shared credentials or named access, integrations, exported working files, meeting series, billing questions visible to the team, and evidence subject to an approved retention rule. Record source, purpose, owner, sensitivity, next event, and authority for disposition. Use references rather than duplicating sensitive content. The inventory is a decision queue, not permission to retain everything.',
        'Include items that appear complete but lack acceptance evidence and tasks canceled solely because the account status changed. Sample historical records only where needed to reconstruct the obligation. A missed residual can originate outside the main CRM, so trace declared interfaces such as calendars, ticket queues, project boards, storage, and approved messaging channels. Anything inaccessible becomes a named visibility limit assigned to an authorized owner; it is not silently counted as clear.'
      ]},
      {heading:'Classify disposition by purpose and authority',paragraphs:[
        'Each residual receives one approved disposition: complete before cutoff, transfer to a named owner, communicate and close, preserve under a retention rule, restrict, revoke, delete through an authorized process, or hold pending decision. The same object can require multiple actions: access may be revoked while a decision record is retained, or a recurring task may stop while its final output is delivered. Purpose prevents the team from treating deletion, archival, revocation, and closure as interchangeable.',
        'Record the decision source and effective time. An outsourced specialist may prepare the inventory, execute specifically authorized administrative steps, collect completion evidence, and flag exceptions. They should not decide legal retention, destroy records outside approved policy, interpret contract obligations, resolve money disputes, or revoke access they do not administer. Least privilege applies during the transition as well: broad temporary access for cleanup can create a new problem while closing the old one.'
      ]},
      {heading:'Test for silent continuation and premature closure',paragraphs:[
        'Use sentinel checks after the effective time. Did scheduled email or reporting run? Did a recurring task reopen? Could the prior team still access an assigned system? Did an integration continue moving data? Did a client-facing queue accept a new item without an owner? Did a retained draft remain discoverable as current guidance? These checks target operational use, not an impossible claim that every byte has been located. Document the search boundary and escalate material uncertainty.',
        'Also test premature removal. Revoking access before evidence transfer can make an open correction impossible; canceling a meeting without communicating a new route can strand a client question; deleting a working record without preserving the approved decision can destroy accountability. Offboarding quality is not maximized by speed alone. Sequence actions according to the owner-approved transition plan and keep temporary exceptions time-bounded, attributable, and reviewed.'
      ]},
      {heading:'Measure closure without overstating assurance',paragraphs:[
        'Report offboarding events eligible, inventories completed, residuals found, dispositions approved, actions verified, exceptions open, and destinations outside visibility. Separate counts by residual type and consequence. A small residual count may mean a simple account or incomplete discovery. A large count may reflect strong detection rather than poor service. Time measures should distinguish awaiting client direction, internal approval, technical execution, and evidence review. State business calendars and the configured cutoff timezone.',
        'Verification should match the action: access removal needs authoritative status from the administering system; a stopped schedule needs a disabled rule and a bounded no-send check; a transferred obligation needs recipient acceptance; a retained record needs purpose, location, access, and review date; a client communication needs approved copy and delivery evidence. None of these alone proves satisfaction, compliance, security, or commercial closure. Conclusions remain limited to the inspected controls and evidence.'
      ]},
      {heading:'Close with a residual register, not a blanket attestation',paragraphs:[
        'The final record should state the transition source, effective time, systems inspected, residuals by disposition, verification evidence, unresolved exceptions, inaccessible destinations, owners, and next review dates. Historical decisions stay linked to the authority valid at the time. Current directories and queues should no longer present superseded access or contacts as active. If a later residual appears, reopen the transition record rather than rewriting the original inventory as though it was always known.',
        'Replication requires the same offboarding definition, system boundary, residual taxonomy, evidence hierarchy, cutoff, disposition authority, sentinel checks, and missingness codes. The reader receives a practical method for separating “primary service stopped” from “all obligations verified,” coordinating the remaining work, and preserving truthful evidence. This improves continuity while keeping legal, security, financial, privacy, and contractual decisions with the accountable specialists and owners.'
      ]}
    ],rows:[['Transition','Governing source, scope, effective time','Status is not the whole sequence'],['Residual','Purpose, owner, sensitivity, next event','Inventory before mutation'],['Disposition','Approved action and authority','Retention, deletion, revocation differ'],['Verification','Evidence matched to action','Report inaccessible destinations']]
  }
];

const workedAnalysis:Record<string,{heading:string;paragraphs:string[]}>= {
  'client-evidence-expiry-trigger-study':{heading:'Worked analysis: an approval record after a stakeholder change',paragraphs:[
    'Consider an account team preparing to send a revised delivery sequence. The CRM still names the original approver, and the approval matrix was confirmed thirty days earlier. A current meeting note says a new operations lead will “take over,” but it does not state whether decision rights changed. The old matrix is authoritative yet exposed to an intervening event; the new note is recent yet incomplete. The correct disposition is not to select whichever record is newer. The team can prepare the sequence, anchor both sources, identify the precise approval needed, and pause the consequential send for owner confirmation.',
    'If the authorized owner confirms that the new lead assumes approval rights at a stated effective time, propagation differs by destination. The active approval matrix and open workflow route change. Draft messages are rechecked. Historical approvals remain attributed to the authority valid when they occurred. An automated reminder for the former approver is disabled, while an archived meeting record is preserved with a link to the later decision rather than rewritten. Each action has separate evidence because “CRM updated” does not prove the operational route, reminder, and drafts all changed.',
    'Now test the negative case. Suppose the meeting note described responsibility for coordination, not authorization. The owner confirms that approval rights remain unchanged. The freshness trigger still worked: it exposed ambiguity before a consequential action. The result should not be scored as an unnecessary false alarm merely because the old value survived review. Report the confirmed decision, the ambiguous phrase that triggered it, and whether the source template should distinguish coordination from approval. That learning improves the interface without encouraging operators to ignore future role-change signals.'
  ]},
  'client-meeting-action-survivorship-study':{heading:'Worked analysis: a conditional promise that vanishes in summary',paragraphs:[
    'Imagine a review where a client says, “If the corrected usage file arrives by Thursday, we can validate the renewal summary on Friday.” The minutes record only “renewal summary review Friday.” The tracker therefore contains a date but loses the prerequisite, the client action, and the conditional nature of the review. When Thursday passes without the file, the task appears late even though its required input never arrived. A tracker-only audit would blame closure; the candidate-to-disposition method reveals a material translation at registration.',
    'The corrected record separates two linked items: delivery of the usage file by its source owner and conditional client validation after receipt. It names the evidence for each transition and the next communication if the prerequisite misses its window. The account specialist may prepare the linked entries and a neutral recap asking the client to confirm the sequence. The specialist may not convert the client’s conditional willingness to review into unconditional acceptance or promise a renewal position. That boundary is part of the action record, not a footnote.',
    'A second reviewer might argue that the statement was merely conversational. That disagreement is valuable. Both reviewers return to the source anchor, meeting purpose, prior agenda, and any explicit recap. If intent remains unclear, the disposition is “confirmation required,” not “missing action” or “accepted promise.” Later client confirmation becomes a dated source. The study thereby measures whether uncertainty was handled visibly, rather than rewarding a high capture rate achieved by turning every tentative sentence into work.'
  ]},
  'escalation-severity-reviewer-agreement-study':{heading:'Worked analysis: urgency and consequence point in different directions',paragraphs:[
    'Take a client report that a weekly dashboard shows an incorrect label for one region. Reviewer A selects high severity because the executive review starts in two hours. Reviewer B selects low severity because the underlying data and decisions are unchanged. Both cite real facts, but they combine urgency and consequence differently. A useful rubric records them separately: near-term communication urgency may be high while observed business or data consequence remains bounded. The route can require prompt owner review without asserting broad impact.',
    'The packet should include the approved dashboard source, affected field, known distribution, decision use, correction authority, meeting time, and facts still unknown. Reviewers state a reversible step, such as pausing distribution or adding an approved limitation, alongside the decision requested. If one reviewer assumes all regional data are wrong despite evidence only of a label defect, that unsupported expansion appears in the rationale. If the second reviewer ignores reputational consequence because the numbers are correct, that omission also becomes discussable.',
    'Adjudication may produce a two-axis rule: communication clock and consequence tier. The historical decisions remain under the old rubric; the new version applies after its effective date. A held-out case then tests whether reviewers route a time-sensitive but reversible presentation error differently from a slower-moving access exposure. Better separation is shown by source-linked reasoning and appropriate destinations, not simply a higher agreement coefficient. This worked example also demonstrates why one overall severity score should not silently authorize client wording.'
  ]},
  'account-portfolio-interruption-load-study':{heading:'Worked analysis: an urgent request displaces a planned account review',paragraphs:[
    'Suppose an account manager begins a scheduled renewal-evidence review, then receives an approved escalation involving a same-day client update. The review is paused after sources are assembled but before contradictions are reconciled. The escalation takes ninety minutes, yet the portfolio cost is not automatically ninety minutes. On return the next day, a source has changed, the earlier notes require validation, and a decision owner is no longer available. The observable restart consists of revalidation, changed notes, and rescheduled review—not a claim about the manager’s private mental state.',
    'The sequence record identifies who authorized the priority change, which renewal work was displaced, the state preserved at pause, the client communication affected, and the restoration checkpoint. If the workflow merely changes the original due date, the displaced obligation disappears from capacity evidence. A visible displaced-work list retains it without pretending the original plan remained feasible. The portfolio owner can then choose whether to restore the review, transfer it with controlled access, or revise cadence through the approved process.',
    'Compare this with an interruption that produces no meaningful restart cost: a brief factual question is answered from the same source while the review remains open and current. Counting both as equal “context switches” would distort the model. The method therefore classifies changes to timing, evidence, ownership, and closure path. Across a bounded sample, owners can test whether protected review windows or a backup evidence summary reduce orphaned work. The result informs a trial; it does not calculate a universal productivity loss or staffing ratio.'
  ]},
  'client-offboarding-residual-obligation-study':{heading:'Worked analysis: service ends while a correction remains open',paragraphs:[
    'Assume primary service ends Friday, but the account team discovered on Thursday that the prior monthly report used an outdated client contact list. The report itself was delivered, and no new routine reporting should occur after Friday. The correction request is therefore a residual obligation, not permission to restart service generally. The transition owner must decide whether to issue a correction, who approves the wording, which recipients are appropriate, and what evidence closes the item. The offboarding label alone cannot answer those questions.',
    'The residual register also shows a scheduled Monday report, a shared-folder permission, and a recurring meeting. Each receives a different disposition. The schedule is disabled and verified; access is removed by its administrator after required evidence transfer; the meeting is canceled with an approved route for the open correction. Historical delivery evidence is retained under the applicable policy, while temporary working exports follow the authorized disposal process. One blanket “closed” checkbox would conceal these unequal actions and authorities.',
    'After the effective time, sentinel checks find that no Monday report was sent, the folder status reflects the approved removal, the old meeting no longer invites participants, and the correction remains assigned with a review date. If the account team cannot inspect a client-owned integration, that destination appears as an unresolved visibility limit with a named owner. The final statement can confirm the controls actually checked while refusing to attest that every external copy, legal obligation, or commercial issue is closed.'
  ]}
};

export const research20261005:ResearchPost[]=drafts.map(d=>({
  slug:d.slug,title:d.title,cluster:d.cluster,excerpt:d.excerpt,hero:d.hero,published:'2026-10-05',datePublished:'2026-10-05',updated:'2026-10-05',headlineStat:d.headline,
  statSource:'Topic-specific synthesis of NIST, GAO, FTC, Philippine NPC, and ISO principles',
  takeaways:['Define the decision, population, source hierarchy, and cutoff before reviewing records.','Preserve missing, conflicting, corrected, and inaccessible evidence in the result.','Keep operational preparation separate from consequential owner judgment.','Report bounded findings, limitations, and the next authorized review trigger.'],
  sections:[...d.sections,workedAnalysis[d.slug]],table:{headers:['Control point','Minimum evidence','Boundary'],rows:d.rows},sources,
  researchMethodology:`Bounded documentary and operational study for ${d.title}; predeclared population, explicit missingness, exception sampling, independent review where applicable, and non-causal conclusions.`,externalSources:sources.map(s=>s.url),
  faqs:[{q:'Can this study prove a client or business outcome?',a:'No. It evaluates a bounded operating record and cannot prove causality, satisfaction, retention, revenue, legal compliance, or a guaranteed result.'},{q:'What may an outsourced account specialist do?',a:'They may gather permitted evidence, maintain assigned records, prepare neutral summaries, flag exceptions, and coordinate approved follow-up. Consequential decisions remain with accountable owners.'},{q:'How can another team reproduce the review?',a:'Use the same unit, population, definitions, cutoff, source hierarchy, visibility limits, missingness treatment, and review procedure, then disclose every material change.'}],
  related:d.related,internalLinks:[{label:`Review ${d.service.replaceAll('-',' ')} support`,href:`/services/${d.service}`},{label:'Explore the research library',href:'/research'}]
}));
