import { makeSeptemberResearchStudy, type SeptemberResearchTopic } from './research-2026-09-07';

const topics: SeptemberResearchTopic[] = [
  ['account-update-claim-traceability-study', 'Can reviewers trace client update claims to current evidence?', 'Workflow Design', 'whether each factual claim in a client account update can be reproduced from an authoritative source available at the stated cutoff', 'freeze approved and returned update drafts, split each into testable claims, ask two reviewers to locate the cited source and observation date, and code unsupported, stale, conflicting, or interpretation-only claims', 'Traceability shows that a reviewer can reproduce a claim from the frozen packet. It does not establish that the source is complete, that the client agrees with the interpretation, or that the update caused an account outcome.', '2026-08-31-account-queue-invisible-work-analysis.png'],
  ['renewal-decision-window-reliability', 'Do renewal decision windows survive account handoffs?', 'Hiring Controls', 'whether controlling renewal dates, required lead times, dependencies, and decision owners remain reproducible after account ownership changes', 'identify handoffs with an upcoming renewal, freeze the pre-handoff and post-handoff records, compare reconstructed decision windows, and independently code missing dates, unsupported assumptions, owner gaps, and late corrections', 'A matched decision window demonstrates record continuity under this protocol. It cannot interpret contract rights, assign fault for delay, or predict renewal, revenue, or client satisfaction.', '2026-08-20-renewal-evidence.png'],
  ['qbr-metric-exception-disclosure-test', 'Are QBR metric exceptions disclosed consistently?', 'Scope Benchmarks', 'whether records excluded from a QBR metric population receive consistent classification, approved treatment, and visible disclosure', 'define the metric population and exception rules before review, sample included and excluded records, have two reviewers reproduce each treatment, and retain disagreements about source quality, calculation effect, and disclosure wording', 'Consistent classification can show that reviewers applied the same frozen rules. It does not prove that the metric is commercially useful, causally meaningful, or comparable with another portfolio.', '2026-08-31-account-metric-definition-drift-study.png'],
  ['handoff-first-action-reconstruction-study', 'Can a receiving owner complete the first account action from the handoff record?', 'Workflow Design', 'whether a receiving owner can reconstruct and complete one approved account action without private explanation from the outgoing owner', 'select bounded handoffs before the first action, freeze available records and permissions, observe an independent reconstruction, then code missing source context, authority ambiguity, access blocks, corrections, and acceptance evidence', 'Successful completion tests usability for one bounded action. It cannot prove the whole handoff is complete, measure individual capability, or show that the action caused a client result.', '2026-08-31-handoff-shadowing-error-detection.png'],
  ['client-feedback-interpretation-agreement', 'When do reviewers disagree about the meaning of client feedback?', 'Scope Benchmarks', 'whether reviewers distinguish source wording, context, observed fact, interpretation, alternative readings, and approved response when coding client feedback', 'build a dated sample of feedback records across channels, remove prior internal labels, ask independent reviewers to code the frozen evidence under a shared rubric, and compare interpretations, uncertainty statements, escalation choices, and proposed follow-up', 'Reviewer agreement demonstrates reproducibility under the stated rubric, not the client\'s intended meaning. Only further client evidence can resolve an ambiguity, and this study cannot infer sentiment, retention, or motive.', '2026-08-31-client-silence-interpretation-research.png'],
];

const sources = [
  { name: 'NIST Cybersecurity Framework 2.0', date: 'February 26, 2024', url: 'https://www.nist.gov/cyberframework', note: 'Primary governance and measurement guidance. It is not an account-management benchmark.' },
  { name: 'NIST SP 800-53 Rev. 5', date: 'updated December 10, 2020', url: 'https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final', note: 'Primary guidance on accountability, access, audit records, and control assessment.' },
  { name: 'GAO Standards for Internal Control in the Federal Government', date: 'September 10, 2014', url: 'https://www.gao.gov/products/gao-14-704g', note: 'Primary standards for reliable information, documented responsibility, monitoring, and corrective action.' },
];

export const research20260910 = topics.map((topic) => ({
  ...makeSeptemberResearchStudy(topic, '2026-09-10'),
  sources,
  statSource: 'Route-specific synthesis of NIST and GAO control principles',
}));
