import type { ResearchPost } from './research-data';

const checked = 'checked September 24, 2026';
const sources = [
  { name: 'NIST Cybersecurity Framework 2.0', date: `February 26, 2024; ${checked}`, url: 'https://www.nist.gov/cyberframework', note: 'Primary risk-management framework used for governance, identification, protection, detection, response, and recovery vocabulary; it is not an account-management benchmark.' },
  { name: 'NIST SP 800-53 Rev. 5, Release 5.2.0', date: `August 27, 2025; ${checked}`, url: 'https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final', note: 'Primary control catalog used for access, audit, information integrity, assessment, and accountability concepts. Controls require local tailoring.' },
  { name: 'GAO Standards for Internal Control in the Federal Government', date: `May 15, 2025; ${checked}`, url: 'https://www.gao.gov/products/gao-25-107721', note: 'Current authoritative framework for preventive controls, quality information, risk assessment, monitoring, and change documentation; private teams are not represented as subject to federal requirements.' },
  { name: 'FTC Start with Security: A Guide for Business', date: `June 2015; ${checked}`, url: 'https://www.ftc.gov/business-guidance/resources/start-security-guide-business', note: 'Authoritative practical guidance on data minimization, sensible access, service-provider oversight, retention, and secure information handling.' },
  { name: 'Philippine National Privacy Commission: Data Privacy Act of 2012', date: checked, url: 'https://privacy.gov.ph/data-privacy-act/', note: 'Primary Philippine legal source for personal-information context. Applicability and legal decisions remain with qualified accountable owners.' },
  { name: 'ISO quality management principles', date: checked, url: 'https://www.iso.org/quality-management/principles', note: 'Authoritative overview of process, improvement, customer focus, relationship management, and evidence-based decision-making principles.' },
];

type Topic = { slug:string; title:string; cluster:string; excerpt:string; hero:string; question:string; unit:string; comparison:string; service:string; decision:string; risk:string; design:string; rows:string[][]; related:string[] };
const topics: Topic[] = [
  { slug:'client-commitment-decomposition-study', title:'What evidence sits inside a client commitment?', cluster:'Workflow Design', excerpt:'A field-level study of source, scope, owner, dependency, due condition, authority, and acceptance proof.', hero:'/research-heroes/2026-09-24-commitment-decomposition.png', question:'whether a client commitment preserves independently reviewable evidence instead of one reassuring sentence', unit:'one purported commitment linked to its earliest source and latest state', comparison:'source-backed, conditional, superseded, blocked, and unaccepted commitments', service:'client-request-routing', decision:'commitment intake and closure', risk:'A promise can hide who spoke, which deliverable was meant, whether approval was assumed, whose calendar controls the date, and what the client will accept.', design:'Freeze the sample, then trace exact wording, speaker, authority, object, scope, dependency, time condition, owners, change history, and acceptance evidence.', rows:[['Source','Wording, speaker, time','Keep conditions'],['Authority','Owner and approval','Attendance is not approval'],['Obligation','Scope and dependency','Avoid implied extras'],['Closure','Action and acceptance','Sent is not accepted']], related:['client-commitment-language-risk','client-closure-proof-analysis'] },
  { slug:'account-evidence-lineage-across-systems-research', title:'Can an account decision survive a cross-system trace?', cluster:'Hiring Controls', excerpt:'A provenance study across CRM, email, meetings, reports, and approved decision records.', hero:'/research-heroes/2026-09-24-evidence-lineage.png', question:'whether an account fact preserves origin, transformation, conflict, and authority across approved systems', unit:'one decision-relevant fact represented in two or more systems', comparison:'unchanged transfers, approved transformations, stale replicas, conflicts, overwrites, and missing origins', service:'crm-account-maintenance', decision:'source selection and reconciliation', risk:'The newest field is not necessarily authoritative. Synchronization can copy an error, while a summary can detach a fact from its qualifier.', design:'Preselect facts; record each system, object, value, time, actor, transformation, conflict, authority rule, and downstream use; independently reproduce the lineage.', rows:[['Origin','System, field, time','Presence is not authority'],['Transform','Rule, before, after','Preserve meaning'],['Conflict','Values and owners','Do not silently select'],['Use','Purpose and trigger','Recheck context']], related:['crm-fact-reconciliation-audit','client-update-source-verifiability-study'] },
  { slug:'account-portfolio-exception-sampling-bias-study', title:'Which account exceptions disappear from the sample?', cluster:'Scope Benchmarks', excerpt:'A sampling-bias study of missing, disputed, reopened, quiet, and easy-to-find cases.', hero:'/research-heroes/2026-09-24-sampling-bias.png', question:'whether a portfolio exception sample represents eligible cases or only searchable, recent, resolved cases', unit:'one eligible exception opportunity defined before its outcome is known', comparison:'routine and consequential, complete and incomplete, open and closed, responsive and nonresponsive cases', service:'account-health-monitoring', decision:'portfolio review scope and escalation attention', risk:'Sampling a closed queue excludes work that never entered it. Requiring complete records removes cases most relevant to a documentation review.', design:'Define an upstream eligible frame, select without outcomes, and preserve nonselection, inaccessibility, duplicates, reopening, substitutions, and exclusions.', rows:[['Frame','Event, window, rule','Set before outcomes'],['Selection','Method and stratum','No convenience swaps'],['Missing','Reason and follow-up','Not normal by default'],['Finding','Counts and denominator','Respect design']], related:['outsourced-account-portfolio-sampling-visibility','client-feedback-response-coverage-study'] },
  { slug:'client-relationship-owner-continuity-study', title:'What survives a client relationship-owner change?', cluster:'Workflow Design', excerpt:'A continuity study of stakeholder context, rights, commitments, sensitivities, and next actions.', hero:'/research-heroes/2026-09-24-owner-continuity.png', question:'whether an owner change preserves enough evidence for approved work without relying on private memory', unit:'one ownership transition through its first independently handled review', comparison:'planned and unplanned transfers, primary and backup coverage, complete and incomplete records', service:'client-onboarding-coordination', decision:'coverage design and owner transfer', risk:'A contact list and task export can omit decision rights, communication preferences, disputed history, dependencies, and context.', design:'Freeze the handoff; trace roles, channels, authority, commitments, history, conflicts, access, restrictions, triggers, backup, and first independent action.', rows:[['Stakeholders','Role and authority','Contact is not authority'],['Work','State and dependency','Keep disputes'],['Access','Approved least privilege','Do not clone blindly'],['Acceptance','Retrieval and confirmation','Transfer is not continuity']], related:['account-handoff-knowledge-decay','client-contact-data-freshness'] },
  { slug:'client-reporting-state-consistency-analysis', title:'Do client reports use the same status definitions?', cluster:'Scope Benchmarks', excerpt:'An analysis of entry evidence, owner, exception rules, and exit conditions behind status labels.', hero:'/research-heroes/2026-09-24-status-taxonomy.png', question:'whether recurring reports apply stable state definitions across accounts and periods', unit:'one reported status for one work item at a dated cutoff', comparison:'same labels with different evidence, different labels for equal evidence, overrides, missing updates, and reopened work', service:'account-reporting', decision:'status taxonomy and portfolio aggregation', risk:'Green can mean started, no known issue, or client acceptance. Aggregating those labels produces a view whose components answer different questions.', design:'Collect definitions first; retain item, cutoff, entry evidence, exclusions, dependency treatment, clock, owner, exit evidence, and corrections; independently recode.', rows:[['Definition','Entry and exclusions','Publish first'],['Cutoff','Time and late-event rule','No hindsight'],['Owner','Work and decision roles','Status is not approval'],['Exit','Evidence and reopen trigger','Delivery may not be acceptance']], related:['client-qbr-metric-definition-drift-research','client-status-evidence-consistency-study'] },
];

const sections = (t:Topic) => [
  { heading:'Research question and decision boundary', paragraphs:[`This study asks ${t.question}. The unit is ${t.unit}. That boundary prevents an account label from replacing the actual evidence. The intended decision is ${t.decision}; the study does not grade an employee, infer client sentiment, establish legal compliance, or promise retention, revenue, response time, or service quality.`, `Facts, interpretations, and decisions are recorded separately. A Philippines-based account specialist may gather permitted sources, normalize fields, prepare a neutral brief, flag exceptions, and coordinate an approved follow-up. Contract, pricing, refund, legal, privacy, security, access, scope, and sensitive client-commitment decisions remain with the accountable owner.`] },
  { heading:'Why the apparent signal can mislead', paragraphs:[t.risk, `The practical safeguard is a claim ledger: source, observed fact, interpretation, uncertainty, authority, affected account work, owner, and next check. “Sent,” “discussed,” “green,” “urgent,” and “complete” are not self-proving states. Each needs a written definition and evidence appropriate to the decision consequence.`] },
  { heading:'Methodology and sampling plan', paragraphs:[t.design, `Use the comparison: ${t.comparison}. Include routine, incomplete, corrected, disputed, missing, and reopened examples. Set the observation window, population, inclusion and exclusion rules, source hierarchy, and stopping rule before reviewing outcomes. Keep unavailable evidence unavailable rather than reconstructing it from memory.`, `Have two reviewers independently code a meaningful subset with the same rubric. Preserve disagreements by field. Agreement supports reproducibility under this protocol, not objective truth; disagreement may expose an unclear definition, inaccessible source, or authority boundary. Retain negative cases and disclose changes before a later replication.`] },
  { heading:'Evidence, privacy, and authority controls', paragraphs:[`Rank sources by authority, specificity, relevance, and freshness for the particular claim. A newer informal note may not override an approved record, while a direct authorized correction may supersede an older field. Preserve both the former and current state, who changed it, the effective date, and why. Do not average incompatible evidence into certainty.`, `Apply data minimization and least privilege throughout. Review only approved systems and fields, avoid copying personal information into working papers, restrict exports, and use named accounts. When evidence is inaccessible, record the limitation and owner. The Data Privacy Act and FTC guidance provide context, but qualified owners must determine obligations and approved handling for the actual client.`] },
  { heading:'Analysis and reporting', paragraphs:[`Report counts, denominators, exclusions, missing fields, state transitions, contradictory cases, and reviewer disagreements before summarizing a pattern. Distinguish description from inference. If one state appears more often in the sample, say exactly that; do not claim it caused delay, satisfaction, churn, or a commercial result.`, `A client-safe brief should state the strongest supported observation, the material uncertainty, the accountable decision, the permitted next action, and the review trigger. Comparisons across accounts require stable definitions and comparable visibility. Where those conditions fail, publish separate case findings rather than a misleading pooled rate.`] },
  { heading:'Framework interpretation', paragraphs:[`NIST CSF 2.0 offers governance and risk-management outcomes; SP 800-53 supplies adaptable control language for access, audit, assessment, and information integrity. GAO’s 2025 Green Book emphasizes preventive controls, quality information, monitoring, and documented change assessment. FTC guidance supports minimization, sensible access, retention discipline, and service-provider oversight. ISO principles support process and evidence-based decisions.`, `None of these sources sets an outsourced-account-management staffing ratio, service level, workflow duration, or performance benchmark. They do not prove that this method improves a client outcome. The buyer’s contracts, policies, system rules, approved procedures, and named decision rights govern. Framework language should clarify a control, never manufacture authority.`] },
  { heading:'Limitations and replication', paragraphs:[`Material limits include small or convenience samples, inaccessible channels, informal decisions, inconsistent clocks, different contracts, holidays, geography, tool configuration, stakeholder availability, survivorship in retained records, and reviewer knowledge of outcomes. Public findings must not reveal client-confidential or personal data.`, `A later team can replicate the study by freezing the same definitions, selecting a new period without inspecting results, recoding a subset independently, reporting missingness, and documenting every method change. The narrow conclusion is that ${t.decision} becomes more reviewable when source, definition, authority, uncertainty, owner, and verification remain connected. That is an operating-control finding, not a guarantee.`] },
];

export const research20260924: ResearchPost[] = topics.map(t => ({
  slug:t.slug, title:t.title, cluster:t.cluster, excerpt:t.excerpt, hero:t.hero,
  published:'2026-09-24', datePublished:'2026-09-24', updated:'2026-09-24',
  headlineStat:'Seven evidence fields connect a source to a reviewable account decision', statSource:'Route-specific synthesis of NIST, GAO, FTC, NPC, and ISO control principles',
  takeaways:['Define the population, unit, state, authority, and comparison before inspecting outcomes.','Preserve missing, contradictory, corrected, and reopened records.','Keep evidence preparation with the support role and consequential judgment with the accountable owner.','Require a dated next check or acceptance condition before claiming closure.'],
  sections:sections(t), table:{headers:['Evidence state','Minimum record','Boundary'],rows:t.rows}, sources,
  researchMethodology:`Fixed-window review of ${t.unit}; frozen definitions and sources; explicit missingness; independent recoding; sensitivity checks; bounded conclusions.`, externalSources:sources.map(s=>s.url),
  faqs:[{q:'Can this study prove a client outcome?',a:'No. It describes evidence and workflow state in a bounded sample; it cannot prove causality, satisfaction, retention, revenue, or a guaranteed result.'},{q:'What may the outsourced specialist do?',a:'They may gather permitted evidence, maintain assigned records, prepare neutral summaries, flag exceptions, and coordinate approved follow-up. Consequential decisions stay with accountable owners.'},{q:'How should another team replicate it?',a:'Freeze definitions and the observation window, retain missing and contrary cases, independently recode a subset, report exclusions, and disclose every method change.'}],
  related:t.related, internalLinks:[{label:`Review ${t.service.replaceAll('-',' ')} support`,href:`/services/${t.service}`},{label:'Explore the research library',href:'/research'}],
}));
