import { makeSeptemberResearchStudy, type SeptemberResearchTopic } from './research-2026-09-07';

const topics:SeptemberResearchTopic[]=[
 ['client-decision-dependency-reconstruction','Can reviewers reconstruct the downstream impact of a delayed client decision?','Workflow Design','whether independent reviewers can identify every account task and promise blocked by the same pending client decision','freeze a set of decision records and related task histories, ask two reviewers to map dependencies independently, then compare missed links, unsupported links, timing, and client consequences','A dependency map can establish what records are linked under the protocol, but it cannot prove the delay caused every downstream outcome or that one prioritization choice is universally correct.','2026-08-31-account-queue-invisible-work-analysis.png'],
 ['renewal-evidence-gap-priority-study','Which missing renewal evidence changes reviewer priority?','Scope Benchmarks','whether reviewers distinguish consequential evidence gaps from routine missing fields in renewal preparation','present matched renewal packets with controlled omissions, use a predefined consequence rubric, and compare priority, requested source, uncertainty, and escalation decisions','Reviewer agreement may reflect a shared rubric rather than a true commercial outcome. Contracts, timing, client statements, and owner judgment remain material.','2026-08-20-renewal-evidence.png'],
 ['qbr-metric-definition-change-detection','Do reviewers detect metric definition changes in QBR drafts?','Hiring Controls','whether a documented review catches population, period, calculation, or inclusion-rule changes before a client-facing QBR','construct paired source packets and draft claims, vary one definition element at a time, and record detection, evidence citation, proposed correction, and approval routing','This design measures detection under prepared conditions. It does not estimate real-world error rates, client trust, revenue impact, or the quality of any named team.','2026-08-31-account-metric-definition-drift-study.png'],
 ['temporary-scope-exception-expiry-reliability','Are temporary scope exceptions closed when their approval expires?','Workflow Design','whether teams consistently identify, renew, reject, or close temporary service exceptions at the stated expiry condition','sample dated exception records, verify approval and expiry evidence, compare recorded disposition with subsequent activity, and independently code unresolved cases','Continued activity after expiry can indicate stale records, an undocumented decision, or scope drift; the observation alone cannot determine which explanation is correct.','2026-08-31-client-decision-expiry-bias-study.png'],
 ['account-coverage-exception-transfer-study','What information survives when coverage exceptions return to the primary owner?','Scope Benchmarks','whether blocked actions, authority gaps, client wording, and next checks remain reconstructable after temporary account coverage ends','compare pre-coverage state, exception logs, messages, return briefs, owner reconstruction, and first follow-up using a frozen evidence cutoff','Successful reconstruction supports record completeness under this sample, not a claim that coverage caused better service or that the method generalizes across clients and tools.','2026-08-31-handoff-shadowing-error-detection.png'],
];

export const research20260908=topics.map(t=>makeSeptemberResearchStudy(t,'2026-09-08'));
