import type { ResearchPost, ResearchSection } from './research-data';

const checked = 'checked October 2, 2026';
const coreSources = [
  { name: 'NIST Cybersecurity Framework 2.0', date: `February 26, 2024; ${checked}`, url: 'https://www.nist.gov/cyberframework', note: 'Primary framework used for governance, risk, protection, response, and recovery concepts; it does not prescribe account-management service levels.' },
  { name: 'NIST SP 800-53 Rev. 5, Release 5.2.0', date: `August 27, 2025; ${checked}`, url: 'https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final', note: 'Primary control catalog used for authorization, audit, information integrity, monitoring, and change-control concepts; controls require local tailoring.' },
  { name: 'Standards for Internal Control in the Federal Government', date: `May 15, 2025; ${checked}`, url: 'https://www.gao.gov/products/gao-25-107721', note: 'Authoritative source for quality information, control activities, monitoring, segregation of duties, and remediation.' },
  { name: 'Start with Security: A Guide for Business', date: `June 2015; ${checked}`, url: 'https://www.ftc.gov/business-guidance/resources/start-security-guide-business', note: 'Authoritative business guidance on data minimization, access control, service-provider oversight, retention, and secure handling.' },
  { name: 'Data Privacy Act of 2012', date: checked, url: 'https://privacy.gov.ph/data-privacy-act/', note: 'Primary Philippine legal source for personal-information context; qualified owners determine applicability and required handling.' },
  { name: 'Quality management principles', date: checked, url: 'https://www.iso.org/quality-management/principles', note: 'Authoritative overview of customer focus, process approach, improvement, relationship management, and evidence-based decisions.' },
];

type Draft = { slug:string; title:string; cluster:string; excerpt:string; hero:string; service:string; headline:string; related:string[]; headings:string[]; paragraphs:string[][]; rows:string[][]; };

const drafts: Draft[] = [
  {
    slug:'client-delegation-expiry-control-study', title:'When does a client delegation stop being safe to use?', cluster:'Hiring Controls', hero:'/research-heroes/2026-09-24-owner-continuity.png', service:'client-request-routing', headline:'A delegation record needs a decision scope, effective window, issuer, delegate, and revocation route', related:['account-decision-rights-analysis','client-stakeholder-authority-drift-study'],
    excerpt:'A bounded study of temporary client authority, expiry evidence, overlapping instructions, revocation, and the decisions an account specialist must route rather than infer.',
    headings:['Delegation is a timed claim, not a reusable contact preference','Construct the authority interval from dated evidence','Challenge the record with collision cases','Study expiry as an operational transition','Design the confirmation path around consequence','What an account team may conclude'],
    paragraphs:[
      [
        'Temporary authority is common during leave, implementation, executive travel, incident response, and organizational change. The operational error is to store a delegate as though the relationship were permanent. A defensible delegation identifies who granted it, which decisions it covers, when it starts, when it ends, and how a later instruction changes it. Familiarity, seniority, meeting attendance, or possession of an old email does not independently establish current authority. This research treats every use of delegated authority as a dated event, not as a static property of the person.',
        'The unit of analysis is one consequential instruction processed under an asserted delegation. Consequential means it could change scope, timing, access, data handling, money, or a client-facing commitment. Routine acknowledgements can be studied separately because their authority threshold may be lower. Before sampling, define the eligible systems, instruction classes, observation window, source hierarchy, and cutoff timezone. Record what the support team could see at the decision time; later evidence belongs in a sensitivity view rather than being allowed to repair the historical record silently.'
      ],
      [
        'Build an interval from the granting record, effective date, explicit end date, triggering event, amendments, and revocation evidence. A message saying “cover while I am away” creates a different interval from an approved matrix assigning invoice disputes for a quarter. If the end condition is return from leave, the team needs an authorized way to observe that condition. If no expiry is stated, classify duration as unresolved and route it; do not manufacture permanence. Preserve the source wording because summaries often erase conditions that determine whether a later instruction is valid.',
        'Measure the time between the real-world change and each affected operational update: approval matrix, CRM role, workflow assignee, shared inbox rule, meeting invite, and open decision queue. These are distinct propagation clocks. A fast CRM edit does not prove that an approval route changed correctly, while a late CRM edit does not prove that staff acted without confirmation. Report the source, actor, timestamp, and permitted interim behavior for every transition so reviewers can distinguish stale display data from unsupported processing.'
      ],
      [
        'Oversample collisions: the principal and delegate give inconsistent directions; two delegates claim the same decision; a delegate acts after the stated date; a permanent successor appears before temporary authority is revoked; or the instruction falls outside the named scope. These cases expose whether the procedure compares evidence or merely trusts the newest message. Code the consequence, conflicting sources, pause or reversible action, escalation owner, client-safe wording, and final disposition. Do not score a cautious confirmation request as poor responsiveness merely because the instruction was eventually approved.',
        'Include clean cases and false alarms. A delegation can remain valid even if a job title changes, and an automated expiry alert can be wrong when an amendment exists in an approved system. Conversely, a current job title can coexist with expired decision rights. Independent reviewers should classify a subset without seeing the final outcome, then compare their conclusions. Disagreement may reveal ambiguous source language, not reviewer failure. Preserve disagreement and route material uncertainty rather than forcing a favorable consensus.'
      ],
      [
        'Expiry creates work beyond changing a field. Open approvals may need reassignment; scheduled messages may need a new reviewer; access may need review; and the principal may need a concise list of decisions made during the interval. Study whether the expiry event reaches these queues and whether unfinished work retains its evidence. Deleting the delegate from a contact list can conceal why earlier actions were accepted. Good closure preserves the historical authority state while preventing that state from authorizing new work.',
        'Useful measures include eligible delegation events, complete interval records, uses inside and outside scope, collision cases, confirmations requested, expired permissions still visible, and unresolved items at cutoff. Each rate needs its own denominator. Avoid claiming that a control prevented loss, improved retention, or proved compliance. The study can show whether authority was reconstructable and whether exceptions followed the approved route; causal business outcomes require a different design and evidence set.'
      ],
      [
        'Use consequence tiers to make confirmation proportionate. A low-risk scheduling choice may follow an approved operational rule, while a pricing change, data export, contract interpretation, security statement, or new delivery promise should reach the accountable owner. State the minimum evidence for each tier and the reversible actions allowed while waiting. Acknowledging receipt is not acceptance. Preparing options is not deciding. Keeping these states separate lets a specialist remain responsive without converting delegated access into unrestricted judgment.',
        'The confirmation request should quote the decision at issue, identify the delegation evidence and its apparent limit, describe the operational effect of waiting, and name the exact answer required. It should not accuse a client contact or expose unnecessary internal detail. Record the response source, effective time, downstream updates, and any superseded instruction. Where client systems are unavailable, state that visibility limit explicitly instead of treating silence as evidence that no delegation or revocation exists.'
      ],
      [
        'The bounded conclusion is that a delegation is usable only when issuer authority, delegate identity, decision class, effective interval, and current evidence agree. An outsourced account specialist may collect records, maintain an assigned matrix, flag expiry, prepare neutral options, and coordinate confirmation. The specialist should not extend an interval, reinterpret a vague grant, resolve competing client authorities, or make a consequential commitment. Those decisions remain with designated owners.',
        'Replication requires the same eligibility frame, consequence definitions, source hierarchy, cutoff, missingness codes, collision sampling, and independent recoding. Disclose excluded private channels and inaccessible client records. Report late corrections as late corrections. The reader outcome is a practical authority-expiry review that shows exactly what can proceed, what must pause, who decides, and which systems need an approved update—without pretending that a neat matrix captures every part of client governance.'
      ]
    ],
    rows:[['Grant','Issuer, delegate, scope, effective start','Familiarity is not authority'],['Limit','Expiry or triggering event','Missing duration stays unresolved'],['Collision','Conflicting instruction and consequence','Route; do not choose silently'],['Closure','Open work, history, downstream updates','Preserve prior valid actions']]
  },
  {
    slug:'renewal-assumption-sensitivity-analysis', title:'Which assumptions can reverse an account renewal forecast?', cluster:'Scope Benchmarks', hero:'/research-heroes/2026-09-24-sampling-bias.png', service:'renewal-administration', headline:'A forecast is decision-ready only when changing a plausible assumption shows how the conclusion moves', related:['renewal-signal-calibration','renewal-risk-signal-disagreement'],
    excerpt:'A sensitivity analysis separating observed renewal evidence from assumptions about timing, authority, missing signals, and commercial interpretation.',
    headings:['Forecast confidence can hide fragile assumptions','Create a renewal evidence boundary','Vary one assumption at a time','Use scenarios without inventing probability','Investigate reversals and stable conclusions','Turn sensitivity into an accountable review'],
    paragraphs:[
      ['Renewal forecasts often combine facts and assumptions in one label. A delivery milestone is observable; whether it predicts renewal is an interpretation. A client statement may be authentic but come from someone without commercial authority. Silence may reflect satisfaction, disengagement, procurement timing, or simple unavailability. This study asks which plausible changes to those assumptions would reverse the forecast. Its purpose is not to produce a more impressive probability. It is to show decision owners where the conclusion is robust, where it is fragile, and what evidence is worth obtaining next.','Define one account-renewal decision at a declared cutoff. Freeze the agreement identity, renewal window, products or services in scope, decision route, and approved evidence sources. Separate delivery records, open commitments, stakeholder statements, payment or procurement events available to the reviewer, support patterns, and explicit commercial decisions. Do not infer access to private client deliberations. Evidence arriving after cutoff belongs to a later view. This protects the analysis from hindsight and makes a forecast revision explainable rather than cosmetic.'],
      ['Create an evidence table with source date, owner, direct wording, relevance, freshness, authority, and contradiction status. Missing fields are not neutral. Record whether absence comes from an inaccessible system, an unasked question, a retention limit, or a genuinely missing event. A support role can assemble this table but cannot decide what contract language means or assign commercial weight without an approved model. Keep observed signal, analyst interpretation, and owner judgment in visibly separate fields.','Choose assumptions before looking at the preferred result. Examples include treating a conditional client statement as positive, treating an overdue commitment as material, treating a changed contact as loss of sponsorship, or treating a procurement request as evidence of intent. Write a reasonable alternative for each and the source that could resolve it. Reject variables that merely restate the outcome. The exercise is valuable only when alternatives are plausible within the account record and decision owners can understand why they matter.'],
      ['Run one-at-a-time sensitivity first. Hold the evidence set constant and change a single interpretation rule, cutoff, freshness window, or missing-data treatment. Record whether the forecast category, recommended action, or uncertainty note changes. Then test a small number of combined scenarios representing coherent account states. Avoid hundreds of combinations that create false precision. The goal is traceability: a reviewer should see which assumption moved which conclusion and whether the movement is operationally meaningful.','Time deserves its own test. Move the cutoff to the dates of a delivery exception, executive meeting, notice deadline, corrected invoice, or confirmed stakeholder change. This reveals conclusions that depend on when the snapshot was taken. Do not rewrite the old forecast with later knowledge. Preserve each dated view, the evidence then available, and the reason for revision. A series of honest changes is more informative than a stable label achieved by silently importing future facts.'],
      ['Scenarios should be named by evidence conditions, not emotional labels. “Authorized positive statement confirmed” is clearer than “best case.” “Open critical commitment remains unresolved at notice date” is clearer than “worst case.” Each scenario lists included observations, assumptions, excluded unknowns, and the accountable action it would support. Do not attach probabilities unless an approved, validated method and suitable historical data exist. A narrative scenario is not a statistical likelihood and should never be presented as one.','Compare scenarios using decisions rather than decorative scores: request confirmation, resolve an operational gap, prepare a renewal packet, escalate a commercial question, or continue monitoring. If several scenarios produce the same next action, that action may be robust even when the renewal outcome is uncertain. If a small assumption changes a consequential recommendation, the forecast is fragile. That finding should increase transparency and evidence gathering, not invite an analyst to choose the assumption that creates the desired label.'],
      ['Investigate every reversal. Identify the exact evidence field and rule responsible, whether the alternative is credible, who owns clarification, and how long the uncertainty can remain open. Also examine stable conclusions for hidden insensitivity: a model that never changes may be hard-coded, dominated by one field, or too coarse to reveal real variation. Independent reviewers should reproduce a sample from the frozen record. Differences belong in the report with their causes and resolution status.','Report denominators: accounts eligible, evidence-complete, tested, reversed by one assumption, reversed only in combined scenarios, and unresolved. Do not generalize from a convenience sample or claim that a forecast caused renewal. Different contracts, client decision structures, regions, and observation access limit comparison. The analysis evaluates the integrity of the forecast process, not client sentiment, revenue certainty, employee performance, or the legal meaning of a renewal provision.'],
      ['The outsourced specialist may maintain the evidence table, calendar deadlines from approved sources, run declared transformations, flag fragile conclusions, and prepare questions. Pricing, concessions, notice interpretation, probability judgments, and the final renewal position remain with accountable owners. Approved client wording must be used for external follow-up. A request for missing evidence should not reveal internal scoring or turn a forecast into an implied commitment.','A useful sensitivity brief fits the decision: current evidence, base interpretation, alternatives tested, conclusions that changed, conclusions that did not, missing facts, next evidence event, and owner. Replication requires the same cutoff, evidence hierarchy, rules, scenario definitions, and missing-data treatments. The reader outcome is not certainty. It is an auditable map showing which assumptions matter enough to verify before an account team acts.']
    ],
    rows:[['Observation','Dated source and exact signal','Do not blend with interpretation'],['Assumption','Declared rule and alternative','Must be plausible and resolvable'],['Sensitivity','Result before and after change','No invented probability'],['Decision','Robust action or owner review','Forecast does not authorize terms']]
  },
  {
    slug:'client-commitment-dependency-topology-study', title:'Why do client commitments stall even when every task has an owner?', cluster:'Workflow Design', hero:'/research-heroes/2026-09-22-meeting-decision-traceability.png', service:'account-health-monitoring', headline:'Task ownership does not reveal the approvals, source facts, access, and predecessor work that control completion', related:['client-commitment-aging-analysis','account-priority-override-outcome-study'],
    excerpt:'A dependency-topology study that maps commitments as linked evidence, authority, access, timing, and work events rather than isolated due dates.',
    headings:['A named owner can still inherit an impossible promise','Model commitments as a directed evidence graph','Find hidden gates and circular waiting','Measure delay without assigning false cause','Test interventions against the original network','Use the map for decisions, not surveillance'],
    paragraphs:[
      ['Account registers usually store owner, due date, and status. That view can conceal the system controlling completion: a client answer, an approved source file, specialist capacity, security review, decision authority, or another commitment. This study represents one consequential client commitment as a network of prerequisites and handoffs. It asks whether the stated owner had a feasible path to closure at the time of acceptance and which dependency became decisive. The method does not assume that elapsed time proves neglect or that a dense network is necessarily poorly designed.','Freeze the commitment wording, acceptance source, accountable owner, intended evidence of completion, due condition, and permitted client communication. Then identify every prerequisite known at acceptance. Separate information, approval, access, capacity, external event, and predecessor-work dependencies. A dependency is not merely someone who was copied. It must have an observable condition whose satisfaction enables a next step. Unknown dependencies discovered later remain dated discoveries so the original planning quality can be studied honestly.'],
      ['Represent each condition as a node and each required transition as a directed edge. Add owner, source, earliest known time, latest acceptable time, visibility, sensitivity, and current state. This topology reveals forks where several inputs can proceed together, joins where all inputs are required, and gates where one decision controls the rest. Keep optional improvements outside the critical closure path. Otherwise the graph can exaggerate complexity and make every desirable detail appear mandatory.','Validate the graph with the people who own its boundary points, not only the coordinator who maintains it. A client-side approval may be visible only as a requested confirmation; a private decision path should not be invented. An inaccessible dependency is recorded as such. Apply data minimization: map the condition and accountable interface without copying confidential content into a broad operational record. The Philippine privacy context and FTC guidance inform careful handling, while qualified owners decide actual obligations.'],
      ['Look for circular waiting: an approval waits for a final date while the date waits for approval; a report waits for corrected data while correction waits for the report owner; access waits for onboarding completion while onboarding completion requires a system check. Also identify orphan nodes with no owner, phantom nodes already satisfied but never updated, and shadow dependencies managed in private messages. These structures can stall work even when every visible task has a named assignee.','Sample completed, late, canceled, reopened, and still-open commitments. A dataset containing only completed work deletes the networks most likely to expose design weaknesses. Preserve superseded due dates and scope changes. If the commitment was redefined, show the old and new closure tests instead of measuring the new task against the old promise. Include a counterexample review where a complex network completed reliably, which prevents the analysis from equating complexity with failure.'],
      ['Measure waiting by dependency state: time before request, time awaiting evidence, time awaiting authority, time blocked by access, active work time, and time after the closure evidence existed but before the record changed. Clocks may overlap, so do not sum them blindly. State business calendars, timezones, pause rules, and cutoff. A long client-dependent interval is operationally different from unassigned internal waiting, but neither alone explains the final client outcome.','Causal language requires restraint. A missing approval may coincide with delay while another unavailable input would have blocked completion anyway. Use the graph to identify necessary recorded conditions and observed sequences, not to claim a single root cause. Compare similar commitment types only where definitions, visibility, consequence, and clocks align. Report missing nodes, later discoveries, and alternate paths. Independent reconstruction of a subset tests whether the topology follows the source record rather than the author’s narrative.'],
      ['Test changes against the frozen network. Earlier evidence requests, parallel preparation, explicit acceptance criteria, backup approvers, and dependency review at intake may alter the path. For each proposed intervention, state the node affected, authority needed, new risk, and evidence that would show improvement. Do not assume that bypassing a gate is efficient; a security, privacy, commercial, or quality gate may be essential. The safer option may be earlier routing rather than removal.','After closure, compare the planned and actual network. Record newly discovered dependencies, unused prerequisites, rerouting, reversals, and residual obligations. Completion of the headline task does not close displaced or derivative work automatically. A client update may still be due, temporary access may need removal, and a corrected record may need propagation. The post-close topology keeps those residual nodes visible without pretending they are part of the original deliverable.'],
      ['Use the map to prepare a decision brief: commitment, current limiting condition, evidence, accountable interface, reversible work available now, next review trigger, and client-safe update status. The support role may maintain nodes, chase approved inputs, flag circular waits, and prepare options. It should not waive a prerequisite, invent an approval, change scope, grant access, or promise a new date. Those decisions belong to the named owners.','Useful reporting includes commitments sampled, topology completeness, hidden dependencies discovered, circular waits, orphan conditions, changes after acceptance, and unresolved residual nodes. The denominator and visibility boundary accompany every count. Replication requires the same node definitions, source hierarchy, cutoff, closure rules, and reconstruction procedure. The reader receives a method for finding why owned work is not yet feasible, without turning a workflow map into employee monitoring or unsupported blame.']
    ],
    rows:[['Commitment','Approved wording and closure proof','Status label is insufficient'],['Node','Necessary evidence, authority, access, or work','Copied contact is not a dependency'],['Edge','Required transition and owner interface','Preserve parallel paths'],['Residual','Unfinished derivative obligation','Headline completion is not universal closure']]
  },
  {
    slug:'service-exception-update-sequence-study', title:'What should an account team say while a service exception is still unresolved?', cluster:'Workflow Design', hero:'/research-heroes/2026-09-24-owner-continuity.png', service:'account-reporting', headline:'An unresolved exception needs a sequence of verified updates, not a premature resolution narrative', related:['service-recovery-evidence-analysis','client-escalation-response-quality'],
    excerpt:'A communication-sequence study of acknowledgements, verified facts, uncertainty, owner decisions, correction behavior, and closure evidence.',
    headings:['One message cannot carry every stage of an exception','Reconstruct the communication sequence','Score factual change, not reassuring tone','Examine corrections and silence intervals','Protect decision authority under pressure','Define closure from evidence'],
    paragraphs:[
      ['An exception unfolds through observation, validation, impact assessment, owner decision, remediation, verification, and follow-up. Compressing these stages into one polished message encourages unsupported certainty. This study examines the sequence of approved client updates and the evidence available at each send time. The question is not which phrase sounds most empathetic. It is whether each message accurately states the known facts, uncertainty, ownership, next checkpoint, and limits of the sender’s authority without implying that investigation or recovery is complete.','Select one material service exception as the unit. Freeze its governing service source as identified by the accountable owner, first observed signal, internal escalation time, approved communication route, and verified closure test. Include ordinary, disputed, reopened, corrected, and unresolved cases. Exclude legal conclusions and contract interpretations unless supplied by qualified owners. The account specialist can preserve the sequence but should not decide whether an event constitutes breach, liability, security incident, or entitlement.'],
      ['Build a message timeline containing draft, approval, send, delivery evidence, recipient route, factual claims, uncertainty statements, promised checkpoint, and later correction. Link each claim to what was known then. A statement can be accurate when sent and later superseded; preserve both states. Drafts matter for process review but are not client communications. Technical delivery does not prove the appropriate stakeholder received or understood the update.','Classify messages by purpose: acknowledgement, investigation checkpoint, verified impact update, decision request, remediation notice, restoration verification, or post-event follow-up. A message may serve two purposes, but combining too many creates ambiguity. The acknowledgement should not guess cause. An investigation update should not promise recovery. A restoration notice should distinguish observed service state from durable resolution. This stage vocabulary makes omissions and premature transitions visible.'],
      ['Evaluate factual coverage using claim-level fields: source, time boundary, affected scope, known limitation, owner, and next evidence event. Do not reward length. A short update can be decision-ready when facts are few; a long update can obscure the only important uncertainty. Compare internal evidence with approved external wording to identify unsupported additions and material omissions while respecting that sensitive details may be intentionally withheld. Record the authorized reason rather than labeling every omission deceptive.','Tone cannot be measured as truth. Avoid scoring apology intensity or confidence as if it proved communication quality. Instead, test whether a reasonable reader could distinguish observation from hypothesis, action from outcome, and target from commitment. Check dates and timezones. Identify absolute language such as “resolved,” “all,” or “no impact” and require proportionate evidence. The study reports communication integrity, not client satisfaction or the emotional adequacy of a response.'],
      ['Corrections are first-class events. Record what changed, why, who approved the correction, when it reached the client route, and which downstream records were updated. A prompt correction can demonstrate control without erasing the original mistake. Study reopened cases separately: if the service regressed after verified restoration, the new event should reference the earlier sequence but not silently rewrite its closure evidence.','Measure silence intervals from the promised checkpoint, not only from the previous message. An interval may be authorized when there is no new verified fact, but a missed promised update is still observable. Record whether a holding update was required, who owned it, and what prevented delivery. Do not invent a universal cadence; contracts, consequence, client preference, and incident process differ. The approved source and accountable owner determine the relevant expectation.'],
      ['Pressure creates authority risk. Clients may ask for cause, compensation, security conclusions, staffing changes, or guaranteed recovery times before evidence exists. The support role may acknowledge, gather facts, maintain the timeline, prepare approved wording, and route the question. It must not concede liability, offer credits, interpret terms, disclose restricted details, or convert an engineering target into a promise. The sequence record should show every routed decision and the reversible operational work allowed meanwhile.','Use recipient minimization. Escalation does not justify broadcasting sensitive data or adding stakeholders without an approved purpose. Record recipient role and route, not unnecessary personal details. Where a changed contact or delegate creates uncertainty, pause consequential disclosure and use the authority-confirmation process. FTC security principles and Philippine privacy law provide context, but qualified owners decide lawful handling and contractual notification duties.'],
      ['Closure requires the declared verification evidence, accountable acceptance, residual-action list, and approved final update. A sent message alone does not close the exception. Neither does disappearance of the initial signal if monitoring coverage is uncertain. Preserve limitations and the review window. Separate restoration, remediation, and prevention; each may finish at a different time and belong to different owners.','Report eligible sequences, missing stages, claims later corrected, missed checkpoints, premature closure language, reopened cases, and unresolved items at cutoff. Include denominators and inaccessible channels. Independent reviewers should code a subset from the same timeline. Replication requires the same stage definitions, claim fields, source hierarchy, and cutoff. The reader outcome is a practical way to stay candid and useful during uncertainty while protecting client trust and accountable decision rights.']
    ],
    rows:[['Acknowledge','Observed issue, owner, next checkpoint','No guessed cause'],['Update','Verified change and remaining uncertainty','Target is not a promise'],['Correct','Superseded claim and propagation','Preserve original message'],['Close','Verification, acceptance, residual work','Sent notice alone is insufficient']]
  },
  {
    slug:'crm-correction-propagation-boundary-study', title:'How far should a corrected client fact propagate?', cluster:'Hiring Controls', hero:'/research-heroes/2026-09-24-sampling-bias.png', service:'crm-account-maintenance', headline:'A correction is controlled when affected decisions update without copying client data into every connected record', related:['cross-system-account-reconciliation','account-record-reconciliation-study'],
    excerpt:'A field-level study of correction authority, lineage, downstream decision use, privacy boundaries, derived values, and proof that stale facts stopped driving work.',
    headings:['Correction completeness is not the same as copying everywhere','Start with the claim and its lineage','Map downstream use by decision consequence','Handle derived fields and historical reports','Verify containment of the stale value','Set a bounded propagation rule'],
    paragraphs:[
      ['A CRM correction can be too narrow or too broad. Changing one field may leave stale facts in renewal packets, account briefs, approval routes, and active tasks. Copying the correction into every system may create unnecessary exposure, conflicting versions, and retention problems. This study asks which downstream uses must change for decisions to remain accurate while keeping personal and client-confidential data limited to approved purposes. It evaluates propagation control, not the truth of a client fact beyond the authorized source.','The unit is one material corrected claim: stakeholder role, approved contact route, service scope, commitment date, account identifier, billing instruction, or another field that influences work. Freeze the original value, source, capture time, correction request, correction authority, effective time, and reason category. Preserve history where authorized. A correction may replace an error, record a real-world change, narrow an overbroad statement, or resolve conflicting sources; these events have different implications.'],
      ['Create lineage from authoritative source to CRM field, synchronized copies, manual exports, calculations, reports, workflows, and decisions. Label each edge as copy, transformation, lookup, notification, or human reuse. Do not assume technical integration means semantic equivalence. Two fields called “owner” may mean relationship owner and task assignee. Compare definitions before propagating a value, and route ambiguity to the accountable data owner.','Record purpose, sensitivity, access group, retention rule, freshness need, and decision consequence at every destination. This makes minimization operational. A meeting agenda may need the current role but not personal contact details. An audit record may need the superseded value and correction date. A public-facing report may need neither. The map should transmit the minimum fact necessary for each approved purpose rather than treating consistency as universal duplication.'],
      ['Prioritize destinations where the stale value can authorize action, route sensitive communication, calculate a client metric, trigger a deadline, or shape a commitment. Passive archives and expired drafts receive a different treatment from live approval matrices. Define whether each destination requires update, invalidation, annotation, recomputation, recipient notification, or no action. The accountable owner approves the rule for consequential systems.','Sample corrections by field type and consequence, including rejected requests, conflicting corrections, late discoveries, synchronization failures, and cases with no downstream use. A clean-only sample hides the boundary decisions. Freeze the eligible population upstream and report exclusions. Independent reviewers should trace a subset without being told the eventual outcome; disagreement often reveals undocumented reuse or inconsistent definitions.'],
      ['Derived values require recomputation rather than direct replacement. A corrected milestone date may change aging, health indicators, forecast windows, and exception flags. Record formula version, inputs, recomputation time, and reviewer. Never assume that a dashboard refresh proves every cached export or narrative changed. Conversely, not every historic report should be rewritten. Preserve what was known at its original cutoff and attach a correction note where the old claim affects continuing interpretation.','Client-facing correction needs its own approval route. Internal propagation does not authorize a specialist to announce fault, interpret contractual effect, or disclose private source details. Prepare neutral wording that states the corrected operational fact, effective date, affected next step, and owner-approved limitation. If recipients of the old statement need notice, identify them from an approved distribution record rather than expanding the audience in the name of completeness.'],
      ['Verification should test use, not merely field equality. Can a workflow still route to the stale owner? Does search surface an old export first? Does an open task retain a superseded due date? Does the renewal brief recompute? Select sentinel decisions for each material destination and confirm the current value or an explicit invalidation. Record inaccessible systems as limits. Do not claim eradication when private copies, local downloads, or client systems are outside visibility.','Measure correction-to-source time, source-to-CRM time, CRM-to-decision-use time, failed synchronizations, unresolved conflicts, stale sentinel uses, and over-propagation events. Clocks can begin at different events, so publish definitions and timezone. A slow interval does not establish negligence; authorization, client response, scheduled reporting, and system controls may explain it. The evidence supports process findings, not causal claims about commercial outcomes.'],
      ['Containment includes revoking inappropriate access and disposing of temporary working copies under approved rules. It does not mean deleting audit history required for accountability. Separate the current operational value from the historical record. The FTC and NIST sources support minimization, access control, audit, and integrity concepts, while the Philippine legal source provides jurisdictional context. Qualified privacy, security, legal, and contract owners decide actual obligations.','The support role may document lineage, update assigned fields, run approved reconciliations, flag stale uses, prepare a correction packet, and coordinate owner review. It should not choose between conflicting authoritative sources, alter restricted systems, notify clients without approval, or decide retention. Least privilege applies to the correction project itself; broad export access should not be granted merely because a field may have propagated.'],
      ['A bounded propagation rule names the controlling source, effective date, destinations by purpose, required action, owner, verification test, retention treatment, and stop condition. It also names destinations deliberately excluded. That exclusion record prevents future reviewers from mistaking minimization for an oversight. Reopen the map when integrations, reports, purposes, or source authority change.','Report how many material corrections were eligible, fully traced, verified at sentinel uses, limited by inaccessible destinations, over-propagated, or unresolved at cutoff. Avoid a single “accuracy rate” that hides field consequence and visibility. Replication requires the same lineage definitions, destination inventory, decision tiers, source hierarchy, and verification procedure. The reader gains a defensible way to stop stale facts from driving work without building an uncontrolled copy network.']
    ],
    rows:[['Claim','Original, correction, authority, effective time','Do not erase lineage'],['Destination','Purpose, definition, sensitivity, consequence','Consistency is not universal copying'],['Action','Update, invalidate, annotate, recompute, or none','Owner approves consequential rules'],['Verify','Sentinel decision and stale-use search','State inaccessible limits']]
  }
];

const additionalAnalysis: Record<string, ResearchSection> = {
  'client-delegation-expiry-control-study': { heading:'Apply the protocol to an operating example', paragraphs:[
    'Consider a client sponsor who delegates approval of routine campaign schedules during a three-week absence. A request then arrives from the delegate to change the delivery channel and add a new recipient group. The schedule decision may fall inside the grant while the channel and recipient changes do not. The reviewer should split the instruction, preserve the exact delegation wording, allow only the portion supported by current authority, and route the remainder. When the sponsor returns, open decisions need reassignment and the delegate’s temporary route needs closure. Treating the whole message as either valid or invalid would lose the decision-specific boundary that the evidence actually supports.',
    'A second example tests revocation latency. The sponsor ends the arrangement early, but the approval matrix updates before the shared inbox rule. A prepared response remains queued under the old route. The correct test is not whether every system displayed identical data at the same second. It is whether a consequential action could still proceed from the stale route, whether a stop control caught it, and whether the history explains why earlier approvals were accepted. This case produces concrete verification steps: inspect pending work, disable prospective authority, retain prior evidence, confirm the current owner, and document the interval during which displays disagreed.'
  ]},
  'renewal-assumption-sensitivity-analysis': { heading:'Read a reversal without overstating it', paragraphs:[
    'Suppose the base view treats a procurement questionnaire as a favorable renewal signal. The sensitivity view reclassifies it as process evidence with no directional meaning. If the recommended action changes from routine packet preparation to sponsor confirmation, the analysis has found a decision-sensitive assumption—not evidence that renewal is unlikely. The brief should name the reclassified signal, the missing authorized statement, the deadline affected, and the owner of outreach. It should not hide the reversal by averaging it with unrelated delivery measures, and it should not tell the client that an internal forecast changed.',
    'Now suppose an overdue low-consequence task changes category under several scoring rules but never changes the next accountable action because a commercial confirmation date controls the review. That is a stable decision despite an unstable score. Report both facts. This distinction helps leaders avoid spending effort tuning a dashboard when the useful next step is already clear. It also exposes models that create visible numerical movement without changing decisions. The result is evaluated by traceability and appropriate action, not by whether the final label is positive, negative, or unchanged.',
    'A final challenge removes the strongest favorable and unfavorable signals in turn. This leave-one-signal-out view reveals whether the conclusion is dominated by a single observation whose source, freshness, or authority deserves extra review. Dominance is not automatically a defect: an explicit authorized renewal decision should outweigh weak behavioral indicators. The report must explain that hierarchy. Where no signal dominates and small rule changes repeatedly reverse the action, the honest result is unresolved. Name the next evidence event and review owner instead of converting instability into a confident midpoint.'
  ]},
  'client-commitment-dependency-topology-study': { heading:'Work through a dependency collision', paragraphs:[
    'Imagine a quarterly report promised for Friday. The analyst owns production, yet the report depends on a corrected client roster, an approved metric definition, and access to a source system. The roster and access can proceed in parallel; the metric approval controls interpretation of both. A flat task list may show three overdue subtasks and imply three independent failures. The topology shows one governing decision, one client-provided input, and one access route with different owners and communication needs. That view supports targeted escalation without transferring accountability to the analyst who cannot resolve any of the gates alone.',
    'If the metric decision arrives Thursday, the team must choose among reducing scope, changing the date, or accepting a compressed review. Those are owner decisions, not scheduling chores. The coordinator can show the remaining path, quality checks, client wording, and residual risk for each option. After delivery, the map should retain whether the roster correction still needs propagation and whether temporary access must be removed. This example demonstrates the reader outcome: identify the smallest set of real decisions that makes work feasible while preserving every consequence that survives the headline deadline.',
    'Portfolio review can aggregate dependency types without merging confidential account details. Count how often work waited on source evidence, client confirmation, internal authority, access, or predecessor completion, and show how many networks were only partially visible. A concentration of approval gates may justify an earlier review window; it does not prove approvers caused delay. Likewise, a repeated client-input dependency may indicate an intake design question rather than client failure. The topology keeps these competing explanations available so process changes target interfaces and timing instead of assigning blame from elapsed time alone.'
  ]},
  'service-exception-update-sequence-study': { heading:'Compare two messages at the same stage', paragraphs:[
    'At the first checkpoint, “the issue is resolved and no accounts were affected” may be reassuring but unsafe when monitoring has only recovered and impact review is incomplete. A stronger update says that the observed service has returned, verification continues across the declared window, impact remains under review, and the next approved checkpoint is a stated time. The second message does not sound less committed; it ties each claim to evidence and gives the client a usable expectation. If later review finds impact, the correction follows a visible uncertainty rather than contradicting an unsupported absolute.',
    'At closure, the sequence should answer different questions: what state was restored, what verification was performed, what remains open, who owns follow-up, and when another review occurs. A root-cause document may still be pending without making restoration untrue. Conversely, a completed root-cause draft does not prove service recovery. Keeping those tracks separate prevents a communication team from delaying every update until all analysis ends or declaring closure because one technical signal improved. Reviewers can then test each transition against the evidence appropriate to that stage.',
    'Sequence comparison should use matched exception classes where possible. A data-correction issue, availability interruption, missed reporting window, and access problem require different evidence and recipients. Compare like stages and consequences rather than declaring one team faster because its cases were simpler. Record approvals that intentionally delayed disclosure, unavailable facts, translation or timezone constraints, and client-requested cadence. These qualifications do not excuse a missed commitment; they make the finding interpretable. The strongest output is a stage-specific gap with an owner and correction path, not a league table of message speed.',
    'The review should also test whether approved templates carried stale absolutes, obsolete contacts, or promises that no current owner recognized. Templates can reduce drafting time but are prior text, not current evidence. Every use needs fresh facts, correct recipients, a valid checkpoint, and an accountable approver. Track material edits rather than rewarding verbatim reuse. If a template repeatedly requires the same correction, revise the source through its owner-controlled process and preserve the version date so later reviewers know which language governed each message.'
  ]},
  'crm-correction-propagation-boundary-study': { heading:'Trace one correction through unequal destinations', paragraphs:[
    'Assume a client corrects the effective date of a service change. The CRM field, open implementation task, renewal calendar, monthly report, and archived meeting minutes all contain related dates. The CRM and task require current values; the renewal calendar needs recomputation; the monthly report needs a dated correction note if still in use; the historical minutes should normally preserve what was recorded at the meeting. A blind synchronization would either leave decisions stale or rewrite history. Purpose and consequence determine the action at each destination.',
    'Verification then uses sentinel questions. Does the next implementation step use the corrected date? Does the renewal alert fire from the recomputed window? Can a reviewer see why last month’s report differs? Does search favor a superseded export? Are temporary reconciliation files disposed of through the approved route? These tests examine whether the correction changed operational use while preserving lineage. They also expose visibility limits: a client-held spreadsheet or private download may remain outside the team’s reach and must be reported as an uncertainty, not silently counted as corrected.',
    'Conflicting corrections need quarantine rather than rapid propagation. If two approved-looking sources supply different effective dates, preserve both, stop automated downstream reuse where consequence warrants it, and present the conflict to the accountable source owner. Record the interim value or restricted action that is explicitly authorized. Once resolved, propagate the decision and the reason, not the entire dispute. This prevents a fast synchronization from multiplying uncertainty and gives downstream reviewers enough lineage to understand why their prior view changed.',
    'A propagation review should include negative controls: destinations that must not receive the field. Test whether broad exports, analytics sandboxes, email lists, or shared notes acquired data outside their approved purpose. An accurate value in an unauthorized location is still a control problem. Report over-propagation separately from stale propagation because the remedies differ. One requires minimization, access review, and disposal; the other requires correction, invalidation, or recomputation. Combining them into a single completeness score can reward unsafe copying. Sample both automated and manual paths because a technically governed integration may coexist with recurring spreadsheet exports. Record who can initiate each path, its review trigger, and whether correction notices reach the people who use it. The objective is proportionate control over actual decision use, not an impossible claim that every historical byte has been found.'
  ]}
};

export const research20261002: ResearchPost[] = drafts.map((d) => ({
  slug:d.slug, title:d.title, cluster:d.cluster, excerpt:d.excerpt, hero:d.hero,
  published:'2026-10-02', datePublished:'2026-10-02', updated:'2026-10-02', headlineStat:d.headline,
  statSource:'Topic-specific synthesis of NIST, GAO, FTC, Philippine NPC, and ISO principles',
  takeaways:['Define the decision and evidence boundary before sampling records.','Preserve missing, contrary, corrected, and unresolved cases in the result.','Keep evidence preparation separate from consequential owner judgment.','State limitations, the next review trigger, and what the analysis cannot prove.'],
  sections:[...d.headings.map((heading, i):ResearchSection => ({heading, paragraphs:d.paragraphs[i]})),additionalAnalysis[d.slug]],
  table:{headers:['Control point','Minimum evidence','Boundary'],rows:d.rows}, sources:coreSources,
  researchMethodology:`Bounded, predeclared review for ${d.title}; upstream sampling, explicit missingness, exception analysis, independent recoding, and non-causal conclusions.`,
  externalSources:coreSources.map((s)=>s.url),
  faqs:[{q:'Can this study prove a client or commercial outcome?',a:'No. It evaluates evidence and workflow states in a bounded sample; it cannot establish causality, satisfaction, retention, revenue, compliance, or a guaranteed result.'},{q:'What may an outsourced account specialist do?',a:'They may gather permitted evidence, maintain assigned records, prepare neutral summaries, flag exceptions, and coordinate approved follow-up. Consequential decisions remain with accountable owners.'},{q:'How can another team replicate the review?',a:'Freeze the unit, definitions, cutoff, source hierarchy, eligibility rules, missingness treatment, and independent recoding procedure, then disclose every material method change.'}],
  related:d.related,
  internalLinks:[{label:`Review ${d.service.replaceAll('-',' ')} support`,href:`/services/${d.service}`},{label:'Explore the research library',href:'/research'}]
}));
