import type { ResearchPost } from './research-data';

type Topic = readonly [string, string, 'Hiring Controls' | 'Scope Benchmarks' | 'Workflow Design', string, string, string[]];
const topics: Topic[] = [
  ['account-approval-chain-compression-bias', 'Does shortening an account approval chain improve decision quality?', 'Hiring Controls', 'whether fewer approval steps produce faster, better-supported client decisions or merely hide necessary review', 'compare complete decision histories before and after an approval-path change, preserving consequence, evidence gaps, rework, reversals, and client-facing corrections', [
    'Approval speed needs two clocks. The first runs from a complete evidence packet to an authorized decision. The second starts when the request first arrives and includes time spent discovering missing facts. Collapsing those clocks can make a shortened chain look effective even when coordinators now perform hidden preparation before the official timer begins. Review timestamp rules, rejected packets, and informal pre-approval conversations before interpreting a change.',
    'Decision quality also needs an observable definition. For this study, test whether the approval cites current evidence, stays within the owner\'s authority, answers the original client need, and survives a later verification without correction. A rapid approval that requires reversal is not equivalent to a rapid approval that remains usable. Report rework beside elapsed time rather than folding both into one score.',
    'The outsourced account manager may assemble the packet, identify the required owner, and prepare approved language. The role does not gain authority because a company removes a review step. If the removed reviewer previously supplied legal, security, financial, or contractual judgment, the redesign needs another authorized control. The research conclusion should identify that dependency instead of recommending speed as an end in itself.'
  ]],
  ['client-meeting-to-crm-evidence-decay', 'How quickly does client-meeting evidence lose meaning before it reaches the CRM?', 'Workflow Design', 'how delay and paraphrase between a client meeting and the account record alter commitments, uncertainty, and ownership', 'sample meeting notes, recordings where authorized, follow-up messages, and CRM entries, then trace each material statement through time and classify omissions, additions, changed certainty, and owner assignment', [
    'Use the client statement, not the finished CRM field, as the starting point. Preserve the words available to the account team, the meeting date, the note author, and the first moment the record became available for action. Then map transformations. A request can become a commitment, a tentative date can become a deadline, or an unresolved question can disappear when someone compresses discussion into a status field.',
    'Delay and distortion are related but separate. A same-day entry can still misstate the meeting, while a later entry may be accurate because the owner waited for confirmation. Code elapsed time, fidelity, confirmation status, and operational consequence independently. Ask a second reviewer to reconstruct the CRM entry from the same source material and record where the two versions diverge.',
    'The practical finding should improve capture at the point where meaning is lost. That may require a source excerpt, a confirmation marker, separate decision and action fields, or a rule that unapproved dates remain tentative. It does not justify storing unnecessary recordings or personal data. The accountable owner sets retention and access rules; the account manager records only what the approved workflow requires.'
  ]],
  ['escalation-owner-transfer-integrity', 'What evidence makes an account escalation safe to transfer between owners?', 'Workflow Design', 'whether an escalation retains its facts, authority, client message, and recovery test when responsibility changes', 'follow transferred escalations from the last verified state through acceptance by the new owner, coding missing context, duplicated work, contradictory messages, access gaps, and closure evidence', [
    'Define a transfer as accepted only when the incoming owner can locate the observed impact, current evidence, prior decisions, client-safe status, next check, and closure rule. A reassigned ticket or changed name field shows routing, not comprehension. Test comprehension with a short reconstruction before the incoming owner sends a message or changes the escalation state.',
    'Transfers during absences deserve separate analysis from permanent ownership changes. An interim owner may need narrow authority and a return trigger, while a permanent owner needs durable access and full decision history. Mixing these cases can make a temporary workaround appear to be a complete handoff. Stratify by transfer type, consequence, and whether the client was awaiting an update.',
    'Account support can maintain chronology, prepare a neutral update, and request missing evidence. Technical recovery, contractual remedies, security conclusions, credits, and sensitive client commitments remain with their authorized owners. If those owners change mid-escalation, preserve both the former decision and the new delegation. The conclusion should state which transfers were reproducible and which remained dependent on private memory.'
  ]],
  ['service-scope-exception-recurrence', 'When does a repeated client exception become evidence of scope drift?', 'Scope Benchmarks', 'whether recurring out-of-pattern requests indicate a changed service need, a classification problem, or isolated exceptions', 'construct an event history for repeated exceptions, compare each request with the approved scope version, and code frequency, similarity, consequence, authorization, fulfillment, and client expectation', [
    'Recurrence is not just a count. Two requests can share a label while requiring different work, and several differently labeled requests can express the same underlying need. Freeze a similarity rule before grouping events. Preserve the client wording and approved scope that existed at each date so later contract changes do not rewrite the earlier record.',
    'Test at least three explanations: the client need changed, the team classified ordinary work inconsistently, or an informal accommodation created an expectation. Evidence for one explanation does not automatically authorize a scope change. Report who approved each exception, whether it was described as one-time, and whether the next request referenced the earlier accommodation.',
    'An outsourced account manager can identify recurrence, reconcile records, and prepare the decision history. The commercial owner decides whether to clarify, decline, redesign, or formally change scope. The study should not turn frequency into a pricing recommendation or public claim. Its useful output is a bounded decision packet showing what repeated, why the classification is credible, and what remains uncertain.'
  ]],
  ['client-update-evidence-latency', 'Does evidence latency make a timely client update misleading?', 'Scope Benchmarks', 'how the age of underlying evidence affects the accuracy of routine client status messages', 'compare the evidence cutoff, drafting time, approval time, send time, and later correction for routine and exception updates, while testing what the sender could know at each point', [
    'A message can be sent on schedule and still describe an obsolete state. Measure evidence age at the moment of drafting and again at approval. Record which source controlled the status, whether a newer event was available, and whether the workflow required a refresh. Do not judge the writer using facts that arrived only after the message was sent.',
    'Separate harmless staleness from decision-changing staleness. A minor timestamp difference may leave the meaning intact; a new dependency, owner decision, service event, or client reply may reverse it. Predefine materiality using the action the update supports. Have a second reviewer decide whether the older evidence would change a reasonable reader\'s understanding, then retain disagreements.',
    'The account manager can refresh approved sources, label the cutoff, qualify uncertainty, and route a changed fact for review. The role should not delay every routine note in pursuit of perfect information, nor present an unchecked status as current. A useful conclusion identifies refresh triggers by consequence and names the authorized owner for updates that touch contracts, remediation, security, or commercial commitments.'
  ]],
];

const sources = [
  { name: 'NIST Cybersecurity Framework 2.0', date: 'February 26, 2024', url: 'https://www.nist.gov/publications/cybersecurity-framework-csf-20', note: 'Governance and lifecycle vocabulary, not an account-management performance benchmark.' },
  { name: 'ISO quality management principles', date: 'accessed September 3, 2026', url: 'https://www.iso.org/quality-management/principles', note: 'Customer focus, process, evidence, and improvement principles.' },
  { name: 'NIST accountability glossary', date: 'accessed September 3, 2026', url: 'https://csrc.nist.gov/glossary/term/accountability', note: 'Vocabulary for tracing actions and decisions to responsible entities.' },
  { name: 'FTC Start with Security', date: 'June 2015', url: 'https://www.ftc.gov/business-guidance/resources/start-security-guide-business', note: 'Guidance on access controls, data minimization, and secure operating practices.' },
];

function study([slug, title, cluster, question, method, routeAnalysis]: Topic): ResearchPost {
  return {
    slug, title, cluster, excerpt: `A September 3, 2026 research design examining ${question}.`,
    headlineStat: 'A workflow timestamp or label cannot by itself prove accuracy, authority, cause, or client outcome', statSource: 'Synthesis of NIST, ISO, and FTC control principles',
    published: '2026-09-03', datePublished: '2026-09-03', updated: '2026-09-03',
    takeaways: [`Study ${question} as a record-level question.`, 'Freeze definitions and exclusions before looking at outcomes.', 'Keep facts, analysis, authority, communication, and verification separate.', 'Use a second reviewer to test whether the evidence supports the same finding.'],
    sections: [
      { heading: 'Research question and evidence boundary', paragraphs: [`Published September 3, 2026. This report asks ${title.toLowerCase()} The question concerns outsourced account-management records and the decisions they support. It does not evaluate a named worker or promise a client result.`, `The evidence boundary is a dated account-work record at a defined decision point. State what the study may change, such as a field definition, approval route, refresh trigger, or handoff test. Retention, revenue, satisfaction, and individual performance remain outside the conclusion unless a separate design measures them.`] },
      { heading: 'Population and selection', paragraphs: [`Define the eligible period, account population, workflow states, inclusion rule, exclusion rule, denominator, and source hierarchy before sampling. Include routine, disputed, corrected, returned, reopened, and apparently successful records so selection does not favor a clean process story.`, `Stratify cases when consequence, channel, contract, owner type, or source system could change the interpretation. Preserve each exclusion and count unavailable records. Missing evidence is a finding when the operating rule required that evidence to exist.`] },
      { heading: 'Methodology', paragraphs: [`The route-specific procedure is to ${method}. Freeze the coding guide before inspecting final outcomes. For every record retain source, timestamp, observed fact, uncertainty, work owner, decision owner, client consequence, communication state, verification rule, and any later correction.`, `Give an independent reviewer the same frozen inputs without the first conclusion. Classify disagreement as an unclear definition, missing source, inaccessible evidence, stale ownership, authority ambiguity, or genuine judgment. Agreement shows that the procedure is reproducible; it does not prove that the preferred interpretation caused an outcome.`] },
      { heading: 'Route-specific analysis', paragraphs: routeAnalysis },
      { heading: 'Facts, analysis, and competing explanations', paragraphs: [`Report direct observations in a separate field from interpretations. A timestamp, source value, recorded message, or documented owner action may be observed. Why it occurred, what it means for the account, and what should change are analyses that require stated reasoning and authority.`, `List plausible alternatives beside the preferred explanation and name the evidence that would distinguish them. Sequence alone cannot prove cause. Client dependency, careful approval, access limits, source correction, tool behavior, and internal delay may produce a similar visible pattern.`] },
      { heading: 'Privacy and role boundaries', paragraphs: [`Use the minimum client information required for this question. Work in approved systems, restrict row-level access, and aggregate findings when individual detail is unnecessary. Research access does not authorize exports, new retention, broad administration, or disclosure.`, `An outsourced account manager may collect facts, maintain assigned records, prepare analysis, and route a decision. Contract, financial, legal, security, privacy, access, and unapproved service-scope decisions stay with authorized owners. The report must keep that boundary visible.`] },
      { heading: 'Limitations', paragraphs: [`A local sample may omit calls, private messages, inaccessible client systems, or work that was never documented. Account size, contract wording, tool configuration, geography, staffing, and stakeholder availability can limit transfer to another portfolio. A second reviewer may also share the same mistaken assumption.`, `This design describes evidence patterns under stated rules. It cannot establish a universal threshold, guarantee an improvement, or attribute a commercial outcome to account support. Report small samples, missingness, disagreements, and later corrections beside the result.`] },
      { heading: 'Evidence-led conclusion', paragraphs: [`The bounded conclusion is that ${question} should be judged from preserved source evidence, timing, consequence, ownership, and verification rather than from a convenient status label. Where the record is incomplete, the defensible result is an evidence gap with a named recheck.`, `Any operating change should name its owner, effective date, expected evidence, review point, and rollback condition. Re-measure it with the same definitions. That gives agencies and B2B account teams a testable control without expanding the outsourced role beyond its approved authority.`] },
    ],
    table: { headers: ['Research layer', 'Required record', 'Boundary'], rows: [['Design', 'Question, unit, population, period', 'Not an outcome claim'], ['Evidence', 'Source, date, fact, missingness', 'Not a causal explanation'], ['Review', 'Independent coding and disagreement', 'Agreement is not proof'], ['Decision', 'Owner, action, recheck, rollback', 'Research does not confer authority']] },
    sources, faqs: [{ q: 'What should the study define first?', a: 'Define the decision, eligible records, source hierarchy, and evidence cutoff before reviewing outcomes.' }, { q: 'Why preserve disagreement?', a: 'Disagreement reveals where definitions, sources, or authority are not yet reproducible.' }, { q: 'What may the account manager decide?', a: 'The role may act only within approved routine authority and must route consequential commercial, legal, security, privacy, access, or scope decisions.' }],
    related: topics.filter(t => t[0] !== slug).slice(0, 2).map(t => t[0]), internalLinks: [{ label: 'See account reporting support', href: '/services/account-reporting' }, { label: 'Review client request routing support', href: '/services/client-request-routing' }],
  };
}

export const research20260903: ResearchPost[] = topics.map(study);
