import type { ResearchPost } from './research-data';

const checked = 'checked September 22, 2026';
const sources = [
  { name: 'NIST Cybersecurity Framework 2.0', date: `February 26, 2024; ${checked}`, url: 'https://www.nist.gov/cyberframework', note: 'Primary risk-management framework used for governance, identification, protection, detection, response, and recovery vocabulary; it is not an account-management benchmark.' },
  { name: 'NIST SP 800-53 Rev. 5, Release 5.2.0', date: `August 27, 2025; ${checked}`, url: 'https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final', note: 'Primary control catalog used for access, audit, information integrity, assessment, and accountability concepts. Controls require local tailoring.' },
  { name: 'GAO Standards for Internal Control in the Federal Government', date: `May 15, 2025; ${checked}`, url: 'https://www.gao.gov/products/gao-25-107721', note: 'Current authoritative framework for preventive controls, quality information, risk assessment, monitoring, and change documentation; private teams are not represented as subject to federal requirements.' },
  { name: 'FTC Start with Security: A Guide for Business', date: `June 2015; ${checked}`, url: 'https://www.ftc.gov/business-guidance/resources/start-security-guide-business', note: 'Authoritative practical guidance on data minimization, sensible access, service-provider oversight, retention, and secure information handling.' },
  { name: 'Philippine National Privacy Commission: Data Privacy Act of 2012', date: checked, url: 'https://privacy.gov.ph/data-privacy-act/', note: 'Primary Philippine legal source for personal-information context. Applicability and legal decisions remain with qualified accountable owners.' },
  { name: 'ISO quality management principles', date: checked, url: 'https://www.iso.org/quality-management/principles', note: 'Authoritative overview of process, improvement, customer focus, relationship management, and evidence-based decision-making principles.' },
];

type Topic = { slug:string; title:string; cluster:string; excerpt:string; hero:string; question:string; unit:string; comparison:string; service:string; decision:string; risk:string; design:string; rows:string[][]; related:string[] };
const topics: Topic[] = [
  { slug:'client-meeting-decision-traceability-study', title:'Can client meeting decisions be traced after the call?', cluster:'Workflow Design', excerpt:'A bounded study of whether account teams can reconstruct a client-meeting decision from source wording through owner approval and the next verified action.', hero:'/research-heroes/2026-09-22-meeting-decision-traceability.png', question:'whether a later reviewer can distinguish discussion, recommendation, decision, commitment, and completed action after a client meeting', unit:'one consequential statement recorded during or immediately after an approved client meeting', comparison:'confirmed decisions, pending recommendations, disputed notes, superseded decisions, and statements incorrectly treated as commitments', service:'customer-qbr-preparation', decision:'meeting-decision capture and follow-through', risk:'A polished set of minutes can erase qualifications such as “subject to review” or assign authority to the loudest attendee. Attendance does not prove decision rights, and silence does not prove agreement.', design:'Freeze the meeting record before inspecting later outcomes. Trace the recording or approved notes, exact statement, speaker, meeting time, authority source, confirmation, affected work, and closure evidence. Ask a second reviewer to classify the statement without seeing the first label.', rows:[['Discussion','Source wording and speaker','No action implied'],['Recommendation','Option and accountable reviewer','Not an approval'],['Decision','Authority, effective date, scope','Route affected work'],['Verified action','Completion and acceptance evidence','Close only stated condition']], related:['client-conversation-thread-continuity','qbr-evidence-claim-reproducibility'] },
  { slug:'qbr-metric-denominator-integrity-analysis', title:'Does the QBR metric use the right denominator?', cluster:'Scope Benchmarks', excerpt:'A reproducible analysis of included, excluded, missing, and ineligible account records behind a client-review percentage.', hero:'/research-heroes/2026-09-22-qbr-denominator-integrity.png', question:'whether a QBR percentage remains decision-useful when every eligible, excluded, missing, and late record is made visible', unit:'one metric claim tied to its population, inclusion rule, period, numerator, denominator, and source extract', comparison:'reported results under the approved denominator, all eligible records, complete-record-only filtering, and plausible missing-data scenarios', service:'customer-qbr-preparation', decision:'QBR metric definition and presentation', risk:'A completion rate can rise when incomplete records disappear from the denominator. Mixing opened, due, closed, canceled, and carried-over items can produce a precise number that answers no stable question.', design:'Recompute each sampled claim from a frozen source extract. Record eligibility before outcome, retain exclusions with reasons, separate unknown from zero, and test how the result changes under disclosed alternatives. Reviewers should reproduce both counts independently.', rows:[['Population','Account scope and period','Set before outcomes'],['Numerator','Qualified event and source','No proxy substitution'],['Denominator','Eligible records and exclusions','Show missingness'],['Sensitivity','Alternative justified rules','Do not select preferred result']], related:['qbr-evidence-claim-reproducibility','outsourced-account-portfolio-sampling-visibility'] },
  { slug:'crm-contact-identity-collision-research', title:'When do two CRM contacts represent the same person?', cluster:'Hiring Controls', excerpt:'A privacy-aware method for resolving CRM identity collisions without silently merging distinct people, roles, permissions, or histories.', hero:'/research-heroes/2026-09-22-crm-identity-collision.png', question:'which evidence is sufficient to resolve two similar contact records while preserving authority, consent, history, and reversibility', unit:'one suspected identity collision between two CRM contact or stakeholder records', comparison:'confirmed duplicates, distinct people, role aliases, shared inboxes, renamed organizations, stale records, and unresolved collisions', service:'crm-account-maintenance', decision:'CRM identity resolution and controlled merge', risk:'Matching names, domains, phone numbers, or titles are clues rather than identity proof. A false merge can expose one contact’s history to another, alter an approval path, or destroy provenance.', design:'Sample collisions before merging. Compare independent identifiers only where approved, direct confirmation, account context, role history, permissions, source system, conflicting facts, and downstream references. Require an authorized reviewer for high-consequence merges and keep a reversible lineage record.', rows:[['Suspected collision','Matched and conflicting fields','Do not merge'],['Verified distinct','Evidence and separation note','Protect both histories'],['Verified duplicate','Authority and survivor rule','Preserve lineage'],['Unresolved','Owner, restriction, next check','Limit downstream use']], related:['client-contact-data-freshness','account-stakeholder-role-change-detection'] },
  { slug:'client-escalation-stage-latency-study', title:'Where does client escalation time actually accumulate?', cluster:'Scope Benchmarks', excerpt:'A stage-by-stage latency study separating intake, preparation, acknowledgment, owner decision, client response, and verified resolution.', hero:'/research-heroes/2026-09-22-escalation-stage-latency.png', question:'where elapsed time accumulates across an escalation without confusing a fast acknowledgment with a resolved client issue', unit:'one escalation episode from the first retained signal to its stated verified close condition', comparison:'routine and high-consequence episodes by intake delay, evidence preparation, routing, owner review, client waiting, action, and acceptance', service:'escalation-coordination', decision:'escalation routing, status wording, and review attention', risk:'One end-to-end duration hides who or what the work was waiting for. It can unfairly label a support role, conceal an incomplete packet, or treat client review as internal delay.', design:'Define stage-entry and stage-exit events before sampling. Preserve clock pauses, time zones, reopened states, priority changes, and missing timestamps. Compare medians and distributions only when the sample supports them; otherwise report case counts and observed ranges without inventing a target.', rows:[['Intake','First source and qualification','Signal is not yet routed'],['Preparation','Evidence-ready timestamp','Separate missing inputs'],['Decision','Owner receipt and decision','Support role cannot decide'],['Resolution','Action plus acceptance rule','Acknowledgment is not closure']], related:['client-approval-latency-interpretation','client-request-consequence-calibration'] },
  { slug:'client-feedback-response-coverage-study', title:'Whose client feedback reaches the account review?', cluster:'Workflow Design', excerpt:'A sampling study of whether client feedback coverage overrepresents scheduled meetings, vocal contacts, positive replies, or easy-to-code channels.', hero:'/research-heroes/2026-09-22-feedback-response-coverage.png', question:'which client feedback is visible to the account review and which eligible voices, channels, periods, or nonresponses are absent', unit:'one feedback opportunity or retained client statement linked to an account, stakeholder role, channel, and observation window', comparison:'scheduled and unsolicited feedback, responses and nonresponses, positive and critical statements, direct and relayed sources, and accessible versus unavailable channels', service:'customer-feedback-administration', decision:'feedback sampling, summary wording, and follow-up', risk:'A tidy feedback summary may reflect who answered, which channel was searchable, or what was easy to code. Nonresponse is not satisfaction, and one stakeholder cannot automatically represent the account.', design:'Define eligible feedback opportunities before reading sentiment. Preserve exact wording and context, code nonresponse separately, stratify by stakeholder role and channel where permitted, and blind a second reviewer to the desired account label. Report coverage counts beside themes.', rows:[['Eligible opportunity','Account, role, channel, window','Defines coverage'],['Retained response','Exact source and context','Do not inflate reach'],['Nonresponse','Attempt and permitted follow-up','No sentiment inference'],['Theme','Count, contrary cases, uncertainty','Owner approves action']], related:['client-feedback-response-consistency-study','outsourced-account-portfolio-sampling-visibility'] },
];

const sections = (t:Topic) => [
  { heading:'Research question and decision boundary', paragraphs:[`This study asks ${t.question}. The unit is ${t.unit}. That boundary prevents an account label from replacing the actual evidence. The intended decision is ${t.decision}; the study does not grade an employee, infer client sentiment, establish legal compliance, or promise retention, revenue, response time, or service quality.`, `Facts, interpretations, and decisions are recorded separately. A Philippines-based account specialist may gather permitted sources, normalize fields, prepare a neutral brief, flag exceptions, and coordinate an approved follow-up. Contract, pricing, refund, legal, privacy, security, access, scope, and sensitive client-commitment decisions remain with the accountable owner.`] },
  { heading:'Why the apparent signal can mislead', paragraphs:[t.risk, `The practical safeguard is a claim ledger: source, observed fact, interpretation, uncertainty, authority, affected account work, owner, and next check. “Sent,” “discussed,” “green,” “urgent,” and “complete” are not self-proving states. Each needs a written definition and evidence appropriate to the decision consequence.`] },
  { heading:'Methodology and sampling plan', paragraphs:[t.design, `Use the comparison: ${t.comparison}. Include routine, incomplete, corrected, disputed, missing, and reopened examples. Set the observation window, population, inclusion and exclusion rules, source hierarchy, and stopping rule before reviewing outcomes. Keep unavailable evidence unavailable rather than reconstructing it from memory.`, `Have two reviewers independently code a meaningful subset with the same rubric. Preserve disagreements by field. Agreement supports reproducibility under this protocol, not objective truth; disagreement may expose an unclear definition, inaccessible source, or authority boundary. Retain negative cases and disclose changes before a later replication.`] },
  { heading:'Evidence, privacy, and authority controls', paragraphs:[`Rank sources by authority, specificity, relevance, and freshness for the particular claim. A newer informal note may not override an approved record, while a direct authorized correction may supersede an older field. Preserve both the former and current state, who changed it, the effective date, and why. Do not average incompatible evidence into certainty.`, `Apply data minimization and least privilege throughout. Review only approved systems and fields, avoid copying personal information into working papers, restrict exports, and use named accounts. When evidence is inaccessible, record the limitation and owner. The Data Privacy Act and FTC guidance provide context, but qualified owners must determine obligations and approved handling for the actual client.`] },
  { heading:'Analysis and reporting', paragraphs:[`Report counts, denominators, exclusions, missing fields, state transitions, contradictory cases, and reviewer disagreements before summarizing a pattern. Distinguish description from inference. If one state appears more often in the sample, say exactly that; do not claim it caused delay, satisfaction, churn, or a commercial result.`, `A client-safe brief should state the strongest supported observation, the material uncertainty, the accountable decision, the permitted next action, and the review trigger. Comparisons across accounts require stable definitions and comparable visibility. Where those conditions fail, publish separate case findings rather than a misleading pooled rate.`] },
  { heading:'Framework interpretation', paragraphs:[`NIST CSF 2.0 offers governance and risk-management outcomes; SP 800-53 supplies adaptable control language for access, audit, assessment, and information integrity. GAO’s 2025 Green Book emphasizes preventive controls, quality information, monitoring, and documented change assessment. FTC guidance supports minimization, sensible access, retention discipline, and service-provider oversight. ISO principles support process and evidence-based decisions.`, `None of these sources sets an outsourced-account-management staffing ratio, service level, workflow duration, or performance benchmark. They do not prove that this method improves a client outcome. The buyer’s contracts, policies, system rules, approved procedures, and named decision rights govern. Framework language should clarify a control, never manufacture authority.`] },
  { heading:'Limitations and replication', paragraphs:[`Material limits include small or convenience samples, inaccessible channels, informal decisions, inconsistent clocks, different contracts, holidays, geography, tool configuration, stakeholder availability, survivorship in retained records, and reviewer knowledge of outcomes. Public findings must not reveal client-confidential or personal data.`, `A later team can replicate the study by freezing the same definitions, selecting a new period without inspecting results, recoding a subset independently, reporting missingness, and documenting every method change. The narrow conclusion is that ${t.decision} becomes more reviewable when source, definition, authority, uncertainty, owner, and verification remain connected. That is an operating-control finding, not a guarantee.`] },
];

export const research20260922: ResearchPost[] = topics.map(t => ({
  slug:t.slug, title:t.title, cluster:t.cluster, excerpt:t.excerpt, hero:t.hero,
  published:'2026-09-23', datePublished:'2026-09-23', updated:'2026-09-23',
  headlineStat:'Seven evidence fields connect a source to a reviewable account decision', statSource:'Route-specific synthesis of NIST, GAO, FTC, NPC, and ISO control principles',
  takeaways:['Define the population, unit, state, authority, and comparison before inspecting outcomes.','Preserve missing, contradictory, corrected, and reopened records.','Keep evidence preparation with the support role and consequential judgment with the accountable owner.','Require a dated next check or acceptance condition before claiming closure.'],
  sections:sections(t), table:{headers:['Evidence state','Minimum record','Boundary'],rows:t.rows}, sources,
  researchMethodology:`Fixed-window review of ${t.unit}; frozen definitions and sources; explicit missingness; independent recoding; sensitivity checks; bounded conclusions.`, externalSources:sources.map(s=>s.url),
  faqs:[{q:'Can this study prove a client outcome?',a:'No. It describes evidence and workflow state in a bounded sample; it cannot prove causality, satisfaction, retention, revenue, or a guaranteed result.'},{q:'What may the outsourced specialist do?',a:'They may gather permitted evidence, maintain assigned records, prepare neutral summaries, flag exceptions, and coordinate approved follow-up. Consequential decisions stay with accountable owners.'},{q:'How should another team replicate it?',a:'Freeze definitions and the observation window, retain missing and contrary cases, independently recode a subset, report exclusions, and disclose every method change.'}],
  related:t.related, internalLinks:[{label:`Review ${t.service.replaceAll('-',' ')} support`,href:`/services/${t.service}`},{label:'Explore the research library',href:'/research'}],
}));
