import type { ResearchPost, ResearchSection } from './research-data';

const checked = 'checked September 28, 2026';
const sources = [
  { name: 'NIST Cybersecurity Framework 2.0', date: `February 26, 2024; ${checked}`, url: 'https://www.nist.gov/cyberframework', note: 'Primary risk-management framework used for governance, identification, protection, response, and recovery concepts. It does not set account-management service levels.' },
  { name: 'NIST SP 800-53 Rev. 5, Release 5.2.0', date: `August 27, 2025; ${checked}`, url: 'https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final', note: 'Primary control catalog used for access, audit, information integrity, accountability, and monitoring concepts; organizations must tailor controls.' },
  { name: 'GAO Standards for Internal Control in the Federal Government', date: `May 15, 2025; ${checked}`, url: 'https://www.gao.gov/products/gao-25-107721', note: 'Authoritative source for quality information, control activities, segregation of duties, monitoring, and remediation. No private-company compliance claim is made.' },
  { name: 'FTC Start with Security: A Guide for Business', date: `June 2015; ${checked}`, url: 'https://www.ftc.gov/business-guidance/resources/start-security-guide-business', note: 'Authoritative business guidance on data minimization, access, service-provider oversight, retention, and secure handling.' },
  { name: 'Philippine National Privacy Commission: Data Privacy Act of 2012', date: checked, url: 'https://privacy.gov.ph/data-privacy-act/', note: 'Primary Philippine legal source for personal-information context. Qualified owners must determine applicability and required handling.' },
  { name: 'ISO quality management principles', date: checked, url: 'https://www.iso.org/quality-management/principles', note: 'Authoritative overview of customer focus, process approach, improvement, relationship management, and evidence-based decisions.' },
];

type Topic = {
  slug: string; title: string; cluster: string; excerpt: string; hero: string; service: string;
  unit: string; decision: string; hypothesis: string; unique: ResearchSection[]; rows: string[][]; related: string[];
};

const topics: Topic[] = [
  {
    slug: 'client-stakeholder-authority-drift-study', title: 'When a client stakeholder’s authority changes before the account record does', cluster: 'Hiring Controls',
    excerpt: 'A bounded study of role evidence, decision rights, communication routes, stale stakeholder maps, and accountable confirmation.', hero: '/research-heroes/2026-09-24-owner-continuity.png', service: 'crm-account-maintenance',
    unit: 'one material client instruction or approval linked to the stakeholder identity, stated role, governing source, and effective date', decision: 'whether the instruction can be processed, needs confirmation, or must be routed to the accountable relationship owner', hypothesis: 'role labels and meeting attendance are weak substitutes for current, decision-specific authority', related: ['crm-ownership-ambiguity-study','client-relationship-owner-continuity-study'],
    rows: [['Identity','Person, organization, verified channel','A familiar sender is not proof of authority'],['Authority','Decision type, source, effective date','Job title alone may be insufficient'],['Conflict','Contrary record and consequence','Do not silently choose a source'],['Resolution','Owner confirmation and downstream update','Preserve the superseded state']],
    unique: [
      { heading: 'The stakeholder map is a claim, not a fact forever', paragraphs: [
        'Account teams often inherit a stakeholder map that looks definitive: sponsor, administrator, approver, billing contact, technical contact, and executive owner. Each label is a dated claim about a relationship and a class of decisions. A promotion, leave, reorganization, acquisition, project transition, or informal delegation can change the real route before the CRM is corrected. The research question is not whether a contact is important. It is whether approved evidence supports that person acting on this particular instruction at this particular time.',
        'Authority drift can move in both directions. Someone may gain responsibility but remain absent from the account record, causing avoidable delay. Someone else may remain listed after losing approval rights, creating a risk that a well-intended specialist treats familiarity as authorization. A safe process does not accuse the contact or freeze routine communication. It distinguishes receiving a message, preparing work, changing a record, and approving a consequential outcome.'
      ]},
      { heading: 'Build an authority-event timeline', paragraphs: [
        'For each sampled instruction, trace the most recent approved stakeholder source, the instruction channel, the decision requested, the role asserted, any contrary evidence, and the eventual confirmation. Record both event time and record-update time. The interval between them is the observable drift window; it is not automatically an error because a valid change may be awaiting documentation. Classify planned transfers, temporary delegations, emergency contacts, permanent role changes, disputed instructions, and messages where authority was simply not relevant.',
        'The source hierarchy must be decision-specific. An approved client notice may control routing, while a signed agreement or designated owner may control a commercial change. A calendar invitation can show participation but rarely proves approval rights. A forwarded message may preserve wording while obscuring who authorized it. Reviewers should code the exact support for the authority claim instead of awarding confidence because several weak records repeat the same title.'
      ]},
      { heading: 'Test downstream propagation rather than CRM neatness', paragraphs: [
        'A corrected contact field is only one step. Study whether the change reached the approval matrix, distribution list, meeting cadence, escalation route, billing workflow, access review, renewal plan, and open decision queue where relevant. Propagation should be limited to approved systems and purposes; copying personal details everywhere is not a control. The useful measure is whether affected decision routes were identified, assigned, updated, and verified without erasing the history needed to explain earlier actions.',
        'Include a contrary-case review. Look for instructions that were properly confirmed even though the CRM was stale, and for immaculate stakeholder records that still lacked decision-specific authority. Those cases prevent the study from equating data completeness with authorization. Report unavailable client-side evidence as a limitation. An outsourced account specialist can surface the conflict and prepare a confirmation request, but should not infer a client governance structure from silence.'
      ]},
      { heading: 'Operating conclusion for account teams', paragraphs: [
        'The defensible conclusion is narrow: stakeholder authority is usable when identity, decision class, governing source, effective date, and confirmation path agree. Where they do not, the account record should show the unresolved conflict, the permitted interim action, and the accountable owner. Routine acknowledgements can continue under approved language while a consequential request waits for confirmation. That separation protects responsiveness without turning speed into unauthorized acceptance.',
        'A recurring review should be triggered by observed change events, not only an annual cleanup. Useful triggers include returned mail, changed domains, new meeting owners, revised signatures, explicit delegation, prolonged absence, account transition, or conflicting approval behavior. These signals justify checking the record; they do not prove a change. The final authority decision belongs to the designated owners on both sides of the relationship.'
      ]},
    ],
  },
  {
    slug: 'renewal-notice-evidence-chain-research', title: 'Can an account team prove a renewal notice reached the right decision route?', cluster: 'Scope Benchmarks',
    excerpt: 'A delivery-and-decision study separating notice preparation, authorized sending, technical delivery, receipt, routing, response, and renewal choice.', hero: '/research-heroes/2026-08-21-renewal-cutoff.png', service: 'renewal-administration',
    unit: 'one renewal-related notice tied to an agreement, required window, approved recipient route, sending event, and resulting decision state', decision: 'whether the renewal record supports follow-up, escalation, correction, or continued waiting without pretending a commercial decision has occurred', hypothesis: 'a sent timestamp does not by itself establish delivery, receipt by an authorized stakeholder, comprehension, or a renewal decision', related: ['renewal-decision-cutoff-bias-study','renewal-risk-signal-disagreement'],
    rows: [['Requirement','Agreement, window, recipient rule','Do not invent a notice obligation'],['Send','Approved copy, actor, channel, timestamp','Drafted is not sent'],['Delivery','Platform evidence and exception','Delivered is not understood'],['Decision','Authorized response or open state','Silence is not acceptance']],
    unique: [
      { heading: 'Separate the six states hidden inside “notice sent”', paragraphs: [
        'Renewal operations compress several events into one phrase. A notice can be drafted, approved, sent, technically accepted by a system, received by a person, routed to an authorized decision maker, and answered. Those states matter differently. A CRM task closed after sending proves an operator action, not the recipient’s authority or the client’s decision. This study follows the evidence chain without interpreting contract language or asserting that any particular form of delivery satisfies a legal obligation.',
        'The controlling source comes first: the approved agreement, amendment, client instruction, or internal policy as identified by the accountable owner. Extract the stated window, channel, address or recipient rule, required content, and owner. If the source is ambiguous, the record should say so and route the question. An outsourced specialist may calendar dates and assemble the packet, but should not decide what the contract requires.'
      ]},
      { heading: 'Design a delivery study around observable transitions', paragraphs: [
        'Select notices from the eligible renewal population, including routine deliveries, bounced messages, changed contacts, portal submissions, corrected notices, disputed receipt, and still-open cases. For each, preserve the approved final copy, approval evidence, sending identity, channel, timestamp, timezone, destination, platform response, later correction, follow-up, and client response. A screenshot without message identity or time may be useful context but is not a complete event record.',
        'Do not collapse technical delivery and human receipt. Email acceptance can coexist with an abandoned mailbox; a portal upload can coexist with no authorized viewer; a meeting mention can coexist with no approved written notice. Conversely, a client response can prove practical receipt even when the original system log is unavailable. Code each state separately and state which inference, if any, the accountable owner approved.'
      ]},
      { heading: 'Measure exceptions without manufacturing a success rate', paragraphs: [
        'Useful counts include eligible renewals, notices required by the selected rule, notices approved, sends attempted, technical exceptions, recipient changes, authority questions, responses, and unresolved cases at the cutoff. The denominators differ. Reporting “98 percent sent” does not answer whether the population was complete or whether open delivery exceptions were resolved. Preserve late evidence and reruns as dated sensitivity views rather than rewriting the original cutoff.',
        'Compare exception handling by cause: invalid destination, absent stakeholder, channel failure, missing approval, ambiguous source, corrected content, or client-requested routing. The study should describe the observed handling path, not declare legal sufficiency. Any claim about timeliness also needs the local timezone, business calendar, start event, endpoint, and treatment of weekends or holidays supplied by the governing process.'
      ]},
      { heading: 'Keep follow-up distinct from the renewal decision', paragraphs: [
        'A follow-up plan can specify the next approved channel, owner, date, wording boundary, and escalation condition. It cannot treat silence as acceptance, rejection, satisfaction, or intent unless a qualified owner identifies an applicable controlling rule. The account specialist’s value is maintaining the evidence chain and making the unresolved state visible before a deadline, not negotiating terms or pressuring a contact outside the approved relationship route.',
        'The narrow conclusion is that renewal administration becomes reviewable when requirement, approved content, send event, delivery evidence, authorized recipient route, response, and open uncertainty remain distinct. Replication should use a later renewal cohort and the same event definitions. Changes to agreements, channels, client instructions, or time rules require a new stratum rather than a misleading comparison with unlike records.'
      ]},
    ],
  },
  {
    slug: 'client-escalation-audience-sequencing-analysis', title: 'Who should learn about a client escalation, and in what order?', cluster: 'Workflow Design',
    excerpt: 'An audience-sequencing analysis of minimum necessary context, parallel alerts, approval gates, client updates, and information leakage.', hero: '/research-heroes/2026-09-22-escalation-stage-latency.png', service: 'escalation-coordination',
    unit: 'one escalation episode represented as a sequence of notices, recipients, purposes, approvals, factual updates, and closure communications', decision: 'whether the escalation route gave each audience timely decision-relevant information without oversharing or bypassing accountable owners', hypothesis: 'adding recipients may increase visibility while decreasing clarity, privacy, ownership, and the reliability of client-facing updates', related: ['client-escalation-acknowledgment-standard','escalation-stage-latency-research'],
    rows: [['Trigger','Observed condition and severity rule','Concern is not yet a conclusion'],['Audience','Recipient, purpose, minimum context','Visibility is not authority'],['Sequence','Parallel or ordered notice with reason','Fastest is not always safest'],['Closure','Resolution owner and approved update','Internal close may not close client impact']],
    unique: [
      { heading: 'Escalation has an information architecture', paragraphs: [
        'An escalation is not one message copied to everyone. Technical responders may need reproduction details; relationship owners may need client impact and communication timing; legal, privacy, security, finance, or leadership owners may need different evidence depending on the trigger. The client needs accurate, approved, useful information without internal speculation. This analysis asks whether each audience received the minimum context needed for its task at the right stage.',
        'Sequence can be ordered, parallel, or conditional. A credible immediate safety or security concern may use a predefined urgent route. A routine service exception may first need fact verification and an accountable communication owner. The study does not invent severity or notification duties. It tests episodes against the company’s approved matrix and records where the matrix was missing, ambiguous, or overridden by an authorized owner.'
      ]},
      { heading: 'Reconstruct the episode message by message', paragraphs: [
        'Create a timeline from the first observable trigger through triage, owner acceptance, investigation, client acknowledgement, material updates, decision, recovery, and closure. For every communication, record sender, recipients, timestamp, purpose, source facts, inference labels, requested action, approval status, sensitivity, and the next expected update. Use message identifiers or approved record links rather than copying sensitive content into the study dataset.',
        'Mark audience changes explicitly. A distribution expands when a new expertise or decision need appears; it contracts when sensitive detail no longer serves a purpose. Blind forwarding can expose unrelated client information or obsolete speculation. Private side conversations can also hide a decision from the operational record. Neither a larger nor smaller audience is inherently correct. The test is whether purpose, authority, and information need explain the choice.'
      ]},
      { heading: 'Evaluate timing without rewarding premature certainty', paragraphs: [
        'Measure elapsed time between the trigger, acknowledgement, accountable acceptance, first approved client update, material change, and closure, but keep the endpoints separate. A rapid internal broadcast can precede owner acceptance. A fast client message can be harmful if it states an unsupported cause or resolution. Report both timeliness and evidence quality, including corrections, conflicting updates, missed recipients, unnecessary recipients, and waits caused by a named decision dependency.',
        'Review at least one ordinary, high-consequence, ambiguous, corrected, and reopened episode where available. Independent reviewers should code whether each message contained observed facts, analysis, inference, decision, or commitment. Disagreement is useful: it may reveal that an update blended categories or that the severity matrix lacks a workable definition. Resolve the process question prospectively; do not rewrite the historical message.'
      ]},
      { heading: 'Design a bounded coordination record', paragraphs: [
        'A practical record names the active stage, accountable owner, permitted recipients, restricted detail, client communication owner, latest verified fact, open question, next update condition, and closure test. It should allow an account specialist to coordinate logistics and evidence while reserving consequential judgments for qualified owners. Access to the record follows least privilege; escalation urgency does not authorize uncontrolled exports or permanent broad access.',
        'The bounded conclusion is that escalation sequencing works when recipient purpose, minimum context, timing, approval, and next action can be reconstructed. The method cannot prove that a different sequence would have prevented harm or improved satisfaction. It can reveal unsupported statements, owner gaps, unnecessary exposure, duplicated requests, and silent stages that deserve an accountable redesign.'
      ]},
    ],
  },
  {
    slug: 'account-priority-override-outcome-study', title: 'What happens after an account priority is overridden?', cluster: 'Scope Benchmarks',
    excerpt: 'A queue study tracing override authority, displaced work, expiry, reassessment, downstream commitments, and visible tradeoffs.', hero: '/research-heroes/2026-09-24-sampling-bias.png', service: 'account-health-monitoring',
    unit: 'one authorized change to the order of two or more account-work items, including the promoted item and every materially displaced commitment', decision: 'whether an override remains justified, should expire, or needs capacity and client-commitment review by the accountable owner', hypothesis: 'priority changes are incompletely understood when teams record only the promoted request and not the work, evidence, and promises displaced', related: ['account-priority-review-routine','account-portfolio-capacity-review'],
    rows: [['Baseline','Queue order and rule before change','Reconstruct the actual alternative'],['Override','Reason, authority, timestamp, expiry','Urgent language is not approval'],['Displacement','Affected work, owner, commitment','Cost may cross accounts'],['Review','Outcome, residual work, reassessment','Completion does not validate the override']],
    unique: [
      { heading: 'Study the counterfactual queue, not only the urgent item', paragraphs: [
        'Priority overrides are visible at the top of a queue and nearly invisible below it. A promoted request can be completed successfully while an account review, promised update, renewal preparation, data correction, or follow-up is delayed. The correct unit therefore includes both the override and displaced work. The research does not judge which client matters more. It tests whether the decision, authority, tradeoff, and review condition were recorded before the original queue disappeared.',
        'Freeze the pre-override snapshot: eligible items, current rank, due conditions, consequence categories, work owners, dependencies, and existing commitments. Then record the trigger, evidence available at the time, person requesting the change, authorized decision owner, affected capacity, expected duration, and expiry. A later good outcome cannot substitute for contemporaneous reasoning because hindsight hides the uncertainty under which the choice was made.'
      ]},
      { heading: 'Trace displaced work through its actual consequences', paragraphs: [
        'For each materially displaced item, follow status changes, reassignment, missed review windows, client-safe updates, rework, escalation, completion, cancellation, and unresolved residue. Do not assume that a date movement caused harm. A low-consequence task may move safely, or a client may approve a revised date. Conversely, unchanged due dates can hide compressed work, after-hours effort, quality risk, or a second unrecorded override. State only what the records support.',
        'Separate direct displacement from shared dependencies. A specialist moved to an urgent request is a direct capacity change. A delayed approval, unavailable source, or system outage may affect both tasks independently. The analysis should retain competing explanations and avoid attributing every later exception to the override. A small matched comparison with similar non-overridden items can inform questions, but observational records do not establish causality.'
      ]},
      { heading: 'Test override expiry and queue restoration', paragraphs: [
        'An override should have a review trigger: completion, elapsed time, new evidence, capacity change, risk reduction, or accountable cancellation. Without it, temporary urgency can become the new queue by inertia. Study whether displaced work was reassessed against current facts rather than simply returned to its old position. New client commitments or deadlines may have arrived, and the original evidence may no longer be fresh.',
        'Repeated overrides deserve a pattern view. Group them by trigger, requester, consequence, service area, duration, and destination of displaced work, while protecting client confidentiality. Concentration can identify a planning or intake question, but it does not prove misuse or poor performance. Report counts with denominators and visibility limits; an account specialist may see queue events but not private executive decisions that explain them.'
      ]},
      { heading: 'Make tradeoffs reviewable without turning the queue into a promise', paragraphs: [
        'The operating record should show the promoted item, displaced items, evidence, decision owner, allowed communication, revised expectations, expiry, and next review. The outsourced specialist can keep that record current, flag an expired override, prepare impact options, and coordinate approved updates. They should not commit new dates, waive scope, allocate unapproved capacity, or decide commercial remedies.',
        'The narrow conclusion is that an override is auditable when the pre-change queue, authorization, displaced work, expiry, and reassessment survive the decision. The study can show whether controls were followed and where information went missing. It cannot prove that a different priority would have produced better retention, revenue, satisfaction, or delivery outcomes.'
      ]},
    ],
  },
  {
    slug: 'client-meeting-decision-ambiguity-research', title: 'Did the client meeting produce a decision, a direction, or only a discussion?', cluster: 'Workflow Design',
    excerpt: 'A transcript-to-record study of proposals, conditional agreement, authority, action language, corrections, and client-safe confirmation.', hero: '/research-heroes/2026-09-22-meeting-decision-traceability.png', service: 'account-reporting',
    unit: 'one consequential statement from a client meeting linked to the speaker, decision question, authority source, conditions, meeting record, and later confirmation', decision: 'whether the account record should show an approved decision, proposed direction, assigned investigation, unresolved question, or corrected misunderstanding', hypothesis: 'conversational agreement markers often lose conditions and authority context when converted into meeting notes and tasks', related: ['client-meeting-action-register','client-meeting-decision-traceability-study'],
    rows: [['Statement','Speaker, wording, timestamp, context','Discussion is not approval'],['Condition','Dependency, option, or qualification','Remove no material caveats'],['Authority','Decision class and source','Seniority is not universal authority'],['Confirmation','Approved record and correction path','Silence is not necessarily acceptance']],
    unique: [
      { heading: 'Meetings create language faster than governance records', paragraphs: [
        'Client conversations use shorthand: “sounds good,” “let us proceed,” “we can explore that,” “send it over,” or “that should work.” Meaning depends on the question, speaker, preceding condition, authority, and expected next step. When notes convert every affirmative phrase into a decision, proposals become commitments. When notes treat every conditional answer as inconclusive, real decisions disappear. This research classifies the evidence without claiming that a recording or transcript is the sole authoritative source.',
        'The decision taxonomy should be fixed before sampling: approved decision, conditional decision, preferred option, permission to investigate, request for a proposal, assigned action, deferred question, rejected option, and ambiguous statement. Define each using observable features. A task can follow a discussion without proving approval of the final outcome; an owner can approve a direction while leaving dates or terms unresolved.'
      ]},
      { heading: 'Preserve context around the candidate decision', paragraphs: [
        'For every sampled statement, capture the agenda question, speaker identity, verified role if available, exact contemporaneous note or approved transcript reference, material words before and after, stated conditions, referenced document, dissent, chair summary, action assigned, and post-meeting confirmation. Limit collection to approved records. Recordings and transcripts may contain personal or confidential data and require an authorized purpose, access route, retention rule, and disposition.',
        'A decision can be invalidly summarized even when every word is accurate. Omitting “subject to security review” changes the operational meaning of “we can proceed.” Attaching a date mentioned for planning to an approved milestone can create a false commitment. Conversely, burying an explicit owner approval in narrative notes can delay work. Reviewers should compare the structured record with the full decision context and list each material transformation.'
      ]},
      { heading: 'Measure ambiguity and correction behavior', paragraphs: [
        'Independently code a subset of candidate decisions and report agreement by category. High disagreement may reflect vague language, missing context, overlapping definitions, or an unresolved authority question. Do not force consensus merely to improve a metric. Route materially consequential ambiguity to the meeting owner with neutral options: proposed interpretation, contrary evidence, affected work, and the exact confirmation needed.',
        'Then study correction latency and propagation. Did the clarification update the minutes, action register, CRM, project queue, client update, and downstream owner where appropriate? Preserve the original note and correction date rather than silently overwriting history. A prompt correction supports traceability, but this study should not claim that it prevented a client outcome. Report unresolved statements at the cutoff as unresolved.'
      ]},
      { heading: 'Use confirmation proportionate to consequence', paragraphs: [
        'Not every routine action needs formal client reconfirmation. The approved process may allow the chair’s recap, written minutes, a designated approver, or a workflow record to serve as confirmation. Higher-consequence changes involving scope, price, access, security, privacy, legal positions, staffing, or client commitments require the accountable route established by the organization. The research evaluates adherence to that route rather than inventing a universal ceremony.',
        'The bounded conclusion is that a meeting decision is operationally usable when question, statement, conditions, authority, disposition, action, and correction path stay connected. An outsourced specialist can prepare minutes, maintain the register, request clarification, and route conflicts. They should not turn conversational warmth into approval or issue commitments beyond the evidence and delegated authority.'
      ]},
    ],
  },
];

const commonSections = (t: Topic): ResearchSection[] => [
  { heading: 'Research boundary and predeclared protocol', paragraphs: [
    `The unit of analysis is ${t.unit}. The intended decision is ${t.decision}. The working hypothesis is that ${t.hypothesis}. Freeze that statement, the observation window, eligible population, inclusion and exclusion rules, source hierarchy, duplicate rule, missingness codes, comparison fields, and stopping rule before selecting outcomes. This prevents a convenient result from redefining the study after reviewers know which records look favorable.`,
    'Select from an upstream eligible frame rather than only closed, searchable, recent, or well-documented records. Include ordinary, incomplete, contradictory, corrected, reopened, disputed, exception, and missing-evidence cases where the population contains them. Preserve nonselection and substitutions. Report eligible, selected, excluded, unavailable, and analyzed counts separately so a clean sample is not mistaken for a clean process.',
    'Facts, analysis, inference, and decisions belong in separate fields. A fact points to an approved source and date. Analysis applies a declared definition. Inference states what may explain the pattern and competing explanations. A decision names the accountable owner and effective condition. This study does not establish employee quality, client sentiment, contractual compliance, privacy or security compliance, revenue, retention, or a guaranteed service outcome.',
    'Before coding, run a small pilot to test whether two reviewers can locate the same event and apply the field guide without private explanation from its author. Revise unclear definitions before the full sample, preserve the pilot version, and identify records recoded after the change. Freeze the cutoff timestamp and timezone. Evidence arriving later should enter a separate sensitivity view with its received time and effect on the finding. This makes the difference between missing-at-cutoff and permanently absent visible. It also prevents a late, favorable document from quietly repairing the historical record while an equally relevant unfavorable correction remains outside the dataset.'
  ]},
  { heading: 'Source quality, privacy, and reviewer controls', paragraphs: [
    'Rank sources by authority, specificity, relevance, and freshness for the claim being tested. An authorized correction may supersede an older system field, while a recent informal message may not override an approved instruction. Preserve both states, effective dates, actors, reasons, and downstream effects. Never average incompatible evidence into a confident label or infer that an unseen event did not occur.',
    'Apply least privilege and data minimization. Use only approved accounts, systems, clients, and fields; avoid copying personal or client-confidential content into the analysis file; restrict exports; and define disposal for working material. The Philippine Data Privacy Act and FTC guidance provide relevant context, but qualified owners determine actual obligations, lawful bases, contract rules, and permitted handling for the client and jurisdiction.',
    'Two reviewers should independently code a meaningful subset using the same field guide and without resolving differences in advance. Report agreement by field and retain disagreements. Agreement supports reproducibility under this protocol, not objective truth. A disagreement may reveal a weak definition, incomplete evidence, different access boundaries, or a decision that was never formally recorded.'
  ]},
  { heading: 'Interpretation, limitations, and replication', paragraphs: [
    'Begin reporting with population counts, missing sources, contradictions, corrections, exceptions, state transitions, and reviewer disagreements. Then state the observed pattern with its denominator and time boundary. Do not convert frequency into cause. Cross-account aggregation is appropriate only when definitions, visibility, eligibility, and clocks are comparable; otherwise report bounded cases and explain why no combined rate is defensible.',
    'NIST CSF 2.0 supplies governance and risk-management outcomes. NIST SP 800-53 supplies adaptable control language. The 2025 GAO Green Book emphasizes quality information, control design, monitoring, and remediation. FTC and ISO sources add practical security and quality principles. None sets a universal account-management staffing ratio, response promise, contractual meaning, approval route, or performance benchmark. Local approved sources remain controlling.',
    'Material limitations include small or convenience samples, private conversations, inaccessible client systems, incomplete histories, inconsistent clocks, configuration changes, different contracts, geography, holidays, stakeholder availability, retention practices, and reviewer knowledge of outcomes. Replication requires the same unit, definitions, eligibility rules, observation window, source hierarchy, field guide, missingness treatment, and independent recoding. Disclose every method change and start a new series where records cannot be recoded without hindsight.'
  ]},
];

export const research20260928: ResearchPost[] = topics.map((t) => ({
  slug: t.slug, title: t.title, cluster: t.cluster, excerpt: t.excerpt, hero: t.hero,
  published: '2026-09-28', datePublished: '2026-09-28', updated: '2026-09-28',
  headlineStat: 'Four evidence stages separate an observed event from an accountable decision',
  statSource: 'Topic-specific synthesis of NIST, GAO, FTC, Philippine NPC, and ISO principles',
  takeaways: [
    'Define the event, eligible population, decision boundary, and source hierarchy before reviewing outcomes.',
    'Preserve missing, contradictory, corrected, exception, and reopened records as part of the result.',
    'Keep evidence preparation with the support role and consequential judgment with accountable owners.',
    'Use a dated review trigger and explicit uncertainty rather than converting an open state into closure.',
  ],
  sections: [...t.unique, ...commonSections(t)],
  table: { headers: ['Evidence stage', 'Minimum record', 'Interpretation boundary'], rows: t.rows },
  sources,
  researchMethodology: `Predeclared bounded review of ${t.unit}; upstream sampling; explicit missingness; independent recoding; exception analysis; non-causal conclusions.`,
  externalSources: sources.map((source) => source.url),
  faqs: [
    { q: 'Can this research prove a client outcome?', a: 'No. It evaluates evidence and workflow states in a bounded sample; it cannot prove causality, satisfaction, retention, revenue, compliance, or a guaranteed result.' },
    { q: 'What may the outsourced account specialist do?', a: 'They may gather permitted evidence, maintain assigned records, prepare neutral summaries, flag exceptions, and coordinate approved follow-up. Consequential decisions remain with accountable owners.' },
    { q: 'How should another team replicate the analysis?', a: 'Freeze definitions and the observation window, select from the eligible frame, retain missing and contrary cases, independently recode a subset, report exclusions, and disclose method changes.' },
  ],
  related: t.related,
  internalLinks: [
    { label: `Review ${t.service.replaceAll('-', ' ')} support`, href: `/services/${t.service}` },
    { label: 'Explore the research library', href: '/research' },
  ],
}));
