import type { ResearchPost } from './research-data';

type Topic = readonly [string, string, 'Hiring Controls' | 'Scope Benchmarks' | 'Workflow Design', string, string, string];
const topics: Topic[] = [
  ['account-priority-reset-reproducibility', 'Can two reviewers reproduce an account priority reset?', 'Workflow Design', 'daily priorities changing without a reproducible client-consequence rule', 'independently rank the same eligible queue using frozen evidence, consequence, authority, and timing definitions', '2026-08-31-account-metric-definition-drift-study.png'],
  ['client-question-answer-boundary-study', 'Where does a client question become an unsupported answer?', 'Hiring Controls', 'client questions acquiring assumptions while moving through research, approval, and reply', 'compare the original wording with each draft, cited source, removed uncertainty, approver action, and final response', '2026-08-31-client-silence-interpretation-research.png'],
  ['renewal-decision-window-loss-analysis', 'Analysis of lost renewal decision windows', 'Scope Benchmarks', 'renewal choices reaching owners after a contractual or operating window has narrowed', 'reconstruct notice dates, evidence cutoffs, preparation starts, owner receipts, decisions, and preventable waiting', '2026-08-31-account-queue-invisible-work-analysis.png'],
  ['qbr-claim-source-reproducibility', 'Reproducibility of QBR claim-to-source links', 'Hiring Controls', 'review claims changing meaning when a second reviewer follows their evidence trail', 'ask independent reviewers to recover the population, definition, period, source value, limitation, and supported conclusion', '2026-08-31-account-metric-definition-drift-study.png'],
  ['handoff-rejection-signal-study', 'What do rejected account handoffs actually signal?', 'Workflow Design', 'handoff rejection being treated as individual failure without testing the acceptance rule or missing dependency', 'code rejection reasons, acceptance criteria, unavailable inputs, authority gaps, correction cycles, and eventual acceptance evidence', '2026-08-31-handoff-shadowing-error-detection.png'],
];

const sources = [
  { name: 'NIST Cybersecurity Framework 2.0', date: 'February 26, 2024', url: 'https://www.nist.gov/publications/cybersecurity-framework-csf-20', note: 'Governance and control vocabulary, not an account-management benchmark.' },
  { name: 'ISO quality management principles', date: 'accessed September 2, 2026', url: 'https://www.iso.org/quality-management/principles', note: 'Evidence-based decision and improvement principles.' },
  { name: 'NIST accountability glossary', date: 'accessed September 2, 2026', url: 'https://csrc.nist.gov/glossary/term/accountability', note: 'Traceable responsibility vocabulary.' },
  { name: 'FTC Start with Security', date: 'June 2015', url: 'https://www.ftc.gov/business-guidance/resources/start-security-guide-business', note: 'Access-control and data-minimization guidance.' },
];

function study([slug, title, cluster, question, method, hero]: Topic): ResearchPost {
  return {
    slug, title, cluster, excerpt: `A September 2, 2026 research design examining ${question}.`, headlineStat: 'A workflow label cannot prove source quality, authority, cause, acceptance, or outcome', statSource: 'Route-specific synthesis of NIST, ISO, and FTC control principles', published: '2026-09-02', datePublished: '2026-09-02', updated: '2026-09-02', hero: `/research-heroes/${hero}`,
    takeaways: [`Study ${question} as a bounded record-level question.`, 'Freeze the unit, population, definitions, exclusions, and competing explanations before sampling.', 'Use independent recoding to test whether the finding survives a second reviewer.', 'Keep observation, interpretation, authority, communication, and outcome in separate fields.'],
    sections: [
      { heading: 'Research question and decision boundary', paragraphs: [`Published September 2, 2026. This report examines ${question}. The unit is one dated account-work record at a defined decision point, not a person, company, or general service outcome.`, `Name the operating decision the finding may inform. A result may justify a revised field, evidence rule, trigger, owner route, or acceptance check; it cannot by itself establish retention, revenue, satisfaction, or individual performance.`] },
      { heading: 'Population and sampling frame', paragraphs: [`Define the eligible records, period, inclusion rule, exclusion rule, denominator, and source hierarchy before inspecting outcomes. Include apparently successful, incomplete, disputed, returned, and reopened records.`, `Stratify where account consequence, channel, workflow state, contract type, or source system could change interpretation. Preserve every exclusion reason. Missing evidence remains a study result when the workflow required it.`] },
      { heading: 'Route-specific coding procedure', paragraphs: [`The procedure is to ${method}. Freeze the coding guide first, then record the source, timestamp, observed fact, interpretation, work owner, decision owner, client consequence, communication state, close rule, and reopen trigger.`, `This route-specific method distinguishes this report from adjacent studies: its primary comparison follows the particular transformation described in the title, rather than applying a generic completeness score.`] },
      { heading: 'Independent reproduction test', paragraphs: [`Give a second reviewer the same frozen inputs without the first reviewer’s conclusion. Compare field-level agreement and retain the disagreements rather than averaging them away.`, `Classify disagreement by unclear definition, missing source, inaccessible evidence, stale ownership, authority ambiguity, or genuine judgment. Agreement shows reproducibility under the stated method; it does not establish that the conclusion caused an outcome.`] },
      { heading: 'Timing, freshness, and sequence', paragraphs: [`Record evidence as it existed at the decision point, then preserve later corrections separately. Freshness is purpose-specific: an agreement may control scope while being unable to prove current execution.`, `Sequence can reveal where waiting accumulated, but it cannot prove why. Client dependency, approval care, access limits, source correction, and internal delay are competing explanations that require their own evidence.`] },
      { heading: 'Privacy and authority controls', paragraphs: [`Use the minimum account information required by this research question. Work in approved systems with named access and aggregate findings when row-level details are unnecessary.`, `Researchers may prepare evidence and control questions. Commercial, legal, security, privacy, access, and service-scope decisions remain with authorized owners; study access does not transfer that authority.`] },
      { heading: 'Analysis and reporting', paragraphs: [`Report the inspected count, eligible count, exclusions, missingness, disagreement, and distribution of coded reasons. Show representative routine, exception, and unresolved cases with unnecessary client data removed.`, `Keep observation and explanation in separate columns. Report plausible alternatives beside the preferred interpretation and identify which additional evidence would distinguish them.`] },
      { heading: 'Limitations and implementation use', paragraphs: [`A local sample may omit undocumented work, inaccessible client systems, or quiet coordination. Account size, contract language, tool design, geography, and stakeholder availability may limit transfer to another portfolio.`, `Use findings to propose a bounded control change with an owner, effective date, review trigger, and rollback condition. Re-measure against the same definition; do not convert a process observation into a performance guarantee.`] },
    ],
    table: { headers: ['Research layer', 'Required record', 'Interpretation boundary'], rows: [['Design', 'Question, unit, population, period', 'Not an outcome claim'], ['Evidence', 'Source, date, fact, missingness', 'Not a causal explanation'], ['Reproduction', 'Second coding and disagreement reason', 'Agreement is not accuracy'], ['Decision', 'Owner, proposed control, recheck', 'Research does not confer authority']] },
    sources, faqs: [{ q: 'What is the first step?', a: `Define the decision and the eligible records for studying ${question}.` }, { q: 'Why use a second reviewer?', a: 'Independent coding shows whether the definitions and evidence trail support a reproducible finding.' }, { q: 'What can this study conclude?', a: 'It can describe bounded patterns and control gaps, not universal performance, causation, or client outcomes.' }],
    related: topics.filter(t => t[0] !== slug).slice(0, 2).map(t => t[0]), internalLinks: [{ label: 'See account reporting support', href: '/services/account-reporting' }, { label: 'Review account health monitoring', href: '/services/account-health-monitoring' }],
  };
}

export const research20260902: ResearchPost[] = topics.map(study);
