export type ResearchSection = { heading: string; paragraphs: string[] };
export type ResearchPost = {
  slug: string; title: string; excerpt: string; cluster: string; published: string; updated: string;
  headlineStat: string; statSource: string; takeaways: string[]; sections: ResearchSection[];
  table: { headers: string[]; rows: string[][] }; sources: { name: string; date: string; url: string; note: string }[];
  faqs: { q: string; a: string }[]; related: string[]; internalLinks: { label: string; href: string }[];
};

const sources = [
  { name: 'NIST Cybersecurity Framework 2.0', date: 'February 26, 2024', url: 'https://www.nist.gov/publications/cybersecurity-framework-csf-20', note: 'Governance, identification, protection, detection, response, and recovery framework.' },
  { name: 'NIST SP 800-53 Rev. 5', date: 'September 2020', url: 'https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final', note: 'Security and privacy control families used for access and review recommendations.' },
  { name: 'NIST least privilege glossary', date: 'accessed August 7, 2026', url: 'https://csrc.nist.gov/glossary/term/least_privilege', note: 'Defines limiting access to the minimum needed for assigned tasks.' },
  { name: 'U.S. Small Business Administration, manage your business', date: 'accessed August 7, 2026', url: 'https://www.sba.gov/business-guide/manage-your-business', note: 'Business-management guidance supporting written processes and record keeping.' },
  { name: 'FTC Start with Security', date: 'June 2015', url: 'https://www.ftc.gov/business-guidance/resources/start-security-guide-business', note: 'Practical guidance for access control, data minimization, and incident response.' },
  { name: 'Philippine National Privacy Commission, Data Privacy Act', date: 'accessed August 7, 2026', url: 'https://privacy.gov.ph/data-privacy-act/', note: 'Republic Act No. 10173 and Philippine personal-data governance context.' },
  { name: 'Microsoft Work Trend Index Annual Report', date: 'May 9, 2023', url: 'https://www.microsoft.com/en-us/worklab/work-trend-index/will-ai-fix-work', note: 'Reports 62% struggling with search time and 68% lacking uninterrupted focus time among surveyed workers.' },
  { name: 'U.S. Department of Labor, telework guidance', date: 'accessed August 7, 2026', url: 'https://www.dol.gov/general/topic/workhours/telework', note: 'General timekeeping and work-arrangement context.' },
  { name: 'ISO 9001 quality management principles', date: 'accessed August 7, 2026', url: 'https://www.iso.org/quality-management/principles', note: 'Process, evidence, improvement, and customer-focus context.' },
  { name: 'NIST accountability glossary', date: 'accessed August 7, 2026', url: 'https://csrc.nist.gov/glossary/term/accountability', note: 'Defines accountability as tracing actions to an entity.' },
];

const topics = [
  ['account-health-scorecard', 'Account health scorecard design for outsourced account management', 'Hiring Controls', 'A scorecard that separates observed facts, owner judgments, and next actions can make an outsourced account portfolio easier to review.', '62% of surveyed workers reported spending too much time searching for information', 'Microsoft Work Trend Index', 'health signals', 'account health monitoring', 'Build a scorecard from last-touch date, open commitments, client sentiment, renewal timing, and evidence links.'],
  ['client-onboarding-control-points', 'Client onboarding control points for a Philippines-based account manager', 'Workflow Design', 'Map onboarding handoffs so access, facts, approvals, and the first client update have visible owners.', 'Six NIST CSF 2.0 functions organize the control map', 'NIST Cybersecurity Framework 2.0', 'onboarding controls', 'client onboarding coordination', 'Onboarding is safer when each handoff has a source record, an owner, a due date, and a close rule.'],
  ['renewal-readiness-evidence', 'Renewal readiness evidence checklist for account teams', 'Scope Benchmarks', 'Renewal preparation should assemble evidence of outcomes and open risks without allowing an assistant to change commercial terms.', 'Five NIST CSF 2.0 functions support a renewal evidence review', 'NIST Cybersecurity Framework 2.0', 'renewal evidence', 'renewal administration', 'A renewal packet should show delivered work, unresolved risks, commitments, dates, and the decision owner for every commercial choice.'],
  ['qbr-data-quality-controls', 'QBR data-quality controls for outsourced account reporting', 'Hiring Controls', 'A quarterly business review is only as useful as the source fields, definitions, dates, and owners behind its charts.', 'ISO quality principles emphasize customer focus and improvement', 'ISO 9001 quality management principles', 'QBR data quality', 'account reporting', 'Treat every QBR metric as a claim that needs a definition, source, time window, owner, and review status.'],
  ['client-request-routing-benchmark', 'Client request routing benchmark: response, risk, and ownership', 'Workflow Design', 'Route client requests by consequence and authority instead of letting urgency alone decide who answers.', 'Five NIST CSF 2.0 functions provide a useful routing vocabulary', 'NIST Cybersecurity Framework 2.0', 'request routing', 'client request routing', 'A good routing matrix names the first response, decision owner, evidence needed, and escalation clock for each request type.'],
  ['crm-access-review', 'CRM access review for Philippines-based account support', 'Hiring Controls', 'Match CRM permissions to assigned account work and review them when the role, client, or system changes.', 'Least privilege means minimum access needed for assigned tasks', 'NIST least privilege glossary', 'CRM access', 'CRM account maintenance', 'Start with read access, add only task-required writes, and keep exports, administration, deletion, and permission changes owner-controlled.'],
  ['escalation-severity-model', 'Escalation severity model for client account operations', 'Workflow Design', 'A severity model helps an account manager route risk consistently while keeping legal, security, financial, and scope decisions with accountable owners.', 'Six NIST CSF 2.0 functions cover the full risk lifecycle', 'NIST Cybersecurity Framework 2.0', 'escalation severity', 'escalation coordination', 'Define severity by client impact, data exposure, contractual risk, and time sensitivity, then attach an owner and evidence standard.'],
  ['feedback-loop-closure', 'Client feedback loop closure: evidence and follow-up design', 'Scope Benchmarks', 'Feedback becomes operational value when the original words, response, owner, and proof of closure stay connected.', 'ISO quality principles include customer focus and improvement', 'ISO 9001 quality management principles', 'feedback closure', 'customer feedback administration', 'Do not close feedback because a reply was sent; close it when the requested result, owner review, and client-safe record agree.'],
  ['implementation-handoff-risk', 'Implementation handoff risk map for account management teams', 'Workflow Design', 'Handoffs fail when context, access, ownership, and client expectations travel in different records.', 'NIST CSF 2.0 includes identify and protect functions before response and recovery', 'NIST Cybersecurity Framework 2.0', 'handoff risk', 'implementation handoff support', 'A handoff brief should carry the approved scope, current facts, open decisions, access map, client language, and first review date.'],
  ['account-manager-daily-control-rhythm', 'Daily control rhythm for an outsourced account manager', 'Scope Benchmarks', 'A short daily rhythm keeps client requests, risks, approvals, and reporting visible without turning the role into an unrestricted operator.', '68% of surveyed workers reported lacking enough uninterrupted focus time', 'Microsoft Work Trend Index', 'daily control rhythm', 'account health monitoring', 'Use a morning triage, focused work block, owner queue, client-update window, and end-of-day evidence check.'],
  ['account-plan-evidence-map', 'Account plan evidence map for outsourced client teams', 'Scope Benchmarks', 'An account plan is more useful when every objective has a source, owner, status definition, and review date.', 'ISO quality principles emphasize evidence and continual improvement', 'ISO 9001 quality management principles', 'account plan evidence', 'account planning support', 'Map each account objective to evidence, an accountable owner, the next client-safe update, and a close condition.'],
  ['client-meeting-action-register', 'Client meeting action register design and closure controls', 'Workflow Design', 'Meeting notes become operational only when decisions, actions, owners, due dates, and proof of completion remain connected.', 'Accountability is the ability to trace actions to an entity', 'NIST accountability glossary', 'meeting actions', 'client meeting coordination', 'Capture decisions separately from discussion, assign one owner per action, and close only against visible proof.'],
  ['service-level-exception-routing', 'Service-level exception routing for account support', 'Workflow Design', 'Exception routing makes missed expectations visible while preserving the authority boundaries around commitments and remediation.', 'NIST CSF 2.0 organizes response and recovery as distinct functions', 'NIST Cybersecurity Framework 2.0', 'service exceptions', 'service-level reporting', 'Record the expected service, observed exception, client impact, decision owner, and approved next communication.'],
  ['client-communication-approval-matrix', 'Client communication approval matrix for account managers', 'Hiring Controls', 'A communication matrix helps an account manager move quickly on routine updates while reserving sensitive statements for accountable owners.', 'Least privilege limits access to the minimum needed for assigned tasks', 'NIST least privilege glossary', 'communication approval', 'client communication support', 'Classify messages by risk and authority, then define who may prepare, approve, send, and archive each class.'],
  ['account-renewal-risk-register', 'Account renewal risk register with evidence thresholds', 'Scope Benchmarks', 'A renewal risk register should distinguish observed signals from forecasts and show what evidence would change the recommendation.', 'NIST CSF 2.0 separates identification from response', 'NIST Cybersecurity Framework 2.0', 'renewal risk', 'renewal administration', 'Use evidence thresholds for delivery, relationship, scope, data, and timing risks before assigning a renewal status.'],
  ['customer-health-data-dictionary', 'Customer health data dictionary for outsourced reporting', 'Hiring Controls', 'A shared data dictionary prevents the same account field from carrying different meanings across weekly and quarterly reporting.', 'ISO quality principles emphasize a factual approach to decision making', 'ISO 9001 quality management principles', 'health data definitions', 'account reporting', 'Define every health field with its meaning, source, allowed values, owner, freshness rule, and limitation.'],
  ['shared-inbox-triage-controls', 'Shared inbox triage controls for client account requests', 'Workflow Design', 'Shared inboxes need a clear intake, classification, owner, and closure record so urgent messages do not erase important context.', 'FTC guidance recommends access control and data minimization', 'FTC Start with Security', 'inbox triage', 'client request routing', 'Triage by client impact and authority, link each request to the account record, and preserve the final response and owner.'],
  ['account-transition-knowledge-capture', 'Account transition knowledge-capture checklist', 'Workflow Design', 'A transition checklist turns tacit account context into a controlled record that a new owner can review and challenge.', 'SBA guidance supports written processes and record keeping', 'U.S. Small Business Administration, manage your business', 'transition knowledge', 'account transition support', 'Capture current commitments, sources, access boundaries, client preferences, open risks, and the first review date.'],
  ['client-data-retention-routine', 'Client data retention routine for account operations', 'Hiring Controls', 'Retention routines reduce unnecessary exposure by making storage, review, deletion, and exception ownership explicit.', 'Data minimization is a core practical security control', 'FTC Start with Security', 'data retention', 'CRM account maintenance', 'Classify records by purpose and retention rule, keep deletion authority with the owner, and log approved exceptions.'],
  ['monthly-account-review-agenda', 'Monthly account review agenda with decision-ready evidence', 'Scope Benchmarks', 'A monthly review should compress account activity into decisions, risks, commitments, and evidence instead of producing another undifferentiated status report.', 'ISO quality principles connect customer focus with improvement', 'ISO 9001 quality management principles', 'monthly account review', 'account health monitoring', 'Use a fixed agenda covering outcomes, open commitments, risks, client feedback, decisions, and next checks.'],
];

export const researchPosts: ResearchPost[] = topics.map(([slug, title, cluster, excerpt, headlineStat, statSource, label, service, thesis], i) => {
  const related = topics.filter(t => t[0] !== slug).slice(i % 7, i % 7 + 3).map(t => t[0]);
  return {
    slug, title, cluster, excerpt, headlineStat, statSource, published: '2026-08-07', updated: '2026-08-07',
    takeaways: [thesis, `Keep ${label} evidence in the account record, with one work owner and a separate decision owner when authority matters.`, `Review the record on a fixed cadence and escalate gaps rather than hiding them in a green status.`],
    sections: [
      { heading: `What the ${label} evidence should show`, paragraphs: [`The useful unit is not a promise that work is under control; it is a dated record showing the source fact, current state, accountable owner, and next check. For ${service}, start with the smallest set of fields that lets an owner understand what changed and what still needs a decision.`, `${headlineStat} is a context signal, not a performance claim about this company or a Philippines-based team. Keep the source, publication date, population, and limitation beside the number so it cannot be mistaken for an internal result.`] },
      { heading: 'Separate preparation from authority', paragraphs: [`A Philippines-based account manager can collect facts, update assigned records, prepare a draft, route a request, and remind an owner. Contract changes, discounts, refunds, legal statements, security exceptions, access administration, and work outside scope require the named business owner.`, `Write the boundary into the workflow. A task should say whether the person may prepare, send an approved message, or only queue the item for review. That makes a fast handoff safer than an informal instruction in chat.`] },
      { heading: 'Use a repeatable review loop', paragraphs: [`Review ${label} on a fixed cadence: inspect the source, check the owner, confirm the due date, record the next client update, and link the proof. If a field is missing, mark the item incomplete and route it to the person who can supply it.`, `Use evidence from the approved system rather than memory. Microsoft reports that 62% of surveyed workers struggled with search time and 68% lacked uninterrupted focus time; this is workplace context, not an account-management benchmark, but it reinforces the value of one usable record.`] },
      { heading: 'Protect client information', paragraphs: [`Apply least privilege and data minimization to ${label}. Give access only to the records required for assigned work, use named accounts, avoid uncontrolled exports, and remove access when the assignment ends.`, `The Philippine Data Privacy Act is part of the local context for personal information systems. Ask the accountable owner to confirm the approved tools, retention rules, incident route, and access-review cadence before the work begins.`] },
      { heading: 'Turn findings into an owner decision', paragraphs: [`A report is useful when it ends with a decision-ready queue: what is known, what is not known, what changed, who can decide, and when the next update will be sent. Avoid an unsupported “healthy” or “at risk” label without the evidence behind it.`, `Use the findings to improve the routine, not to create a new uncontrolled promise. Record the chosen action, its limit, its owner, and the proof required to close it.`] },
    ],
    table: { headers: ['Control field', 'Minimum evidence', 'Owner check'], rows: [['Source', 'Link, date, and exact fact', 'Can another person reproduce it?'], ['Status', 'Current state and last checked time', 'Does it reflect the source record?'], ['Authority', 'Work owner and decision owner', 'Is approval scope explicit?'], ['Next update', 'Date, channel, and expected proof', 'Will the client know what happens next?']] },
    sources: sources.map(s => ({...s})),
    faqs: [
      { q: `What is the first step in ${label}?`, a: `Define the source record, the minimum fields, and the owner who reviews the result. Then test the routine on a small set of real accounts.` },
      { q: 'What should an outsourced account manager not decide?', a: 'The role should not independently change contracts, approve money movement or refunds, make legal or security judgments, administer broad access, or promise work outside scope.' },
      { q: 'How do we know the record is complete?', a: 'A complete record has a source, date, current state, named work owner, decision owner where needed, next update, and linked proof of closure.' },
    ],
    related,
    internalLinks: [{label: `See ${service} support`, href: `/services/${service}`}, {label: 'Read account reporting support', href: '/services/account-reporting'}],
  };
});
