import type { ResearchPost } from './research-data';
type Topic=readonly[string,string,string,string,string];
const topics:Topic[]=[
['client-decision-expiry-bias-study','Decision-expiry bias in outsourced account management','Hiring Controls','old approvals continuing after assumptions change','compare approval conditions, effective windows, expiry triggers, later actions, and reapproval evidence'],
['account-queue-invisible-work-analysis','Invisible work in client account queues','Workflow Design','queue counts omitting reconciliation, approval waiting, verification, and communication','trace each sampled request across intake, evidence preparation, owner waiting, client waiting, verification, and communication'],
['client-silence-interpretation-research','How should account teams interpret client silence?','Scope Benchmarks','nonresponse being mistaken for consent, satisfaction, rejection, or low risk','sample unanswered requests by stakeholder, channel, consequence, cadence, later response, and competing explanation'],
['account-metric-definition-drift-study','Metric-definition drift in client account reporting','Hiring Controls','stable metric labels hiding changed formulas, populations, exclusions, or refresh rules','reconstruct definitions, denominators, exclusions, source owners, and comparison claims across reporting periods'],
['handoff-shadowing-error-detection','Can shadow review detect account-handoff errors?','Workflow Design','observed first work revealing missing sources, stale context, or authority confusion','observe fixed first-work tasks and compare actions with the approved handoff, source record, and decision boundary'],
];
const sources=[{name:'NIST Cybersecurity Framework 2.0',date:'February 26, 2024',url:'https://www.nist.gov/publications/cybersecurity-framework-csf-20',note:'Governance vocabulary, not an account-management benchmark.'},{name:'ISO quality management principles',date:'accessed August 31, 2026',url:'https://www.iso.org/quality-management/principles',note:'Evidence-based process and improvement principles.'},{name:'NIST accountability glossary',date:'accessed August 31, 2026',url:'https://csrc.nist.gov/glossary/term/accountability',note:'Traceable responsibility vocabulary.'},{name:'FTC Start with Security',date:'June 2015',url:'https://www.ftc.gov/business-guidance/resources/start-security-guide-business',note:'Access-control and data-minimization guidance.'}];
function study([slug,title,cluster,question,method]:Topic):ResearchPost{return{slug,title,cluster,excerpt:`A bounded research design testing ${question}.`,headlineStat:'A workflow label is not evidence of cause, authority, or completion',statSource:'Route-specific synthesis of NIST, ISO, and FTC control principles',published:'2026-08-31',datePublished:'2026-08-31',updated:'2026-08-31',hero:`/research-heroes/2026-08-31-${slug}.png`,takeaways:['Define the unit, decision, and competing explanations before inspecting outcomes.','Preserve missing, conflicting, negative, and reopened cases.','Use independent recoding to test whether another reviewer can reproduce the result.','Separate observed facts, interpretation, owner authority, client communication, and verified closure.'],sections:[
{heading:'Research question and evidence boundary',paragraphs:[`Published August 31, 2026. This route asks whether ${question}. The unit of analysis is one dated account record at one defined decision point. The study is designed to improve an outsourced account-management control; it does not estimate an industry rate, client satisfaction, retention, revenue, or worker performance.`,`State the operational decision the evidence will support before selecting records. A finding may justify changing an intake field, review trigger, owner route, or communication rule. If no decision is named, the exercise can accumulate descriptive detail without showing which control should change or which authorized person should consider the change.`]},
{heading:'Sampling design',paragraphs:[`Define the population, period, inclusion rule, exclusion rule, source hierarchy, and denominator before review. Include incomplete, disputed, reclassified, reopened, and apparently successful records. Sampling only clean examples would make the workflow look more reliable and would remove precisely the cases most likely to reveal ambiguity or authority gaps.`,`Use stratification when account consequence, channel, contract type, or workflow state may change interpretation. Preserve the number inspected and the reason for every exclusion. Missing records are not merely an inconvenience: missingness may be the central finding when the workflow depends on evidence that cannot be located at the decision point.`]},
{heading:'Route-specific method',paragraphs:[`The route-specific procedure is to ${method}. Save the coding guide before examining outcomes. For each item record the exact source, source date, actor, observed fact, interpretation, work owner, decision owner, client consequence, communication state, closure rule, and reopening trigger.`,`Have a second reviewer independently code a defined subset without coaching. Retain disagreements and inspect whether they arose from unclear definitions, inaccessible sources, stale ownership, or ambiguous evidence. Agreement does not prove the conclusion is true, but disagreement shows where the process cannot yet support a reproducible interpretation.`]},
{heading:'Separate observation from explanation',paragraphs:[`An observation describes what the approved record contained during the stated window. It should not combine a client statement, remembered conversation, later correction, and reviewer inference into one fact. Preserve each layer so a decision owner can see which part is direct evidence and which part remains a hypothesis.`,`Sequence does not establish cause. A delayed item may reflect a client dependency, a careful owner review, missing access, a source correction, or avoidable internal waiting. A quick item may still be unsafe if an unsupported promise was sent. Test operational, client-dependent, authority-dependent, and measurement explanations before selecting a response.`]},
{heading:'Freshness and definition controls',paragraphs:[`Freshness is purpose-specific. A signed agreement may control approved scope while offering no proof of current delivery; a new message may describe current concern without changing the contract. Record the effective period and the event that requires rechecking each source rather than using one universal freshness label.`,`Keep definitions versioned. If a category, formula, population, closure rule, or severity threshold changes, retain the prior definition for the comparison period. Otherwise an apparent improvement may be a reclassification. Report which records move under the new rule and avoid a trend statement until the bridge between definitions is explicit.`]},
{heading:'Authority and role boundaries',paragraphs:[`An outsourced account manager may gather approved facts, reconcile assigned records, prepare a comparison, request clarification, draft neutral wording, and route a decision. Contract changes, pricing, credits, refunds, legal or security determinations, broad access, and promises outside approved scope remain with authorized business owners.`,`Record the work owner and decision owner separately when they differ. System access or the ability to edit a field does not prove decision authority. When an owner is unavailable, use a documented delegate with a defined limit and expiry. The study should treat unclear authority as a workflow finding rather than asking the reviewer to guess.`]},
{heading:'Data protection and auditability',paragraphs:[`Use task-matched access and the minimum client data needed for the research question. Link controlled evidence rather than copying sensitive files into the analysis. Exports, deletion, retention exceptions, permission administration, and disclosure decisions stay with authorized owners. Record inaccessible evidence as a limitation.`,`Preserve corrections with their source, date, editor, reviewer, and affected conclusion. Do not overwrite the earlier coding silently. A correction history allows another reviewer to understand why an earlier action occurred and whether the current conclusion should replace, narrow, or merely supplement it.`]},
{heading:'Analysis and negative cases',paragraphs:[`Summarize counts only when the denominator and missingness are stable. Report the number inspected, excluded, disagreed, and unresolved. Where useful, compare time between defined states, but do not assign fault from elapsed time alone. Link each finding to sample records and the coding rule that produced it.`,`Inspect at least one negative case and one ambiguous case closely. A negative case fails the stated evidence rule. An ambiguous case supports more than one plausible explanation. Showing how the control handles both is more informative than a polished average and helps the owner decide whether the next repair belongs in data, routing, training, or approval design.`]},
{heading:'Limitations',paragraphs:[`Small or selected samples, missing conversations, inaccessible tools, different contracts, geography, stakeholder availability, and changing account conditions limit transfer. Independent coding improves reproducibility but does not remove selection bias, establish causality, or prove that the observed sample represents a wider portfolio.`,`NIST, ISO, and FTC materials supply governance, accountability, evidence, and security concepts. They do not establish an OutsourcedAccountManagement.com result or acceptable performance threshold. The research must label these sources as method context and collect local evidence before an owner makes an operational decision.`]},
{heading:'Conclusion and replication',paragraphs:[`The bounded conclusion is that ${question} should be evaluated through dated sources, explicit definitions, competing explanations, and visible authority rather than inferred from a familiar status label. State what the evidence can answer, what remains unknown, who can decide, and the trigger for review.`,`After changing one control, repeat the study with a comparable population and preserve the old definition. Examine whether missingness, reviewer disagreement, reopened items, or unsafe interpretations changed. A client-facing update should still say only what is confirmed, what is being checked, and when the next approved answer will arrive.`]},
],table:{headers:['Evidence layer','Required record','Interpretation limit'],rows:[['Observation','Source, actor, date, exact fact','Does not prove cause'],['Method','Population, coding rule, exclusions, missingness','Does not prove representativeness'],['Authority','Work owner, decision owner, approval state','Preparation is not permission'],['Closure','Rule, proof, communication, reopen trigger','A message is not resolution']]},sources,faqs:[{q:'What is the first research step?',a:'Define the decision, unit, period, source hierarchy, inclusion rule, and competing explanations before reviewing outcomes.'},{q:'What makes the finding reproducible?',a:'A saved coding rule, route-local sources, explicit missingness, and independent recoding of a defined subset.'},{q:'What should the conclusion avoid?',a:'Universal benchmarks, unsupported causality, client guarantees, and decisions outside the reviewer’s authority.'}],related:[],internalLinks:[{label:'See account reporting support',href:'/services/account-reporting'},{label:'Review client request routing support',href:'/services/client-request-routing'}]};}
export const research20260831:ResearchPost[]=topics.map(study);
