import { makeSeptemberResearchStudy, type SeptemberResearchTopic } from './research-2026-09-07';
const topics:SeptemberResearchTopic[]=[
 ['account-decision-packet-reconstruction','Can reviewers reconstruct an account decision from its evidence packet?','Workflow Design','whether a bounded decision packet preserves the source facts, missing evidence, authority, timing, and client consequence needed for independent review','freeze completed and pending decision packets, ask two reviewers to reconstruct the question, evidence cutoff, unknowns, owner, and next action, then code omissions and disagreements','Reconstruction demonstrates record completeness under the protocol. It cannot prove that the decision was commercially optimal or caused a later client outcome.','2026-08-31-account-queue-invisible-work-analysis.png'],
 ['renewal-obligation-source-integrity','How often can renewal obligations be traced to a controlling source?','Hiring Controls','whether obligations in renewal preparation retain a reproducible link to current contract or approved client evidence','define the eligible obligation population, sample routine and disputed items, verify each cited source and effective period, and have a second reviewer classify missing, stale, conflicting, or superseded evidence','A traceable source establishes provenance, not legal interpretation. Contract meaning, waiver, pricing, and renewal decisions remain with authorized owners.','2026-08-20-renewal-evidence.png'],
 ['qbr-period-comparability-test','When are QBR periods comparable enough to support a trend statement?','Scope Benchmarks','whether reviewers detect changes in metric population, time window, exclusions, calculation, or source before approving a trend claim','construct paired period packets, vary one comparison condition at a time, require evidence citations and limitations, and compare independent approval decisions','Detection in controlled packets does not estimate live reporting error rates. Even stable definitions cannot establish causality or future performance.','2026-08-31-account-metric-definition-drift-study.png'],
 ['portfolio-review-omission-bias-study','Which accounts disappear from portfolio review populations?','Scope Benchmarks','whether filters, missing ownership, incomplete fields, or inactive labels systematically omit accounts from routine review','freeze the intended portfolio roster and generated review set, reconcile every exclusion, stratify omission reasons and consequences, and independently review unresolved cases','Observed omissions may reflect valid scope rules or data defects. This study cannot infer motive, portfolio risk, or client impact without additional evidence.','2026-08-31-client-silence-interpretation-research.png'],
 ['commitment-acceptance-proof-reliability','Does completion evidence predict accepted client commitments?','Workflow Design','whether records distinguish action completion from the stated acceptance condition and later acknowledgement','sample claimed closures and open exceptions, verify completion proof, acceptance rules, verifier responses, and reopen events, then compare two reviewers under a frozen rubric','Association between completion records and acceptance cannot show that the workflow caused satisfaction, retention, or commercial results. Missing client responses must remain missing, not be coded as acceptance.','2026-08-31-handoff-shadowing-error-detection.png'],
];
export const research20260909=topics.map(t=>makeSeptemberResearchStudy(t,'2026-09-09'));
