export type ResearchSection = { heading: string; paragraphs: string[] };
export type ResearchPost = {
  slug: string; title: string; excerpt: string; cluster: string; published: string; updated: string;
  headlineStat: string; statSource: string; takeaways: string[]; sections: ResearchSection[];
  table: { headers: string[]; rows: string[][] }; sources: { name: string; date: string; url: string; note: string }[];
  faqs: { q: string; a: string }[]; related: string[]; internalLinks: { label: string; href: string }[];
};

const sources = [
  { name: 'NIST Cybersecurity Framework 2.0', date: 'February 26, 2024', url: 'https://www.nist.gov/publications/cybersecurity-framework-csf-20', note: 'Governance, identification, protection, detection, response, and recovery framework.' },
  { name: 'NIST SP 800-53 Rev. 5', date: 'September 2020', url: 'https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final', note: 'Security and privacy control families used for access and review recommendations.' },
  { name: 'NIST least privilege glossary', date: 'accessed August 7, 2026', url: 'https://csrc.nist.gov/glossary/term/least_privilege', note: 'Defines limiting access to the minimum needed for assigned tasks.' },
  { name: 'U.S. Small Business Administration, manage your business', date: 'accessed August 7, 2026', url: 'https://www.sba.gov/business-guide/manage-your-business', note: 'Business-management guidance supporting written processes and record keeping.' },
  { name: 'FTC Start with Security', date: 'June 2015', url: 'https://www.ftc.gov/business-guidance/resources/start-security-guide-business', note: 'Practical guidance for access control, data minimization, and incident response.' },
  { name: 'Philippine National Privacy Commission, Data Privacy Act', date: 'accessed August 7, 2026', url: 'https://privacy.gov.ph/data-privacy-act/', note: 'Republic Act No. 10173 and Philippine personal-data governance context.' },
  { name: 'Microsoft Work Trend Index Annual Report', date: 'May 9, 2023', url: 'https://www.microsoft.com/en-us/worklab/work-trend-index/will-ai-fix-work', note: 'Reports 62% struggling with search time and 68% lacking uninterrupted focus time among surveyed workers.' },
  { name: 'U.S. Department of Labor, telework guidance', date: 'accessed August 7, 2026', url: 'https://www.dol.gov/general/topic/workhours/telework', note: 'General timekeeping and work-arrangement context.' },
  { name: 'ISO 9001 quality management principles', date: 'accessed August 7, 2026', url: 'https://www.iso.org/quality-management/principles', note: 'Process, evidence, improvement, and customer-focus context.' },
  { name: 'NIST accountability glossary', date: 'accessed August 7, 2026', url: 'https://csrc.nist.gov/glossary/term/accountability', note: 'Defines accountability as tracing actions to an entity.' },
];

const topics = [
  ['account-health-scorecard', 'Account health scorecard design for outsourced account management', 'Hiring Controls', 'A scorecard that separates observed facts, owner judgments, and next actions can make an outsourced account portfolio easier to review.', '62% of surveyed workers reported spending too much time searching for information', 'Microsoft Work Trend Index', 'health signals', 'account health monitoring', 'Build a scorecard from last-touch date, open commitments, client sentiment, renewal timing, and evidence links.'],
  ['client-onboarding-control-points', 'Client onboarding control points for a Philippines-based account manager', 'Workflow Design', 'Map onboarding handoffs so access, facts, approvals, and the first client update have visible owners.', 'Six NIST CSF 2.0 functions organize the control map', 'NIST Cybersecurity Framework 2.0', 'onboarding controls', 'client onboarding coordination', 'Onboarding is safer when each handoff has a source record, an owner, a due date, and a close rule.'],
  ['renewal-readiness-evidence', 'Renewal readiness evidence checklist for account teams', 'Scope Benchmarks', 'Renewal preparation should assemble evidence of outcomes and open risks without allowing an assistant to change commercial terms.', 'Five NIST CSF 2.0 functions support a renewal evidence review', 'NIST Cybersecurity Framework 2.0', 'renewal evidence', 'renewal administration', 'A renewal packet should show delivered work, unresolved risks, commitments, dates, and the decision owner for every commercial choice.'],
  ['qbr-data-quality-controls', 'QBR data-quality controls for outsourced account reporting', 'Hiring Controls', 'A quarterly business review is only as useful as the source fields, definitions, dates, and owners behind its charts.', 'ISO quality principles emphasize customer focus and improvement', 'ISO 9001 quality management principles', 'QBR data quality', 'account reporting', 'Treat every QBR metric as a claim that needs a definition, source, time window, owner, and review status.'],
  ['client-request-routing-benchmark', 'Client request routing benchmark: response, risk, and ownership', 'Workflow Design', 'Route client requests by consequence and authority instead of letting urgency alone decide who answers.', 'Five NIST CSF 2.0 functions provide a useful routing vocabulary', 'NIST Cybersecurity Framework 2.0', 'request routing', 'client request routing', 'A good routing matrix names the first response, decision owner, evidence needed, and escalation clock for each request type.'],
  ['crm-access-review', 'CRM access review for Philippines-based account support', 'Hiring Controls', 'Match CRM permissions to assigned account work and review them when the role, client, or system changes.', 'Least privilege means minimum access needed for assigned tasks', 'NIST least privilege glossary', 'CRM access', 'CRM account maintenance', 'Start with read access, add only task-required writes, and keep exports, administration, deletion, and permission changes owner-controlled.'],
  ['escalation-severity-model', 'Escalation severity model for client account operations', 'Workflow Design', 'A severity model helps an account manager route risk consistently while keeping legal, security, financial, and scope decisions with accountable owners.', 'Six NIST CSF 2.0 functions cover the full risk lifecycle', 'NIST Cybersecurity Framework 2.0', 'escalation severity', 'escalation coordination', 'Define severity by client impact, data exposure, contractual risk, and time sensitivity, then attach an owner and evidence standard.'],
  ['feedback-loop-closure', 'Client feedback loop closure: evidence and follow-up design', 'Scope Benchmarks', 'Feedback becomes operational value when the original words, response, owner, and proof of closure stay connected.', 'ISO quality principles include customer focus and improvement', 'ISO 9001 quality management principles', 'feedback closure', 'customer feedback administration', 'Do not close feedback because a reply was sent; close it when the requested result, owner review, and client-safe record agree.'],
  ['implementation-handoff-risk', 'Implementation handoff risk map for account management teams', 'Workflow Design', 'Handoffs fail when context, access, ownership, and client expectations travel in different records.', 'NIST CSF 2.0 includes identify and protect functions before response and recovery', 'NIST Cybersecurity Framework 2.0', 'handoff risk', 'implementation handoff support', 'A handoff brief should carry the approved scope, current facts, open decisions, access map, client language, and first review date.'],
  ['account-manager-daily-control-rhythm', 'Daily control rhythm for an outsourced account manager', 'Scope Benchmarks', 'A short daily rhythm keeps client requests, risks, approvals, and reporting visible without turning the role into an unrestricted operator.', '68% of surveyed workers reported lacking enough uninterrupted focus time', 'Microsoft Work Trend Index', 'daily control rhythm', 'account health monitoring', 'Use a morning triage, focused work block, owner queue, client-update window, and end-of-day evidence check.'],
  ['account-plan-evidence-map', 'Account plan evidence map for outsourced client teams', 'Scope Benchmarks', 'An account plan is more useful when every objective has a source, owner, status definition, and review date.', 'ISO quality principles emphasize evidence and continual improvement', 'ISO 9001 quality management principles', 'account plan evidence', 'account planning support', 'Map each account objective to evidence, an accountable owner, the next client-safe update, and a close condition.'],
  ['client-meeting-action-register', 'Client meeting action register design and closure controls', 'Workflow Design', 'Meeting notes become operational only when decisions, actions, owners, due dates, and proof of completion remain connected.', 'Accountability is the ability to trace actions to an entity', 'NIST accountability glossary', 'meeting actions', 'client meeting coordination', 'Capture decisions separately from discussion, assign one owner per action, and close only against visible proof.'],
  ['service-level-exception-routing', 'Service-level exception routing for account support', 'Workflow Design', 'Exception routing makes missed expectations visible while preserving the authority boundaries around commitments and remediation.', 'NIST CSF 2.0 organizes response and recovery as distinct functions', 'NIST Cybersecurity Framework 2.0', 'service exceptions', 'service-level reporting', 'Record the expected service, observed exception, client impact, decision owner, and approved next communication.'],
  ['client-communication-approval-matrix', 'Client communication approval matrix for account managers', 'Hiring Controls', 'A communication matrix helps an account manager move quickly on routine updates while reserving sensitive statements for accountable owners.', 'Least privilege limits access to the minimum needed for assigned tasks', 'NIST least privilege glossary', 'communication approval', 'client communication support', 'Classify messages by risk and authority, then define who may prepare, approve, send, and archive each class.'],
  ['account-renewal-risk-register', 'Account renewal risk register with evidence thresholds', 'Scope Benchmarks', 'A renewal risk register should distinguish observed signals from forecasts and show what evidence would change the recommendation.', 'NIST CSF 2.0 separates identification from response', 'NIST Cybersecurity Framework 2.0', 'renewal risk', 'renewal administration', 'Use evidence thresholds for delivery, relationship, scope, data, and timing risks before assigning a renewal status.'],
  ['customer-health-data-dictionary', 'Customer health data dictionary for outsourced reporting', 'Hiring Controls', 'A shared data dictionary prevents the same account field from carrying different meanings across weekly and quarterly reporting.', 'ISO quality principles emphasize a factual approach to decision making', 'ISO 9001 quality management principles', 'health data definitions', 'account reporting', 'Define every health field with its meaning, source, allowed values, owner, freshness rule, and limitation.'],
  ['shared-inbox-triage-controls', 'Shared inbox triage controls for client account requests', 'Workflow Design', 'Shared inboxes need a clear intake, classification, owner, and closure record so urgent messages do not erase important context.', 'FTC guidance recommends access control and data minimization', 'FTC Start with Security', 'inbox triage', 'client request routing', 'Triage by client impact and authority, link each request to the account record, and preserve the final response and owner.'],
  ['account-transition-knowledge-capture', 'Account transition knowledge-capture checklist', 'Workflow Design', 'A transition checklist turns tacit account context into a controlled record that a new owner can review and challenge.', 'SBA guidance supports written processes and record keeping', 'U.S. Small Business Administration, manage your business', 'transition knowledge', 'account transition support', 'Capture current commitments, sources, access boundaries, client preferences, open risks, and the first review date.'],
  ['client-data-retention-routine', 'Client data retention routine for account operations', 'Hiring Controls', 'Retention routines reduce unnecessary exposure by making storage, review, deletion, and exception ownership explicit.', 'Data minimization is a core practical security control', 'FTC Start with Security', 'data retention', 'CRM account maintenance', 'Classify records by purpose and retention rule, keep deletion authority with the owner, and log approved exceptions.'],
  ['monthly-account-review-agenda', 'Monthly account review agenda with decision-ready evidence', 'Scope Benchmarks', 'A monthly review should compress account activity into decisions, risks, commitments, and evidence instead of producing another undifferentiated status report.', 'ISO quality principles connect customer focus with improvement', 'ISO 9001 quality management principles', 'monthly account review', 'account health monitoring', 'Use a fixed agenda covering outcomes, open commitments, risks, client feedback, decisions, and next checks.'],
  ['client-success-metric-governance', 'Client success metric governance for outsourced account reporting', 'Hiring Controls', 'Metric governance keeps account teams from presenting ambiguous or unsupported measures as client outcomes.', 'ISO quality principles call for a factual approach to decision making', 'ISO 9001 quality management principles', 'metric governance', 'account reporting', 'Give each metric a definition, source, owner, time window, calculation note, and approval status before it enters a client report.', '2026-08-09'],
  ['account-portfolio-capacity-review', 'Account portfolio capacity review for outsourced support teams', 'Scope Benchmarks', 'A capacity review connects account workload, service commitments, focus time, and escalation load before coverage gaps become client surprises.', '68% of surveyed workers reported lacking enough uninterrupted focus time', 'Microsoft Work Trend Index', 'portfolio capacity', 'account health monitoring', 'Review workload by account, request type, due date, and authority level, then route capacity decisions to the accountable owner.', '2026-08-09'],
  ['client-outcome-baseline-method', 'Client outcome baseline method for account management', 'Scope Benchmarks', 'A baseline makes later account reporting interpretable by recording the starting condition, scope, date, and evidence limitations.', 'ISO quality principles emphasize customer focus and improvement', 'ISO 9001 quality management principles', 'outcome baselines', 'account reporting', 'Record the baseline fact, measurement method, source, owner, review date, and what the baseline cannot prove.', '2026-08-09'],
  ['account-access-offboarding-checklist', 'Account access offboarding checklist for client support', 'Hiring Controls', 'Offboarding controls close access, transfer ownership, preserve required evidence, and reduce residual exposure when account assignments change.', 'Least privilege limits access to the minimum needed for assigned tasks', 'NIST least privilege glossary', 'access offboarding', 'CRM account maintenance', 'List every approved system, owner the record transfer, revoke unnecessary access, and retain an auditable completion record.', '2026-08-09'],
  ['client-risk-communication-log', 'Client risk communication log with approval controls', 'Workflow Design', 'A risk communication log preserves what was observed, what was approved, who sent it, and what the client should expect next.', 'Accountability is the ability to trace actions to an entity', 'NIST accountability glossary', 'risk communications', 'client communication support', 'Separate internal risk assessment from approved client wording and keep the decision owner attached to sensitive updates.', '2026-08-09'],
  ['account-service-scope-change-register', 'Account service scope change register', 'Hiring Controls', 'A scope change register prevents informal requests from becoming unapproved commitments or hidden workload.', 'SBA guidance supports written processes and record keeping', 'U.S. Small Business Administration, manage your business', 'scope changes', 'account reporting', 'Capture the request, current scope, impact, decision owner, approved wording, effective date, and closure evidence.', '2026-08-09'],
  ['client-data-quality-exception-log', 'Client data-quality exception log for account teams', 'Workflow Design', 'An exception log makes missing, stale, conflicting, or unverified account data visible without silently repairing facts.', 'NIST CSF 2.0 separates identification from response', 'NIST Cybersecurity Framework 2.0', 'data exceptions', 'CRM account maintenance', 'Record the affected field, source conflict, business impact, owner, correction route, and next review date.', '2026-08-09'],
  ['account-review-evidence-retention', 'Account review evidence retention guide', 'Hiring Controls', 'A retention guide keeps review evidence usable for the approved purpose while limiting unnecessary client-data exposure.', 'FTC guidance recommends data minimization', 'FTC Start with Security', 'review evidence retention', 'account reporting', 'Define the record purpose, approved location, retention period, deletion authority, and exception log before collecting review evidence.', '2026-08-09'],
  ['client-escalation-acknowledgment-standard', 'Client escalation acknowledgment standard', 'Workflow Design', 'An acknowledgment standard gives clients a clear first response without implying an unapproved resolution or commitment.', 'NIST CSF 2.0 organizes response and recovery as distinct functions', 'NIST Cybersecurity Framework 2.0', 'escalation acknowledgment', 'escalation coordination', 'Acknowledge receipt, state the next check, name the accountable owner, and avoid promising an outcome before investigation.', '2026-08-09'],
  ['account-review-decision-log', 'Account review decision log for outsourced teams', 'Scope Benchmarks', 'A decision log turns recurring account reviews into traceable choices with evidence, authority, and follow-up.', 'Accountability is the ability to trace actions to an entity', 'NIST accountability glossary', 'review decisions', 'account health monitoring', 'Record the question, evidence considered, decision owner, approved action, boundary, due date, and proof of completion.', '2026-08-09'],
  ['client-commitment-aging-review', 'Client commitment aging review and escalation rules', 'Workflow Design', 'A commitment-aging review surfaces overdue promises early while keeping remediation and commercial decisions with accountable owners.', 'ISO quality principles connect process approach with improvement', 'ISO 9001 quality management principles', 'commitment aging', 'client request routing', 'Age commitments from the source date, classify impact, confirm the work owner, and escalate when the approved threshold is crossed.', '2026-08-09'],
  ['account-coverage-calendar-controls', 'Account coverage calendar controls for outsourced support', 'Workflow Design', 'A coverage calendar makes planned absences, review windows, and client commitments visible before a handoff becomes urgent.', 'Six NIST CSF 2.0 functions organize a complete control lifecycle', 'NIST Cybersecurity Framework 2.0', 'coverage calendar', 'account coverage planning', 'Map each coverage window to an account owner, approved backup, client-safe notice, open commitments, and return check.', '2026-08-10'],
  ['client-approval-aging-dashboard', 'Client approval aging dashboard for account operations', 'Scope Benchmarks', 'Approval aging shows where work is waiting on a decision without mislabeling an unresolved request as completed.', 'Accountability means actions can be traced to an entity', 'NIST accountability glossary', 'approval aging', 'client approval coordination', 'Track the request date, decision needed, approver, impact of delay, next reminder, and evidence of the decision.', '2026-08-10'],
  ['account-contact-record-standard', 'Account contact record standard for client teams', 'Hiring Controls', 'A contact-record standard keeps role, consent, source, freshness, and communication preferences usable across account workflows.', 'FTC guidance recommends data minimization and access control', 'FTC Start with Security', 'contact records', 'CRM account maintenance', 'Store only approved contact data, name its source and purpose, and route changes through the accountable record owner.', '2026-08-10'],
  ['client-deliverable-acceptance-log', 'Client deliverable acceptance log with evidence thresholds', 'Scope Benchmarks', 'An acceptance log separates delivery, review, requested changes, and final owner approval so completion is not inferred from sending a file.', 'ISO quality principles emphasize evidence and continual improvement', 'ISO 9001 quality management principles', 'deliverable acceptance', 'client deliverable coordination', 'Record the approved deliverable, recipient, delivery date, review status, requested changes, and close evidence.', '2026-08-10'],
  ['account-meeting-preparation-brief', 'Account meeting preparation brief for outsourced teams', 'Workflow Design', 'A preparation brief turns prior actions, open risks, and decision requests into a concise, source-linked meeting agenda.', '62% of surveyed workers reported spending too much time searching for information', 'Microsoft Work Trend Index', 'meeting preparation', 'client meeting coordination', 'Assemble only decision-relevant facts, cite each source, identify the meeting owner, and separate prepared questions from approved commitments.', '2026-08-10'],
  ['client-issue-reproduction-record', 'Client issue reproduction record for account support', 'Hiring Controls', 'A reproduction record preserves observable facts and steps without allowing an account role to make unsupported technical or security conclusions.', 'NIST CSF 2.0 separates identification from response', 'NIST Cybersecurity Framework 2.0', 'issue reproduction', 'escalation coordination', 'Capture the report, environment, timestamps, repeatable steps, impact, evidence location, and technical owner for investigation.', '2026-08-10'],
  ['account-priority-review-routine', 'Account priority review routine for competing requests', 'Scope Benchmarks', 'A priority review makes tradeoffs explicit when several client requests compete for the same approved capacity.', '68% of surveyed workers reported lacking enough uninterrupted focus time', 'Microsoft Work Trend Index', 'priority review', 'client request routing', 'Rank requests by client impact, due date, authority, dependencies, and evidence, then route capacity choices to the owner.', '2026-08-10'],
  ['client-duplicate-request-detection', 'Client duplicate-request detection and merge controls', 'Workflow Design', 'Duplicate detection reduces contradictory replies and keeps one accountable record for a request that arrives through several channels.', 'Accountability is the ability to trace actions to an entity', 'NIST accountability glossary', 'duplicate requests', 'client request routing', 'Compare client, topic, source, timing, and status before merging; preserve the source trail and confirm the surviving owner.', '2026-08-10'],
  ['account-service-review-scorecard', 'Account service review scorecard for owner decisions', 'Hiring Controls', 'A service review scorecard connects observable delivery evidence with owner decisions while avoiding unsupported performance promises.', 'ISO quality principles call for a factual approach to decision making', 'ISO 9001 quality management principles', 'service scorecard', 'service-level reporting', 'Define each measure, source, window, limitation, and decision threshold before using it in an account review.', '2026-08-10'],
  ['client-change-impact-register', 'Client change impact register for account managers', 'Workflow Design', 'An impact register shows how an approved change affects timing, scope, dependencies, communications, and evidence.', 'NIST CSF 2.0 includes identify and protect before response and recovery', 'NIST Cybersecurity Framework 2.0', 'change impact', 'implementation handoff support', 'Record the requested change, affected accounts, approved owner, dependencies, client wording, and post-change review date.', '2026-08-10'],
  ['account-report-distribution-controls', 'Account report distribution controls for client data', 'Hiring Controls', 'Distribution controls keep reports with approved recipients, purpose, version, and retention evidence instead of uncontrolled forwarding.', 'Least privilege means minimum access needed for assigned tasks', 'NIST least privilege glossary', 'report distribution', 'account reporting', 'Verify the recipient list, approved channel, report version, sensitivity, and owner before sending or archiving a client report.', '2026-08-10'],
  ['client-briefing-source-register', 'Client briefing source register for account teams', 'Workflow Design', 'A source register makes meeting and update briefs traceable when account facts come from several approved systems.', 'NIST CSF 2.0 begins with identifying organizational context and risk', 'NIST Cybersecurity Framework 2.0', 'briefing sources', 'client meeting coordination', 'List each fact, source, freshness date, owner, and limitation before it enters a client-facing briefing.', '2026-08-10'],
  ['account-task-ownership-matrix', 'Account task ownership matrix for outsourced support', 'Hiring Controls', 'An ownership matrix prevents recurring account tasks from being silently dropped between preparation, approval, execution, and review.', 'Accountability is the ability to trace actions to an entity', 'NIST accountability glossary', 'task ownership', 'account workflow coordination', 'Assign one work owner, one decision owner where needed, a due date, and a completion record to each recurring task.', '2026-08-10'],
  ['client-update-freshness-control', 'Client update freshness controls for account reporting', 'Scope Benchmarks', 'Freshness controls keep account updates honest by showing when a fact was last checked and when it must be reviewed again.', 'ISO quality principles emphasize a factual approach to decision making', 'ISO 9001 quality management principles', 'update freshness', 'client communication support', 'Put source date, checked date, next review, and owner beside each material update before distribution.', '2026-08-10'],
  ['account-open-loop-register', 'Account open-loop register for unresolved client work', 'Workflow Design', 'An open-loop register keeps unresolved requests visible until evidence shows that the owner decision or approved next step is complete.', 'NIST CSF 2.0 separates response from recovery', 'NIST Cybersecurity Framework 2.0', 'open loops', 'client request routing', 'Record the unresolved question, impact, owner, next action, due date, and closure evidence without converting uncertainty into a status label.', '2026-08-10'],
  ['client-record-change-audit', 'Client record change audit for outsourced account operations', 'Hiring Controls', 'A lightweight change audit shows what account data changed, why it changed, who approved it, and how the source was preserved.', 'FTC guidance recommends access control and data minimization', 'FTC Start with Security', 'record changes', 'CRM account maintenance', 'Require a source, reason, actor, timestamp, and owner review for material changes to client records.', '2026-08-10'],
  ['account-approval-escalation-ladder', 'Account approval escalation ladder for time-sensitive work', 'Workflow Design', 'An escalation ladder gives delayed approvals a predictable route without allowing urgency to bypass authority boundaries.', 'NIST CSF 2.0 includes governance, response, and recovery functions', 'NIST Cybersecurity Framework 2.0', 'approval escalation', 'client approval coordination', 'Define reminder intervals, impact thresholds, escalation owners, and client-safe wording before an approval becomes urgent.', '2026-08-10'],
  ['client-report-reconciliation-routine', 'Client report reconciliation routine for account teams', 'Scope Benchmarks', 'Reconciliation compares reported values with approved source records before a client update turns a data mismatch into a credibility issue.', 'ISO quality principles emphasize evidence and improvement', 'ISO 9001 quality management principles', 'report reconciliation', 'account reporting', 'Compare the report version, source fields, time window, calculations, exceptions, and reviewer sign-off before distribution.', '2026-08-10'],
  ['account-handoff-acceptance-check', 'Account handoff acceptance check for support transitions', 'Workflow Design', 'An acceptance check confirms that a new owner has received the approved context, access boundaries, open commitments, and next review date.', 'NIST least privilege guidance supports task-limited access', 'NIST least privilege glossary', 'handoff acceptance', 'account transition support', 'Close a handoff only after the receiving owner confirms context, access, open work, escalation route, and first review.', '2026-08-10'],
  ['client-request-evidence-pack', 'Client request evidence pack for accountable follow-through', 'Hiring Controls', 'An evidence pack makes a request reviewable by collecting the source message, account context, authority, response, and closure proof.', 'Accountability is the ability to trace actions to an entity', 'NIST accountability glossary', 'request evidence', 'client request routing', 'Keep the original request, classification, owner, approved response, decision trail, and closure evidence together.', '2026-08-10'],
  ['account-review-calendar-governance', 'Account review calendar governance for recurring client work', 'Scope Benchmarks', 'Calendar governance turns recurring reviews into owned, prepared, and evidenced events instead of reminders with no accountable outcome.', 'SBA guidance supports written processes and record keeping', 'U.S. Small Business Administration, manage your business', 'review calendar', 'account health monitoring', 'Give each recurring review an owner, preparation deadline, decision agenda, approved attendees, and evidence location.', '2026-08-10'],
  ['account-decision-latency-study', 'Decision latency in outsourced account management: where approvals stall', 'Scope Benchmarks', 'Decision latency analysis separates work that is waiting for facts from work that is waiting for authority, making account delays measurable without blaming the preparer.', 'Accountability is the ability to trace actions to an entity', 'NIST accountability glossary', 'decision latency', 'client approval coordination', 'Measure elapsed time from a decision request to an accountable response, then classify the waiting state by missing evidence, unavailable owner, or unresolved tradeoff.', '2026-08-12'],
  ['client-portfolio-concentration-analysis', 'Client portfolio concentration analysis for account coverage', 'Scope Benchmarks', 'Concentration analysis shows whether a small number of clients, request types, or deadlines can distort account coverage and review quality.', 'ISO quality principles emphasize a factual approach to decision making', 'ISO 9001 quality management principles', 'portfolio concentration', 'account health monitoring', 'Compare account workload and consequence by client, request type, and review window; use the result to inform an owner decision about coverage and sequencing.', '2026-08-12'],
  ['renewal-signal-calibration', 'Renewal signal calibration: separating evidence from forecast', 'Scope Benchmarks', 'Renewal signals become more useful when observed delivery facts, client statements, and forecasts are kept as separate evidence classes.', 'NIST CSF 2.0 separates identification from response', 'NIST Cybersecurity Framework 2.0', 'renewal signal calibration', 'renewal administration', 'Calibrate a renewal view by recording the observed signal, source quality, confidence limit, decision owner, and evidence that would change the forecast.', '2026-08-12'],
  ['account-contact-freshness-analysis', 'Account contact freshness analysis for client communications', 'Hiring Controls', 'Contact freshness analysis identifies stale roles, uncertain consent, and missing source dates before an account update reaches the wrong person.', 'FTC guidance recommends data minimization and access control', 'FTC Start with Security', 'contact freshness', 'CRM account maintenance', 'Assess each material contact field by purpose, source, last verification, communication permission, and accountable record owner.', '2026-08-12'],
  ['cross-system-account-reconciliation', 'Cross-system account reconciliation: finding conflicting client facts', 'Hiring Controls', 'Cross-system reconciliation tests whether the CRM, approved reports, meeting records, and client communications describe the same account state.', 'ISO quality principles emphasize evidence and improvement', 'ISO 9001 quality management principles', 'account reconciliation', 'account reporting', 'Compare field definitions, source timestamps, account identifiers, and owner review before treating a cross-system value as client-ready.', '2026-08-12'],
  ['account-decision-rights-analysis', 'Decision-rights analysis for outsourced account support', 'Hiring Controls', 'Decision-rights analysis clarifies which account activities can be prepared, which can be sent from approved language, and which require owner judgment.', 'Least privilege means minimum access needed for assigned tasks', 'NIST least privilege glossary', 'decision rights', 'account workflow coordination', 'Map each recurring account action to its preparation access, approval authority, communication permission, and evidence-retention owner.', '2026-08-12'],
  ['service-recovery-evidence-analysis', 'Service recovery evidence analysis for client account issues', 'Workflow Design', 'Service recovery analysis tests whether an issue record proves what happened, who owned the response, and what the client was authorized to expect next.', 'NIST CSF 2.0 organizes response and recovery as distinct functions', 'NIST Cybersecurity Framework 2.0', 'service recovery evidence', 'escalation coordination', 'Separate the observed failure, impact assessment, approved remediation, client communication, and post-resolution evidence so recovery is not inferred from a reply.', '2026-08-12'],
  ['account-segmentation-evidence', 'Account segmentation evidence: grouping clients without guesswork', 'Scope Benchmarks', 'Account segmentation is defensible when each segment has an explicit purpose, measurable criteria, source fields, and a review limit.', 'ISO quality principles call for a factual approach to decision making', 'ISO 9001 quality management principles', 'account segmentation', 'account health monitoring', 'Define segments from observable account characteristics, document exclusions and limitations, and keep commercial or service decisions with the accountable owner.', '2026-08-12'],
  ['handoff-information-loss-analysis', 'Handoff information-loss analysis for account transitions', 'Workflow Design', 'Information-loss analysis reveals which facts, decisions, access boundaries, and client expectations disappear between account owners.', 'SBA guidance supports written processes and record keeping', 'U.S. Small Business Administration, manage your business', 'handoff information loss', 'account transition support', 'Compare the outgoing record with the receiving owner’s confirmed understanding and classify each gap as missing source, unclear authority, stale status, or unresolved decision.', '2026-08-12'],
  ['meeting-to-action-conversion-study', 'Meeting-to-action conversion study for client account reviews', 'Workflow Design', 'A conversion study measures whether client meetings produce owned decisions and verifiable next steps rather than notes that merely describe discussion.', 'Accountability is the ability to trace actions to an entity', 'NIST accountability glossary', 'meeting-to-action conversion', 'client meeting coordination', 'Count decisions, actions, owners, due dates, and closure evidence separately, then investigate where meeting output loses accountability.', '2026-08-12'],
];

const august13Topics = [
  ['account-briefing-completeness-study', 'Account briefing completeness: testing whether client updates are decision-ready', 'Scope Benchmarks', 'A briefing is decision-ready only when its claims, dates, owners, and unresolved questions can be checked without reconstructing the account history.', 'ISO 9001 emphasizes evidence-based decision making', 'ISO 9001 quality management principles', 'briefing completeness', 'client meeting coordination', 'Test briefings for source coverage, temporal freshness, decision ownership, and explicit uncertainty before they reach a client meeting.', '2026-08-13'],
  ['client-commitment-aging-analysis', 'Client commitment aging analysis for outsourced account management', 'Scope Benchmarks', 'Commitment aging distinguishes ordinary elapsed time from overdue work, waiting states, and promises that lack an accountable owner.', 'NIST accountability links actions to an entity', 'NIST accountability glossary', 'commitment aging', 'account health monitoring', 'Measure each commitment from agreed date to verified closure, while separating client dependency, owner dependency, and missing evidence.', '2026-08-13'],
  ['account-source-freshness-benchmark', 'Account source freshness benchmark for client reporting', 'Hiring Controls', 'Source freshness is a measurable property of account reporting: a fact can be accurate when captured yet unsafe to reuse after its business context changes.', 'NIST CSF 2.0 begins with understanding organizational context and risk', 'NIST Cybersecurity Framework 2.0', 'source freshness', 'account reporting', 'Set freshness windows by field purpose and consequence, then show stale evidence as a limitation rather than silently presenting it as current.', '2026-08-13'],
  ['client-expectation-alignment-analysis', 'Client expectation alignment analysis for account teams', 'Workflow Design', 'Expectation alignment compares what was agreed, what was understood, and what the record can prove before a service gap becomes a relationship problem.', 'ISO 9001 places customer focus alongside process improvement', 'ISO 9001 quality management principles', 'expectation alignment', 'client communication support', 'Compare approved scope, client language, delivery evidence, and unresolved assumptions; route any commitment change to the accountable owner.', '2026-08-13'],
  ['account-risk-evidence-thresholds', 'Account risk evidence thresholds: when a signal warrants escalation', 'Hiring Controls', 'Evidence thresholds keep account risk labels proportional to observable impact, source quality, and decision consequence.', 'NIST CSF 2.0 separates identification, response, and recovery', 'NIST Cybersecurity Framework 2.0', 'risk evidence thresholds', 'escalation coordination', 'Define what must be observed before each risk level is assigned and what evidence can downgrade, sustain, or escalate the finding.', '2026-08-13'],
  ['client-approval-queue-analysis', 'Client approval queue analysis for delayed account decisions', 'Workflow Design', 'Approval queue analysis reveals where account work waits for authority, facts, or client clarification instead of treating every delay as the same problem.', 'NIST accountability supports traceable responsibility', 'NIST accountability glossary', 'approval queues', 'client approval coordination', 'Classify waiting time by dependency and consequence, then make the next owner action visible without bypassing approval boundaries.', '2026-08-13'],
  ['account-report-narrative-integrity', 'Account report narrative integrity: keeping conclusions tied to evidence', 'Hiring Controls', 'Narrative integrity checks whether a client report says more than its source data can support.', 'ISO 9001 calls for a factual approach to decisions', 'ISO 9001 quality management principles', 'narrative integrity', 'account reporting', 'Separate observation, interpretation, forecast, and recommendation so a polished account narrative does not turn uncertainty into a promise.', '2026-08-13'],
  ['client-escalation-response-quality', 'Client escalation response quality: measuring the first accountable reply', 'Workflow Design', 'The first escalation reply should acknowledge the issue, set the next check, and preserve authority boundaries without implying a premature resolution.', 'NIST CSF 2.0 treats response and recovery as distinct functions', 'NIST Cybersecurity Framework 2.0', 'response quality', 'escalation coordination', 'Assess first replies for factual accuracy, ownership, timing, approved language, and the absence of unsupported commitments.', '2026-08-13'],
  ['account-review-sample-design', 'Account review sample design for outsourced portfolios', 'Scope Benchmarks', 'A review sample is useful only when its selection logic reflects account consequence, variation, and known evidence gaps.', 'ISO 9001 supports evidence-based improvement', 'ISO 9001 quality management principles', 'review sampling', 'account health monitoring', 'Choose samples by risk and coverage purpose, record exclusions, and avoid treating a small convenient sample as a portfolio-wide finding.', '2026-08-13'],
  ['client-data-minimization-analysis', 'Client data minimization analysis for account support', 'Hiring Controls', 'Data minimization asks whether each account field is necessary for an approved purpose, accessible to the right role, and retained for a justified period.', 'FTC guidance recommends data minimization and access control', 'FTC Start with Security', 'data minimization', 'CRM account maintenance', 'Map purpose, sensitivity, access, retention, and deletion authority before collecting or copying client information.', '2026-08-13'],
];

const august13Sections = (label: string, service: string, thesis: string, topic: string): ResearchSection[] => [
  { heading: `Research question: what does ${label} prove?`, paragraphs: [
    `${thesis} The central unit of analysis is one account record at one review point, not a general impression of service quality. A reviewer should be able to identify the claim, the source record, the date observed, the person responsible for the next decision, and the condition that would change the conclusion. This makes the finding useful to an account owner without turning a limited observation into a company-wide performance claim.`,
    `For ${service}, begin by stating the decision the evidence is meant to support. A briefing may support a meeting question; an approval queue may support an escalation; a data-minimization review may support deletion or access restriction. If no decision is named, the record tends to accumulate descriptive detail without showing why the detail matters.`
  ] },
  { heading: 'Define the observation before interpreting it', paragraphs: [
    `An observation should describe what was present in the approved account record during a defined period. It should not blend an email excerpt, a remembered conversation, and a later interpretation into one sentence. Record the source type, capture date, account identifier, and relevant time window. If a value came from a client statement, preserve the statement as a statement rather than recasting it as independently verified fact.`,
    `Interpretation comes after the observation. The same missing date can mean an ordinary documentation gap, a delayed decision, or a material risk depending on the commitment, client impact, and authority involved. That distinction matters for ${topic}: a measured field is not automatically a service outcome, and a red flag is not automatically proof of cause.`
  ] },
  { heading: 'Use a bounded measurement design', paragraphs: [
    `A practical measurement design names the population, inclusion rule, period, unit, and denominator. For example, count client commitments opened during a calendar month and calculate the share with a named owner and a verified closure record. Do not combine completed and canceled items unless the purpose is to study disposition. Keep client-caused waiting separate from internal owner waiting when elapsed time is the result being examined.`,
    `The measure should also record missingness. If ten of forty account records lack a source date, the result is not simply a percentage with lower confidence; the missingness may itself explain why the account view is unreliable. Report the number inspected, the number excluded, and the reason for each exclusion. This prevents a clean-looking result from hiding weak evidence.`
  ] },
  { heading: 'Separate work ownership from decision authority', paragraphs: [
    `An outsourced account manager may gather approved facts, prepare a comparison, update an assigned record, draft an update from approved language, and route a question. The role should not independently change contractual scope, approve refunds or financial commitments, make legal or security determinations, administer broad access, or promise delivery that an accountable owner has not approved. The boundary is part of the finding, not an afterthought.`,
    `For each material item, name the work owner and the decision owner separately when they differ. Then state the evidence the decision owner needs: a source link, a client statement, a time calculation, a permission review, or a record of the approved wording. This arrangement supports fast preparation while keeping consequential choices with the person authorized to make them.`
  ] },
  { heading: 'Check freshness and source quality', paragraphs: [
    `Freshness is not one universal number. A contact role, open commitment, access grant, and monthly outcome may each need a different review window because their consequences differ. Record when the source was last checked, when the field is expected to be checked again, and what event triggers an earlier review. Mark an expired window as a limitation; do not quietly substitute a newer-looking assumption.`,
    `Source quality has several dimensions: authority, specificity, completeness, and traceability. A signed approval may be authoritative for scope but irrelevant to current delivery status. A meeting note may describe a concern but not establish its technical cause. A useful analysis keeps these distinctions visible so the reader knows what the evidence can and cannot support.`
  ] },
  { heading: 'Analyze failure modes, not just missing fields', paragraphs: [
    `Missing evidence can arise from different causes: the source was never created, the source exists in an unapproved location, the owner was unclear, the record was not updated after a change, or the evidence was intentionally withheld because authority was unresolved. Each cause needs a different response. A field-completion score alone cannot tell those cases apart and may reward copying information into a system without improving accountability.`,
    `For ${label}, test at least one negative case and one ambiguous case. A negative case has a clear missing or overdue condition. An ambiguous case has conflicting sources or a client statement that requires owner confirmation. Recording how the reviewer resolved—or deliberately did not resolve—the ambiguity gives the analysis more value than a binary pass label.`
  ] },
  { heading: 'Translate findings into a decision-ready record', paragraphs: [
    `A decision-ready record contains the finding, evidence, impact, uncertainty, recommended next question, accountable owner, and next review date. The recommendation should be framed as an option or request for decision when authority is not delegated. It should never imply that preparation access grants permission to commit the company or speak for the client.`,
    `For account management services, the handoff should preserve the original source and the approved client-safe wording. A later reviewer should be able to see whether the item was acknowledged, investigated, approved, communicated, and closed. A sent message is evidence of communication, not proof that the underlying issue was resolved.`
  ] },
  { heading: 'Limitations and interpretation', paragraphs: [
    `This analysis describes a control and evidence approach; it does not claim that every account has the same operating context or that a single review predicts retention, revenue, or client satisfaction. Account size, contract terms, system design, geography, and client reporting expectations can change the meaning of the same field. Any comparison should state those boundaries before it is used for staffing or service decisions.`,
    `External guidance supplies principles rather than an OutsourcedAccountManagement.com benchmark. NIST, FTC, SBA, and ISO materials help frame governance, accountability, security, customer focus, and improvement, but they do not establish a result for a particular account portfolio. Treat the citations as sources for the method and the limitation, then collect local evidence before drawing an operational conclusion.`
  ] },
  { heading: 'Conclusion', paragraphs: [
    `The strongest ${label} finding is modest and testable: it states what was observed, during which period, from which source, with what uncertainty, and who can decide what happens next. That discipline makes account support easier to review because it keeps evidence, interpretation, and authority in separate lanes.`,
    `Use the result to improve the quality of client-facing decisions in ${service}. Preserve the source trail, show stale or missing evidence plainly, and revisit the conclusion when the defined trigger occurs. The goal is not a perfect record; it is a record that helps the accountable owner make a better bounded decision.`
  ] },
];

const august13Posts: ResearchPost[] = august13Topics.map(([slug, title, cluster, excerpt, headlineStat, statSource, label, service, thesis, articleDate]) => ({
  slug, title, cluster, excerpt, headlineStat, statSource, published: articleDate, updated: articleDate,
  takeaways: [thesis, `Keep ${label} evidence tied to a source, time window, work owner, and decision owner where authority matters.`, 'Report limitations and unresolved questions instead of converting incomplete evidence into a confident status label.'],
  sections: august13Sections(label, service, thesis, title),
  table: { headers: ['Evidence element', 'Required record', 'Interpretation limit'], rows: [['Observation', 'Source, account, period, and exact fact', 'Does not establish cause by itself'], ['Ownership', 'Work owner and decision owner', 'Preparation is not approval'], ['Freshness', 'Checked date and next review trigger', 'Expired evidence is a limitation'], ['Conclusion', 'Finding, uncertainty, and next decision', 'Not a portfolio-wide guarantee']] },
  sources: sources.map(s => ({...s})),
  faqs: [{ q: `What is the first review step for ${label}?`, a: 'State the decision, population, time window, source records, and evidence exclusions before interpreting the findings.' }, { q: 'What should remain with the accountable owner?', a: 'Contract scope, financial commitments, legal or security judgments, access administration, and any promise outside approved authority.' }, { q: 'What makes the conclusion defensible?', a: 'A dated source trail, explicit uncertainty, a named decision owner, and a clear condition for reopening the finding.' }],
  related: [], internalLinks: [{label: `See ${service} support`, href: `/services/${service}`}, {label: 'Read account reporting support', href: '/services/account-reporting'}],
}));

export const researchPosts: ResearchPost[] = [...august13Posts, ...topics.map(([slug, title, cluster, excerpt, headlineStat, statSource, label, service, thesis, articleDate], i) => {
  const related = topics.filter(t => t[0] !== slug).slice(i % 7, i % 7 + 3).map(t => t[0]);
  return {
    slug, title, cluster, excerpt, headlineStat, statSource, published: articleDate || '2026-08-07', updated: articleDate || '2026-08-07',
    takeaways: [thesis, `Keep ${label} evidence in the account record, with one work owner and a separate decision owner when authority matters.`, `Review the record on a fixed cadence and escalate gaps rather than hiding them in a green status.`],
    sections: [
      { heading: `What the ${label} evidence should show`, paragraphs: [`The useful unit is not a promise that work is under control; it is a dated record showing the source fact, current state, accountable owner, and next check. For ${service}, start with the smallest set of fields that lets an owner understand what changed and what still needs a decision.`, `${headlineStat} is a context signal, not a performance claim about this company or a Philippines-based team. Keep the source, publication date, population, and limitation beside the number so it cannot be mistaken for an internal result.`] },
      { heading: 'Separate preparation from authority', paragraphs: [`A Philippines-based account manager can collect facts, update assigned records, prepare a draft, route a request, and remind an owner. Contract changes, discounts, refunds, legal statements, security exceptions, access administration, and work outside scope require the named business owner.`, `Write the boundary into the workflow. A task should say whether the person may prepare, send an approved message, or only queue the item for review. That makes a fast handoff safer than an informal instruction in chat.`] },
      { heading: 'Use a repeatable review loop', paragraphs: [`Review ${label} on a fixed cadence: inspect the source, check the owner, confirm the due date, record the next client update, and link the proof. If a field is missing, mark the item incomplete and route it to the person who can supply it.`, `Use evidence from the approved system rather than memory. Microsoft reports that 62% of surveyed workers struggled with search time and 68% lacked uninterrupted focus time; this is workplace context, not an account-management benchmark, but it reinforces the value of one usable record.`] },
      { heading: 'Protect client information', paragraphs: [`Apply least privilege and data minimization to ${label}. Give access only to the records required for assigned work, use named accounts, avoid uncontrolled exports, and remove access when the assignment ends.`, `The Philippine Data Privacy Act is part of the local context for personal information systems. Ask the accountable owner to confirm the approved tools, retention rules, incident route, and access-review cadence before the work begins.`] },
      { heading: 'Turn findings into an owner decision', paragraphs: [`A report is useful when it ends with a decision-ready queue: what is known, what is not known, what changed, who can decide, and when the next update will be sent. Avoid an unsupported “healthy” or “at risk” label without the evidence behind it.`, `Use the findings to improve the routine, not to create a new uncontrolled promise. Record the chosen action, its limit, its owner, and the proof required to close it.`] },
    ],
    table: { headers: ['Control field', 'Minimum evidence', 'Owner check'], rows: [['Source', 'Link, date, and exact fact', 'Can another person reproduce it?'], ['Status', 'Current state and last checked time', 'Does it reflect the source record?'], ['Authority', 'Work owner and decision owner', 'Is approval scope explicit?'], ['Next update', 'Date, channel, and expected proof', 'Will the client know what happens next?']] },
    sources: sources.map(s => ({...s})),
    faqs: [
      { q: `What is the first step in ${label}?`, a: `Define the source record, the minimum fields, and the owner who reviews the result. Then test the routine on a small set of real accounts.` },
      { q: 'What should an outsourced account manager not decide?', a: 'The role should not independently change contracts, approve money movement or refunds, make legal or security judgments, administer broad access, or promise work outside scope.' },
      { q: 'How do we know the record is complete?', a: 'A complete record has a source, date, current state, named work owner, decision owner where needed, next update, and linked proof of closure.' },
    ],
    related,
    internalLinks: [{label: `See ${service} support`, href: `/services/${service}`}, {label: 'Read account reporting support', href: '/services/account-reporting'}],
  };
}).sort((a, b) => b.published.localeCompare(a.published))];
