import type { RichArticle } from './rich-articles';

type Topic = readonly [string, string, string, string, string, string];
const topics: Topic[] = [
  ['daily-account-priority-reset', 'Daily account priority reset', 'account-health-monitoring', 'rebuild the day’s queue from current client consequence instead of yesterday’s urgency', 'account, triggering change, consequence, evidence, owner, and review time', '2026-08-31-portfolio-exception-budget.png'],
  ['client-question-evidence-envelope', 'Client question evidence envelope', 'client-request-routing', 'hold the exact question and its supporting records together until an approved answer is ready', 'client wording, source links, known facts, unknowns, approver, and reply deadline', '2026-08-31-client-silence-follow-up-rule.png'],
  ['renewal-decision-clock', 'Renewal decision clock', 'renewal-administration', 'make every time-sensitive renewal choice visible before a notice or approval window closes', 'decision, contractual date, preparation lead time, owner, evidence cutoff, and escalation trigger', '2026-08-31-renewal-evidence-freeze.png'],
  ['qbr-claim-to-source-index', 'QBR claim-to-source index', 'customer-qbr-preparation', 'connect every material review statement to the dated evidence that supports its limited meaning', 'claim, metric definition, period, source, limitation, and approving owner', '2026-08-31-qbr-question-backlog.png'],
  ['crm-change-impact-trace', 'CRM change impact trace', 'crm-account-maintenance', 'show which reports, messages, and decisions must be rechecked after a material field changes', 'changed field, former value, new source, affected outputs, reviewer, and completion proof', '2026-08-31-crm-correction-provenance-log.png'],
  ['portfolio-review-recovery-queue', 'Portfolio review recovery queue', 'account-health-monitoring', 'restore missed account reviews in consequence order without hiding the original gap', 'missed review, reason, client effect, interim control, recovery owner, and verified date', '2026-08-31-portfolio-exception-budget.png'],
  ['escalation-decision-expiry-note', 'Escalation decision expiry note', 'escalation-coordination', 'prevent an old escalation approval from governing facts or consequences that have changed', 'approved decision, source snapshot, expiry condition, current evidence, decision owner, and next update', '2026-08-31-escalation-audience-map.png'],
  ['client-reporting-cutoff-register', 'Client reporting cutoff register', 'account-reporting', 'make the evidence boundary of every client report explicit before drafting begins', 'report, coverage period, source cutoff, late evidence rule, approver, and release date', '2026-08-31-client-decision-expiry-register.png'],
  ['handoff-rejection-resolution-log', 'Handoff rejection resolution log', 'implementation-handoff-support', 'turn a rejected handoff into an owned correction path instead of an informal return', 'rejected item, acceptance rule, missing proof, correction owner, resubmission date, and acceptance evidence', '2026-08-31-handoff-shadow-review.png'],
  ['contract-obligation-source-card', 'Contract obligation source card', 'contract-milestone-tracking', 'keep operational tracking anchored to the controlling obligation and its interpretation owner', 'obligation text, controlling document, effective period, operational translation, owner, and review trigger', '2026-08-31-client-commitment-sunset-review.png'],
  ['service-recovery-client-proof-pack', 'Service recovery client proof pack', 'escalation-coordination', 'assemble the evidence needed to show what was corrected without overstating recovery', 'incident boundary, approved remedy, execution proof, verification result, limitation, and client-safe update', '2026-08-31-service-credit-preparation-boundary.png'],
  ['stakeholder-delegation-boundary-card', 'Stakeholder delegation boundary card', 'client-onboarding-coordination', 'state what a temporary delegate may decide while the usual stakeholder is unavailable', 'delegate, effective window, allowed decisions, exclusions, evidence requirement, and return handback', '2026-08-31-stakeholder-absence-plan.png'],
];

const sources = [
  { name: 'NIST Cybersecurity Framework 2.0', date: 'February 26, 2024', url: 'https://www.nist.gov/publications/cybersecurity-framework-csf-20', note: 'Governance and control vocabulary; not an account-performance benchmark.' },
  { name: 'ISO quality management principles', date: 'accessed September 2, 2026', url: 'https://www.iso.org/quality-management/principles', note: 'Supports evidence-based decisions and improvement.' },
  { name: 'NIST accountability glossary', date: 'accessed September 2, 2026', url: 'https://csrc.nist.gov/glossary/term/accountability', note: 'Supports traceable actions and ownership.' },
];

function make([short, name, service, purpose, fields, image]: Topic): RichArticle {
  const subject = name.toLowerCase();
  return {
    title: `Philippines account management ${subject}`,
    description: `Published September 2, 2026: a practical routine to ${purpose}.`, published: '2026-09-02', updated: '2026-09-02', readMinutes: 12, heroImage: `/blog-heroes/${image}`,
    intro: [`Published September 2, 2026. A ${subject} helps a Philippines-based account team ${purpose}.`, `The working record should contain ${fields}. The distinctive test for this routine is simple: can a new reviewer reproduce the next action without relying on private memory?`],
    takeaways: [`Record ${fields}.`, `Tie the ${subject} to one client consequence and one decision.`, 'Keep preparation, approval, communication, verification, and closure as separate states.', 'Route commercial, legal, security, privacy, access, and scope choices to authorized owners.'],
    sections: [
      { heading: `Define the job of the ${subject}`, paragraphs: [`Write the account, operating window, triggering event, client consequence, and decision this record supports. Its job is to ${purpose}. Anything unrelated belongs in a separate record with its own owner.`, `Capture ${fields}. Label missing evidence as unknown and assign the smallest source check that can resolve it. This prevents a plausible recollection from becoming an operational fact.`] },
      { heading: 'Bind each statement to evidence', paragraphs: [`Link the controlling CRM record, agreement, approved message, meeting decision, or delivery artifact beside the fact it supports. Preserve the source date and relevant limitation; a source may be authoritative for scope but unable to prove current delivery.`, `For this ${subject}, retain conflicting sources rather than silently selecting one. Name the reconciliation owner, affected action, and rule used to determine which source controls.`] },
      { heading: 'Use observable workflow states', paragraphs: [`Use states such as captured, checking evidence, ready for decision, approved to communicate, awaiting response, verifying, and closed. Define the evidence needed to enter and leave each state.`, `A draft is not an approval, a sent message is not acceptance, and a completed task is not proof of the intended client outcome. The ${subject} should keep those distinctions visible.`] },
      { heading: 'Separate work from decision authority', paragraphs: [`A Philippines-based specialist may gather approved facts, maintain this record, prepare neutral wording, and route an exception. That does not authorize changes to terms, money, legal positions, security controls, access, or service scope.`, `Name the work owner and decision owner separately. If authority is delegated, record the exact decision class, effective window, exclusions, and expiry trigger.`] },
      { heading: 'Prepare the next client update', paragraphs: [`When the final answer is pending, say what was received, what is confirmed, what remains open, who owns the decision, and when the next approved update will arrive. Avoid reassurance that outruns the evidence.`, `Before sending, compare the message with the current ${subject}. Save the approved version and any client correction so the record and conversation remain aligned.`] },
      { heading: 'Protect access and history', paragraphs: [`Use named accounts and task-matched permissions. Link controlled evidence instead of copying sensitive client data into a broad note.`, `Append material corrections with the editor, date, source, reviewer, and affected downstream work. Silent rewriting would erase why an earlier action appeared reasonable.`] },
      { heading: 'Review the control in practice', paragraphs: [`During the daily scan, inspect new triggers and missed checks. Weekly, sample one routine item, one consequential exception, and one closed item for source quality, authority, communication, and outcome proof.`, `Ask a teammate to reconstruct the current decision from the record. Any coaching they require identifies a field, definition, or source link that needs improvement.`] },
      { heading: 'Close and define reopening', paragraphs: [`Close only when the stated action happened, the authorized owner accepted the result, required communication was sent, and the evidence meets the rule written at intake.`, `Set a route-specific reopening trigger: changed evidence, client correction, expired approval, failed verification, or a new consequence. That makes this ${subject} a durable operating control.`] },
    ],
    banners: [{ label: 'Evidence', title: 'Preserve the source boundary', body: 'Facts need dated, reviewable support.', href: `/services/${service}`, link: 'See related support' }, { label: 'Authority', title: 'Route the decision', body: 'Preparation does not grant approval.', href: '/services/account-reporting', link: 'See reporting support' }, { label: 'Closure', title: 'Verify the intended result', body: 'Define proof before closing.', href: '/contact-us', link: 'Contact Us' }],
    table: { caption: `${name} minimum control record`, headers: ['Layer', 'Required entry', 'Reviewer question'], rows: [['Boundary', 'Account, event, consequence', 'What decision is supported?'], ['Evidence', 'Source, date, limitation', 'Can the fact be reproduced?'], ['Authority', 'Work and decision owners', 'Who may approve the next step?'], ['Outcome', 'Close proof and reopen trigger', 'What would change this status?']] },
    chart: [{ label: 'Evidence', value: 100, color: '#e8c98e' }, { label: 'Authority', value: 75, color: '#b9dfce' }, { label: 'Outcome', value: 50, color: '#ffd9ce' }], chartMeta: { title: `${name} control path`, desc: 'Evidence, authority, and outcome form the review path.', heading: 'Three review layers', method: 'Process illustration, not measured performance.' },
    quote: { text: 'Accountability allows actions to be traced to an entity.', source: 'NIST accountability glossary', url: 'https://csrc.nist.gov/glossary/term/accountability' },
    script: [`We reviewed ${subject} against [source] on [date]. The confirmed fact is [fact]; [owner] is deciding [open issue].`, 'The next approved update is due [date]. We will close only when [route-specific proof] is available.'],
    faqs: [{ q: `What belongs in a ${subject}?`, a: `At minimum: ${fields}, plus the client consequence and closure rule.` }, { q: 'Who approves consequential action?', a: 'The named authorized owner approves commercial, legal, security, access, privacy, and scope decisions.' }, { q: 'What makes closure credible?', a: 'Evidence that matches the intake rule, owner acceptance, required communication, and a defined reopening trigger.' }], sources,
  };
}

export const september2BlogPosts = topics.map(t => ({ slug: `philippines-account-management-${t[0]}`, title: `Philippines account management ${t[1].toLowerCase()}`, published: '2026-09-02' as const, excerpt: `A September 2, 2026 guide to ${t[3]}.`, minutes: 12 }));
export const september2RichArticles: Array<[string, RichArticle]> = topics.map(t => [`philippines-account-management-${t[0]}`, make(t)]);
