import type { RichArticle } from './rich-articles';

export type SeptemberBlogTopic = readonly [string,string,string,string,string,string,string];
type Topic = SeptemberBlogTopic;
const topics: Topic[] = [
  ['client-meeting-decision-receipt','Client meeting decision receipt','customer-qbr-preparation','turn a meeting decision into an acknowledged, owned action','decision wording, source note, accountable owner, recipient, acknowledgement, due date, and completion proof','A meeting can end with agreement while each attendee leaves with a different version of the decision.','2026-08-31-qbr-question-backlog.png'],
  ['renewal-assumption-expiry-board','Renewal assumption expiry board','renewal-administration','surface renewal assumptions before their evidence goes stale','assumption, supporting source, owner, expiry trigger, commercial consequence, and next review','Renewal work becomes fragile when last quarter’s assumption quietly survives into today’s forecast.','2026-08-31-renewal-evidence-freeze.png'],
  ['account-contact-authority-check','Account contact authority check','crm-account-maintenance','verify who may approve which client-side decisions','contact, confirmed role, decision class, source, effective date, limit, and reconfirmation trigger','A familiar client contact is not automatically the right approver for every request.','2026-08-31-stakeholder-absence-plan.png'],
  ['escalation-evidence-cutoff-note','Escalation evidence cutoff note','escalation-coordination','anchor a sensitive update to a precise evidence window','incident state, evidence cutoff, verified facts, unresolved facts, approver, next check, and client wording','An escalation update can become inaccurate between drafting and sending.','2026-08-31-escalation-audience-map.png'],
  ['client-request-duplicate-merge','Client request duplicate merge','client-request-routing','join duplicate requests without losing their separate promises or recipients','request sources, received times, promised replies, owners, affected contacts, merge rationale, and closure proof','Two messages about the same need may carry different deadlines and promises.','2026-08-31-client-silence-follow-up-rule.png'],
  ['portfolio-risk-review-trigger','Portfolio risk review trigger','account-health-monitoring','open a focused review when a defined account signal changes','trigger, threshold, source, observation time, affected account, reviewer, and disposition','Risk reviews work better when a visible trigger opens them instead of intuition alone.','2026-08-31-portfolio-exception-budget.png'],
  ['qbr-claim-approval-lane','QBR claim approval lane','customer-qbr-preparation','route each client-facing performance claim to the right approver','claim, metric definition, source window, calculation, limitation, approver, and approved wording','A polished QBR sentence may outrun the metric behind it.','2026-08-31-client-metric-definition-card.png'],
  ['handoff-open-loop-inventory','Handoff open-loop inventory','implementation-handoff-support','carry unresolved commitments through an ownership change','open loop, origin, current evidence, client expectation, work owner, decision owner, and next update','The quietest handoff risk is an open loop that appears in neither owner’s queue.','2026-08-31-handoff-shadow-review.png'],
  ['service-scope-question-register','Service scope question register','contract-milestone-tracking','hold ambiguous requests for an authorized scope decision','request, contract reference, ambiguity, interim response, decision owner, decision date, and outcome','Helpful teams can accidentally turn an unclear request into an unauthorized commitment.','2026-08-31-service-credit-preparation-boundary.png'],
  ['client-update-correction-trail','Client update correction trail','account-reporting','correct a client update while preserving what changed and why','original statement, corrected fact, source, impact, approver, recipients, and correction time','A correction is easier to trust when the old statement and the reason for change remain visible.','2026-08-31-crm-correction-provenance-log.png'],
  ['account-coverage-acceptance-check','Account coverage acceptance check','account-health-monitoring','confirm that temporary coverage actually transferred usable context','coverage period, accounts, decisions, open risks, client messages, returning owner, and acceptance','Temporary coverage is not complete merely because the calendar owner changed back.','2026-08-31-stakeholder-absence-plan.png'],
  ['client-commitment-reopen-rule','Client commitment reopen rule','contract-milestone-tracking','define when new evidence should reopen a closed commitment','commitment, closure evidence, acceptance condition, reopen trigger, review owner, client consequence, and next action','Closed should describe evidence, not the desire to clear a queue.','2026-08-31-client-commitment-sunset-review.png'],
];
const sources=[
  {name:'NIST Cybersecurity Framework 2.0',date:'February 26, 2024',url:'https://www.nist.gov/publications/cybersecurity-framework-csf-20',note:'Governance and review vocabulary; it is not an account-performance benchmark.'},
  {name:'ISO quality management principles',date:'accessed September 7, 2026',url:'https://www.iso.org/quality-management/principles',note:'Process, evidence-based decision, and improvement principles.'},
  {name:'NIST accountability glossary',date:'accessed September 7, 2026',url:'https://csrc.nist.gov/glossary/term/accountability',note:'Traceable responsibility vocabulary.'},
];
export function makeSeptemberBlogArticle([short,name,service,purpose,fields,opening,image]:Topic, published='2026-09-07'):RichArticle{
  const subject=name.toLowerCase();
  const readerDate = new Intl.DateTimeFormat('en-US',{timeZone:'UTC',month:'long',day:'numeric',year:'numeric'}).format(new Date(`${published}T00:00:00Z`));
  return {title:`Philippines account management ${subject}`,description:`A ${readerDate} field guide to ${purpose}.`,published,updated:published,readMinutes:11,heroImage:`/blog-heroes/${image}`,
    intro:[`Published ${readerDate}. ${opening} A ${subject} gives a Philippines-based account team a controlled way to ${purpose}.`,`The working record contains ${fields}. It should let a second reviewer reconstruct the state without relying on a private retelling.`],
    takeaways:[`Record ${fields}.`,'Keep source facts separate from interpretations and decisions.','Name both the work owner and the authorized decision owner.','Close against observable proof and retain a specific reopen condition.'],
    sections:[
      {heading:`Define the job of the ${subject}`,paragraphs:[`Start with the account event and the decision or client update this record must support. Its purpose is to ${purpose}; unrelated work belongs in another record.`,`Write the entry condition and the consequence of delay. That makes priority review possible without turning urgency into authority.`]},
      {heading:'Keep the source beside the claim',paragraphs:[`Link the approved CRM entry, agreement, delivery record, meeting note, or client message beside the fact it supports. Record the observation date and any limit on what the source can establish.`,`If two sources disagree, preserve both and assign a reconciliation owner. Do not silently choose the easier version.`]},
      {heading:'Use states another person can test',paragraphs:[`Use observable states such as captured, checking, awaiting decision, approved to communicate, verifying, and closed. Define the evidence required to leave each state.`,`A sent message is not acknowledgement, and claimed completion is not acceptance. The ${subject} should keep those distinctions visible.`]},
      {heading:'Separate preparation from authority',paragraphs:[`A Philippines-based specialist may assemble approved facts, maintain the record, draft neutral wording, and route an exception. Contract, pricing, legal, security, privacy, access, and out-of-scope choices remain with authorized owners.`,`Temporary authority needs a written decision class, start date, end date, and exclusions. A role title alone does not prove permission.`]},
      {heading:'Prepare the next client-safe update',paragraphs:[`When the answer is open, say what was received, what is confirmed, who owns the remaining decision, and when the next approved update is due.`,`Compare the draft with the latest source record immediately before sending. Save the approved message and preserve any later correction.`]},
      {heading:'Run a reconstruction check',paragraphs:[`Ask a teammate to reconstruct the current state, authority, client consequence, and next action from the record alone. Treat every needed verbal explanation as a missing field or unclear definition.`,`Sample ordinary, delayed, disputed, and reopened cases. A routine that works only on clean examples is not ready for live account work.`]},
      {heading:'Close without erasing uncertainty',paragraphs:[`Close only when the stated action occurred, the authorized owner accepted the result where required, and the client communication is complete. Link that proof.`,`Reopen when the source changes, acceptance fails, an approval expires, or the client corrects the record. Keep residual uncertainty visible.`]},
    ],
    banners:[{label:'Working record',title:'Keep the source close',body:'A reviewer should be able to reproduce the fact.',href:`/services/${service}`,link:'See related support'},{label:'Authority check',title:'Name the decision owner',body:'Preparation and approval are different jobs.',href:'/services/account-reporting',link:'See reporting support'},{label:'Next step',title:'Build a controlled routine',body:'Start with a small queue and visible review.',href:'/contact-us',link:'Contact Us'}],
    table:{caption:`${name} control fields`,headers:['Question','Record','Review'],rows:[['What happened?','Source, date, observed fact','Can another person find it?'],['Why now?','Client consequence and due date','Is the timing current?'],['Who decides?','Work owner and decision owner','Is authority explicit?'],['What closes it?','Proof and reopen rule','Was the result verified?']]},
    chart:[{label:'Source',value:100,color:'#e8c98e'},{label:'Decision',value:72,color:'#b9dfce'},{label:'Proof',value:46,color:'#ffd9ce'}],chartMeta:{title:`${name} review path`,desc:'A process aid connecting source, decision, and proof.',heading:'Source, decision, proof',method:'Illustrative workflow, not measured performance.'},quote:{text:'Accountability allows actions to be traced to an entity.',source:'NIST accountability glossary',url:'https://csrc.nist.gov/glossary/term/accountability'},
    script:[`We checked ${subject} against [source] on [date]. We can confirm [fact], while [owner] is reviewing [open point].`,'The next approved update is due [date]. We will close this record when [proof] is available.'],
    faqs:[{q:`What belongs in a ${subject}?`,a:`Record ${fields}, the client consequence, and the closure rule.`},{q:'Who decides sensitive issues?',a:'The named authorized owner handles commercial, legal, security, privacy, access, and scope decisions.'},{q:'When should the record reopen?',a:'Reopen when evidence changes, approval expires, acceptance fails, or the client corrects a fact.'}],sources};
}
export const september7BlogPosts=topics.map(t=>({slug:`philippines-account-management-${t[0]}`,title:`Philippines account management ${t[1].toLowerCase()}`,published:'2026-09-07' as const,excerpt:`A September 7, 2026 guide to ${t[3]}.`,minutes:11}));
export const september7RichArticles:Array<[string,RichArticle]>=topics.map(t=>[`philippines-account-management-${t[0]}`,makeSeptemberBlogArticle(t)]);
