import { makeSeptemberBlogArticle, type SeptemberBlogTopic } from './september7-blog-batch';
import type { RichArticle } from './rich-articles';

type Topic = { core: SeptemberBlogTopic; example: string; comparison: string; test: string };

const topics: Topic[] = [
  {core:['onboarding-discovery-completeness-gate','Onboarding discovery completeness gate','client-onboarding-coordination','decide whether a new account has enough confirmed context to enter routine support','account objective, stakeholders, approved channels, system access, open commitments, decision boundaries, missing-evidence owner, and next check','A kickoff can feel complete while the operating details needed for Monday are still missing.','2026-08-31-handoff-shadow-review.png'],example:'An agency moves four accounts to a support specialist. Two records lack renewal dates and an escalation owner. Hold those two in preparation while the complete records proceed; do not label the whole launch ready or blocked.',comparison:'Use three outcomes: ready, ready with a dated exception, and not ready. A dated exception names the missing item, temporary safe instruction, owner, and deadline.',test:'Ask the incoming specialist to prepare one real follow-up from the record. Every question about authority, source, or channel reveals a gap to capture before the account list grows.'},
  {core:['account-health-telemetry-ownership-map','Account health telemetry ownership map','account-health-monitoring','assign an owner and response rule to every signal used in an account health view','signal, source, refresh cadence, interpretation owner, response owner, threshold, blind spot, and retirement rule','A health dashboard creates confidence only when someone knows who checks each signal and what a change should trigger.','2026-08-31-portfolio-exception-budget.png'],example:'A portfolio view combines overdue tasks, response time, cases, and a relationship note. Operations can investigate response time, while the account owner must interpret the relationship note. One generic health owner cannot act on both.',comparison:'Separate maintenance from interpretation. A specialist may check whether data refreshed and route a threshold breach; the accountable owner decides whether combined signals change the risk view.',test:'Add a blind-spot field. If the ticket source is unavailable, show the gap. Missing telemetry is not a positive signal and must not silently become reassurance.'},
  {core:['renewal-notice-deadline-control','Renewal notice deadline control','renewal-administration','separate contractual notice dates from preparation dates and client conversation targets','agreement source, notice clause, timezone, calculated deadline, reviewer, preparation date, conversation owner, and exception route','A renewal plan can start early and still fail when the contractual notice deadline is buried in the calendar.','2026-08-31-renewal-evidence-freeze.png'],example:'An agreement renews December 1 and appears to require notice 60 days earlier. An October 10 conversation target is useful but is not the contractual deadline. The contract owner must verify the clause, calculation, and timezone.',comparison:'Maintain separate evidence, internal-decision, client-conversation, and formal-notice dates. The specialist maintains reminders; an authorized owner interprets ambiguous language.',test:'If an amendment conflicts with the base agreement, preserve both sources, suspend the automatic answer, and route the conflict with a dated internal update.'},
  {core:['qbr-audience-decision-map','QBR audience decision map','customer-qbr-preparation','match each QBR section to the people who can use or decide it','agenda section, audience, decision requested, evidence, presenter, sensitivity limit, and follow-up owner','A thorough QBR wastes time when the right evidence reaches the wrong room.','2026-08-31-qbr-question-backlog.png'],example:'An operations lead needs the exception log; an executive sponsor needs a priority decision. Sending the same twenty-slide narrative to both can bury the choice and expose detail without purpose.',comparison:'Label items inform, validate, decide, or assign. A decision item needs options, consequences, an authorized decision maker, and a recorded outcome.',test:'Compare attendance with the map after the meeting. Route an unmade decision to the absent owner instead of recording silence as approval.'},
  {core:['crm-relationship-role-change-audit','CRM relationship role change audit','crm-account-maintenance','update contact roles after a client responsibility change without erasing history','contact, former role, current role, effective date, confirmation source, affected permissions, relationship owner, and follow-up','A familiar CRM name can receive the wrong messages long after the client reorganizes.','2026-08-31-crm-correction-provenance-log.png'],example:'A client director moves into an advisory role while a new director takes daily ownership. Overwriting the old title erases history; leaving it unchanged misroutes work. End-date the old role and record the new state.',comparison:'Audit title, approval rights, lists, channels, open tasks, meetings, access, and renewal participation. Each change needs a source and effective date.',test:'Use an approved channel to confirm routing when permitted. Sensitive access or authority changes remain with the internal owner.'},
  {core:['client-request-dependency-acknowledgement','Client request dependency acknowledgement','client-request-routing','acknowledge a request that depends on another team without promising that team’s result','request wording, client consequence, dependency, dependency owner, evidence requested, acknowledgement, next update, and escalation trigger','The quickest reply to a dependent request is often the one most likely to create an accidental promise.','2026-08-31-client-silence-follow-up-rule.png'],example:'A client asks whether a reporting change can be live Friday, but engineering and security must respond. “On track” turns open dependencies into a promise. Confirm the request and commit only to the next update.',comparison:'Keep the dependency owner separate from the client-response owner. One supplies evidence; the other prevents silence.',test:'Distinguish answer delivered from work delivered. The decision request may close while an approved implementation remains open elsewhere.'},
  {core:['expansion-signal-consent-boundary','Expansion signal consent boundary','upsell-opportunity-tracking','distinguish evidence of client need from permission to begin a commercial conversation','observed need, source wording, current scope, account impact, relationship context, commercial owner, contact permission, and next step','A client describing a problem is not automatically inviting a sales pitch.','2026-08-31-client-metric-definition-card.png'],example:'A client says month-end reporting consumes too much team time. That is evidence of friction, not consent for a proposal. Preserve the wording and let the relationship owner decide whether to ask permission.',comparison:'Classify the next step as service recovery, routine improvement, discovery, or commercial discussion. A current-scope delivery gap should not be disguised as an upsell.',test:'Ask narrowly whether the client wants to explore options and who should join. Do not promise capacity, pricing, or a solution.'},
  {core:['account-report-exception-narrative','Account report exception narrative','account-reporting','explain an unusual result without turning an unverified theory into a client-facing cause','metric, expected range, observed exception, source window, confirmed facts, hypotheses, investigation owner, and approved note','A surprising number attracts an explanation before evidence can support one.','2026-08-31-crm-correction-provenance-log.png'],example:'Completed tasks fall sharply for one week. An outage, holiday, workflow change, or lower activity could all create the pattern. State the exception and source limits before any hypothesis.',comparison:'Write in layers: observed value, comparison period, confirmed facts, open questions, and next check. The client can use what is known without mistaking a story for a cause.',test:'When later evidence changes the explanation, preserve the correction and identify affected charts and updates.'},
  {core:['milestone-dependency-acceptance-check','Milestone dependency acceptance check','contract-milestone-tracking','confirm that a prerequisite was received, usable, and accepted before advancing a milestone','milestone, dependency, expected format, received time, validation test, acceptance owner, defect route, and schedule effect','A file arriving on time does not mean the milestone dependency is usable.','2026-08-31-client-commitment-sunset-review.png'],example:'A client uploads a file on time, but identifiers are absent and validation fails. Received is true; dependency complete is not. Record both states and the schedule effect.',comparison:'Define format, required fields, authorized source, access, and approval tests before the due date. A checklist invented after failure moves the goalposts.',test:'Acknowledge usable portions and request the smallest correction. Timing or scope changes belong to the authorized owner.'},
  {core:['feedback-anonymity-handling-record','Feedback anonymity handling record','customer-feedback-administration','preserve useful feedback while honoring the promised level of anonymity','feedback channel, anonymity promise, audience, redaction method, retained context, action owner, response route, and deletion rule','Anonymous feedback loses trust when a helpful summary reveals who must have said it.','2026-08-31-stakeholder-absence-plan.png'],example:'Three client participants submit anonymous feedback. Quoting a unique responsibility or meeting can identify a speaker even without a name. Record both direct identifiers and contextual clues.',comparison:'Anonymous, confidential, and unattributed are different. Use the promise made at collection, not the label that becomes convenient later.',test:'Retain enough context to route action without reconstructing identity for a broad audience. Escalate if safe action is impossible under the promise.'},
  {core:['handoff-stabilization-window','Handoff stabilization window','implementation-handoff-support','define the monitored period after ownership transfers but before the handoff is stable','accounts, window dates, checks, warning signals, outgoing owner availability, incoming owner, evidence, and exit test','A handoff is most fragile after the meeting, when the new owner handles real exceptions.','2026-08-31-handoff-shadow-review.png'],example:'The first weekly report after handoff succeeds, but the first exception exposes missing access. Sample routine work and an exception path before calling the transfer stable.',comparison:'Entry requires an accepted handoff and minimum access. Exit requires completed checks, reviewed communication, reconciled open loops, and decisions on material exceptions.',test:'The incoming owner holds the queue; the outgoing owner supplies history; the accountable owner resolves conflicts. Avoid two invisible owners.'},
  {core:['escalation-communication-audience-approval','Escalation communication audience approval','escalation-coordination','approve who receives each escalation update before sensitive facts travel too widely','incident state, audience, need-to-know purpose, approved facts, excluded details, channel, approver, and audience review','An urgent escalation can spread incomplete or sensitive information faster than the issue changes.','2026-08-31-escalation-audience-map.png'],example:'Operations, executives, the client, and a staffing partner need different incident facts. Copying one internal message to all groups can expose personal detail, speculation, or security information.',comparison:'Build packets from a verified core: effect, confirmed scope, mitigation, owner, and next update. Add only what each audience needs to decide.',test:'Reapprove the audience as scope changes. A list suitable for investigation may be too broad for later personnel or contractual discussion.'},
];

function build({core,example,comparison,test}: Topic): RichArticle {
  const base=makeSeptemberBlogArticle(core,'2026-09-23'); const subject=core[1].toLowerCase();
  return {...base,description:`A September 23, 2026 field guide to ${core[3]}, with a worked example, decision boundaries, and a verifiable close.`,readMinutes:14,
    intro:[...base.intro,example],takeaways:[...base.takeaways,`Test the ${subject} on a bounded account set before widening the queue.`],
    sections:base.sections.map((section,index)=>({...section,paragraphs:[...section.paragraphs,index%2?comparison:test,`For this ${subject}, record exceptions as carefully as the normal path. Name the blocker, client consequence, resolution owner, temporary safe instruction, and next review time. This turns waiting into a visible state rather than an unowned pause.`]}))};
}

export const september23BlogPosts=topics.map(({core})=>({slug:`philippines-account-management-${core[0]}`,title:`Philippines account management ${core[1].toLowerCase()}`,published:'2026-09-23' as const,excerpt:`A September 23, 2026 guide to ${core[3]}.`,minutes:14}));
export const september23RichArticles:Array<[string,RichArticle]>=topics.map((topic)=>[`philippines-account-management-${topic.core[0]}`,build(topic)]);
