import { makeSeptemberBlogArticle, type SeptemberBlogTopic } from './september7-blog-batch';
import type { RichArticle } from './rich-articles';

const topics: SeptemberBlogTopic[] = [
  ['client-decision-dependency-map','Client decision dependency map','client-request-routing','show which client decisions block dependent account work','decision, source request, dependent work, accountable approver, due date, interim response, and release proof','A single unanswered decision can quietly stall several promises unless the dependencies are visible.','2026-08-31-client-decision-expiry-register.png'],
  ['renewal-evidence-gap-triage','Renewal evidence gap triage','renewal-administration','rank missing renewal evidence by decision consequence','missing fact, expected source, commercial consequence, evidence owner, decision owner, due date, and fallback','A renewal file can look complete while its most consequential claim still lacks a reproducible source.','2026-08-31-renewal-evidence-freeze.png'],
  ['stakeholder-response-window-record','Stakeholder response window record','crm-account-maintenance','keep contact availability and promised response windows current','stakeholder, decision class, stated window, source, timezone, backup contact, and refresh trigger','A correct contact record is still operationally weak when nobody knows when or how that person can respond.','2026-08-31-stakeholder-absence-plan.png'],
  ['escalation-update-approval-clock','Escalation update approval clock','escalation-coordination','track time-sensitive approvals without overstating incident certainty','draft update, evidence cutoff, approver, requested time, expiry time, fallback wording, and send proof','Sensitive updates lose value when approval timing is invisible and facts change underneath the draft.','2026-08-31-escalation-audience-map.png'],
  ['client-request-acceptance-test','Client request acceptance test','client-request-routing','define observable proof that a client request is actually complete','requested outcome, acceptance condition, verifier, evidence source, exception, client response, and reopen trigger','Marking work done is not the same as showing that the requested outcome was accepted.','2026-08-21-client-request-consequence-grid.png'],
  ['portfolio-attention-rebalance-note','Portfolio attention rebalance note','account-health-monitoring','document why account-review capacity moves between clients','trigger signal, affected accounts, evidence age, client consequence, old cadence, new cadence, and review date','Changing portfolio attention without a written rationale can hide which client risks were deliberately deferred.','2026-08-31-portfolio-exception-budget.png'],
  ['qbr-metric-change-brief','QBR metric change brief','customer-qbr-preparation','explain a metric-definition change before it reaches a client review','metric, former definition, new definition, affected period, calculation impact, approver, and disclosure wording','A trend line can appear persuasive even when the metric definition changed between periods.','2026-08-31-client-metric-definition-card.png'],
  ['handoff-client-language-register','Handoff client language register','implementation-handoff-support','preserve approved client wording through an account ownership transition','message, audience, source facts, approval owner, send status, response, and correction history','A handoff can preserve tasks yet still lose the exact wording a client received or was promised.','2026-08-31-handoff-shadow-review.png'],
  ['scope-exception-expiry-check','Scope exception expiry check','contract-milestone-tracking','stop temporary service exceptions from becoming silent permanent scope','exception, approving owner, start date, expiry, client consequence, renewal decision, and closure proof','Temporary exceptions often outlive their approval when nobody records the condition that ends them.','2026-08-31-service-credit-preparation-boundary.png'],
  ['client-report-source-window-card','Client report source window card','account-reporting','make the evidence period behind every client report explicit','report claim, source system, start date, cutoff date, late data, reviewer, and limitation','A client report can be technically accurate yet misleading when its evidence window is unclear.','2026-08-21-client-update-source-trace.png'],
  ['account-coverage-exception-log','Account coverage exception log','account-health-monitoring','record work that temporary coverage could not safely complete','account, assigned coverage, blocked action, authority gap, client effect, escalation owner, and return plan','Coverage plans fail quietly when blocked work is left outside the returning owner’s record.','2026-08-21-account-coverage-window-board.png'],
  ['commitment-verification-sample','Commitment verification sample','contract-milestone-tracking','test a sample of claimed closures against their stated proof','sample rule, commitment, closure claim, required evidence, observed evidence, reviewer result, and correction','A closed queue can conceal weak evidence unless ordinary items are sampled as carefully as exceptions.','2026-08-31-client-commitment-sunset-review.png'],
];

export const september8BlogPosts=topics.map(t=>({slug:`philippines-account-management-${t[0]}`,title:`Philippines account management ${t[1].toLowerCase()}`,published:'2026-09-08' as const,excerpt:`A September 8, 2026 guide to ${t[3]}.`,minutes:11}));
export const september8RichArticles:Array<[string,RichArticle]>=topics.map(t=>[`philippines-account-management-${t[0]}`,makeSeptemberBlogArticle(t,'2026-09-08')]);
