import type { RichArticle } from './rich-articles';

type Topic = readonly [string, string, string, string, string, string];
const topics: Topic[] = [
  ['account-context-revalidation-check', 'Account context revalidation check', 'account-health-monitoring', 'confirm that the facts guiding today’s account work still match the client record', 'context source, last confirmation, changed assumption, affected action, and review owner', '2026-08-31-client-metric-definition-card.png'],
  ['client-reply-commitment-ledger', 'Client reply commitment ledger', 'client-request-routing', 'keep promised responses visible until the approved answer is actually sent', 'client question, promised reply date, evidence owner, decision dependency, and send proof', '2026-08-31-client-silence-follow-up-rule.png'],
  ['renewal-assumption-challenge-log', 'Renewal assumption challenge log', 'renewal-administration', 'surface unsupported renewal beliefs before they enter a commercial review', 'assumption, supporting source, contradictory evidence, decision consequence, and commercial owner', '2026-08-31-renewal-evidence-freeze.png'],
  ['qbr-action-evidence-reconciliation', 'QBR action evidence reconciliation', 'customer-qbr-preparation', 'reconcile review actions with their owners, due dates, and completion evidence', 'meeting decision, action owner, due date, current proof, discrepancy, and next check', '2026-08-31-qbr-question-backlog.png'],
  ['crm-source-conflict-workbench', 'CRM source conflict workbench', 'crm-account-maintenance', 'resolve conflicting account facts without silently choosing a convenient value', 'field, competing sources, timestamps, authority ranking, reviewer, and correction trail', '2026-08-31-crm-correction-provenance-log.png'],
  ['account-coverage-interruption-plan', 'Account coverage interruption plan', 'account-health-monitoring', 'protect scheduled client work when urgent exceptions consume the team’s attention', 'interruption, affected accounts, deferred review, interim owner, client consequence, and recovery date', '2026-08-31-portfolio-exception-budget.png'],
  ['escalation-fact-readiness-check', 'Escalation fact readiness check', 'escalation-coordination', 'prepare a consequential escalation without mixing verified facts and interpretation', 'observed event, source, impact boundary, unknowns, decision owner, and approved audience', '2026-08-31-escalation-audience-map.png'],
  ['client-update-approval-timestamp', 'Client update approval timestamp', 'account-reporting', 'show which version of a client update was approved and when that approval expires', 'draft version, evidence cutoff, approver, approval time, expiry condition, and sent version', '2026-08-31-client-decision-expiry-register.png'],
  ['implementation-dependency-receipt', 'Implementation dependency receipt', 'implementation-handoff-support', 'record whether every incoming implementation dependency was received and accepted', 'dependency, provider, expected date, receipt evidence, acceptance result, and blocker owner', '2026-08-31-handoff-shadow-review.png'],
  ['account-commitment-change-notice', 'Account commitment change notice', 'contract-milestone-tracking', 'make a changed client commitment reviewable before teams act on it', 'original commitment, proposed change, reason, affected milestone, approver, and communication proof', '2026-08-31-client-commitment-sunset-review.png'],
  ['service-recovery-next-check-card', 'Service recovery next-check card', 'escalation-coordination', 'keep recovery verification separate from the first client response', 'incident fact, approved action, client update, verification method, next check, and closure owner', '2026-08-31-service-credit-preparation-boundary.png'],
  ['stakeholder-decision-continuity-note', 'Stakeholder decision continuity note', 'client-onboarding-coordination', 'preserve decision limits when a client or internal stakeholder becomes unavailable', 'absence window, authorized delegate, decision limit, open questions, prohibited actions, and return review', '2026-08-31-stakeholder-absence-plan.png'],
];

const sources = [
  { name: 'NIST Cybersecurity Framework 2.0', date: 'February 26, 2024', url: 'https://www.nist.gov/publications/cybersecurity-framework-csf-20', note: 'Governance vocabulary; it does not establish account-management performance.' },
  { name: 'NIST accountability glossary', date: 'accessed September 1, 2026', url: 'https://csrc.nist.gov/glossary/term/accountability', note: 'Supports traceable ownership and action records.' },
  { name: 'ISO quality management principles', date: 'accessed September 1, 2026', url: 'https://www.iso.org/quality-management/principles', note: 'Supports evidence-based review and improvement.' },
];

function make([short, name, service, purpose, fields, image]: Topic): RichArticle {
  const subject = name.toLowerCase();
  return {
    title: `Philippines account management ${subject}`,
    description: `Published September 1, 2026: an operating guide to ${purpose}.`, published: '2026-09-01', updated: '2026-09-01', readMinutes: 13,
    heroImage: `/blog-heroes/${image}`,
    intro: [`Published September 1, 2026. A ${subject} helps an outsourced account team ${purpose}.`, `Build the record around ${fields}. Each entry must point to dated evidence, an authorized decision, or an explicit unknown.`],
    takeaways: [`Capture ${fields}.`, 'Separate observed facts, interpretation, preparation, approval, communication, and closure.', 'Keep commercial, legal, security, access, and scope decisions with authorized owners.', 'Give every uncertainty a source request, owner, and next-check date.'],
    sections: [
      { heading: `Set the boundary for the ${subject}`, paragraphs: [`Name the account, operating window, client consequence, and exact decision this record supports. The purpose is to ${purpose}; it is not to create a general diary of account activity. A bounded unit prevents unrelated work from sharing one ambiguous status.`, `Record ${fields}. If evidence is unavailable, write unknown and identify the smallest authorized source check that could resolve it. Do not convert a remembered conversation or likely outcome into a confirmed fact.`] },
      { heading: 'Preserve the controlling source', paragraphs: [`Link the approved CRM entry, agreement, client message, meeting record, or delivery proof behind each material statement. Keep source wording separate from the team’s interpretation so a later reviewer can see whether a condition, date, or limitation was lost.`, `When two sources disagree, retain both with their timestamps and purpose. Rank authority for this decision, name the reconciliation owner, and pause only the affected action. Newer does not automatically mean controlling, and convenient does not mean correct.`] },
      { heading: 'Use states that another person can verify', paragraphs: [`Use observable states such as captured, checking source, ready for owner, approved to communicate, waiting for client, verifying action, and closed. Each state needs entry evidence, an allowed editor, and a specific exit condition.`, `A sent message proves communication, not resolution. A completed administrative task proves an action occurred, not that a client accepted it or that an accountable owner approved its consequence.`] },
      { heading: 'Keep preparation separate from authority', paragraphs: [`A Philippines-based account specialist can gather approved facts, maintain the assigned record, prepare neutral wording, and route an exception. Those activities do not grant authority to alter terms, promise service, approve money, disclose sensitive material, or decide legal and security questions.`, `Name the work owner and decision owner separately. Delegated authority should identify its scope and expiry. System access, meeting attendance, or job seniority is not evidence that a person may make the decision.`] },
      { heading: 'Prepare the client-facing update', paragraphs: [`If an answer is not ready, state what was received, what is confirmed, what remains under review, who owns that review, and when the next update will arrive. Specific uncertainty is more useful than unsupported reassurance.`, `Compare the approved draft with the ${subject} immediately before sending. Preserve the version sent and any client correction so the operating record continues to match the conversation.`] },
      { heading: 'Protect access and revision history', paragraphs: [`Use named accounts and task-matched permissions. Link controlled evidence instead of copying private client information into broad coordination notes. Credentials, identity documents, financial data, and sensitive personnel information do not belong in this record.`, `Append material corrections with a date, source, editor, reviewer, and affected downstream items. Silent rewriting removes the history needed to explain earlier decisions and communications.`] },
      { heading: 'Test the handoff and review cadence', paragraphs: [`At the daily scan, inspect new records, triggered exceptions, and missed next-check dates. In the weekly review, sample consequential open and closed items for source quality, ownership, communication accuracy, and closure proof.`, `Ask a receiving teammate to locate the evidence, explain the current state, identify the decision owner, and state the closure rule without coaching. Treat misunderstandings as a signal to improve the field or instruction.`] },
      { heading: 'Close with proof', paragraphs: [`Close only when the stated action occurred, the correct owner accepted the result, evidence is linked, and approved client communication was sent where required. Carry residual work forward as a separately owned item.`, `Add a reopening trigger such as a client correction, changed scope, expired approval, contradictory source, or failed verification. A durable ${subject} makes both closure and the reason to revisit it visible.`] },
    ],
    banners: [{ label: 'Source', title: 'Use dated evidence', body: 'Keep the fact and interpretation separate.', href: `/services/${service}`, link: 'See related support' }, { label: 'Owner', title: 'Name decision authority', body: 'Preparation does not confer approval.', href: '/services/account-reporting', link: 'See reporting support' }, { label: 'Proof', title: 'Verify the outcome', body: 'Communication alone is not closure.', href: '/contact-us', link: 'Contact Us' }],
    table: { caption: `${name} control fields`, headers: ['Layer', 'Minimum record', 'Review question'], rows: [['Purpose', 'Account, period, consequence', 'Which decision will this support?'], ['Evidence', 'Source, date, fact, limitation', 'Can another reviewer reproduce it?'], ['Authority', 'Work owner, decision owner, state', 'Is the action within scope?'], ['Closure', 'Rule, proof, reopen trigger', 'What confirms the outcome?']] },
    chart: [{ label: 'Source', value: 100, color: '#e8c98e' }, { label: 'Owner', value: 75, color: '#b9dfce' }, { label: 'Proof', value: 50, color: '#ffd9ce' }],
    chartMeta: { title: name, desc: 'Source, owner, and proof form a reviewable control path.', heading: 'A reviewable control path', method: 'Process illustration, not measured performance.' },
    quote: { text: 'Accountability allows actions to be traced to an entity.', source: 'NIST accountability glossary', url: 'https://csrc.nist.gov/glossary/term/accountability' },
    script: [`We checked ${purpose} against [source] on [date]. The confirmed fact is [fact], and [owner] is reviewing [open decision].`, 'The next approved update is due [date]. Closure requires [proof], and any remaining exception will stay visible.'],
    faqs: [{ q: `What belongs in a ${subject}?`, a: `At minimum: ${fields}, plus the client consequence and closure rule.` }, { q: 'Which decisions remain with the owner?', a: 'Commercial, legal, security, access, privacy, and scope decisions remain with their authorized owners.' }, { q: 'When is the record complete?', a: 'When the source, authority, communication, outcome evidence, and reopening rule agree.' }], sources,
  };
}

export const september1BlogPosts = topics.map(t => ({ slug: `philippines-account-management-${t[0]}`, title: `Philippines account management ${t[1].toLowerCase()}`, published: '2026-09-01' as const, excerpt: `A practical guide to ${t[3]}.`, minutes: 13 }));
export const september1RichArticles: Array<[string, RichArticle]> = topics.map(t => [`philippines-account-management-${t[0]}`, make(t)]);
