import { makeSeptemberBlogArticle, type SeptemberBlogTopic } from './september7-blog-batch';
import type { RichArticle } from './rich-articles';
const topics: SeptemberBlogTopic[] = [
 ['account-decision-evidence-envelope','Account decision evidence envelope','client-request-routing','package the facts an account owner needs before making a consequential decision','decision question, source facts, evidence cutoff, missing facts, client consequence, decision owner, and response deadline','A decision request is easier to answer when evidence and uncertainty arrive in one bounded packet.','2026-08-31-client-decision-expiry-register.png'],
 ['renewal-obligation-source-ledger','Renewal obligation source ledger','renewal-administration','trace each renewal obligation to its controlling record','obligation, contract source, effective date, current evidence, work owner, commercial owner, and verification status','Renewal preparation becomes risky when an inherited obligation has no visible source.','2026-08-31-renewal-evidence-freeze.png'],
 ['stakeholder-decision-substitute-plan','Stakeholder decision substitute plan','crm-account-maintenance','route decisions safely when the usual client contact is unavailable','decision class, primary contact, approved substitute, authority source, availability window, limit, and reconfirmation date','An out-of-office notice should not force an account team to guess who can decide.','2026-08-31-stakeholder-absence-plan.png'],
 ['escalation-fact-change-watch','Escalation fact change watch','escalation-coordination','keep a pending escalation draft aligned with changing evidence','claim, source, last check, change trigger, draft owner, approver, and next verification','A careful escalation draft can still become stale while it waits for approval.','2026-08-31-escalation-audience-map.png'],
 ['client-request-scope-split','Client request scope split','client-request-routing','separate one client message into authorized work and owner decisions','original request, in-scope action, decision item, evidence needed, work owner, decision owner, and reply plan','One client message can contain routine work, a scope question, and a commercial decision.','2026-08-21-client-request-consequence-grid.png'],
 ['account-health-signal-expiry','Account health signal expiry','account-health-monitoring','retire or recheck account signals before they mislead a portfolio review','signal, source date, interpretation, expiry rule, corroboration, review owner, and disposition','An old account signal can keep influencing attention long after its context has changed.','2026-08-31-portfolio-exception-budget.png'],
 ['qbr-comparison-basis-note','QBR comparison basis note','customer-qbr-preparation','show whether two reporting periods use genuinely comparable definitions','metric, period, population, exclusions, calculation, source changes, and approved interpretation','Two polished QBR columns are not comparable merely because they share a label.','2026-08-31-client-metric-definition-card.png'],
 ['handoff-decision-rationale-capsule','Handoff decision rationale capsule','implementation-handoff-support','preserve why an open account decision reached its current state','decision, options considered, source evidence, constraint, authorized owner, date, and revisit trigger','A handoff that carries the answer but loses the rationale invites the next owner to reopen settled work.','2026-08-31-handoff-shadow-review.png'],
 ['service-boundary-client-reply','Service boundary client reply','contract-milestone-tracking','prepare a useful response while an out-of-scope request awaits review','client request, confirmed scope, unresolved boundary, interim action, decision owner, next update, and approval','A fast helpful reply can accidentally sound like acceptance of work nobody approved.','2026-08-31-service-credit-preparation-boundary.png'],
 ['client-report-late-evidence-addendum','Client report late-evidence addendum','account-reporting','add material evidence received after a report cutoff without rewriting history','original cutoff, late source, affected claim, materiality review, approver, correction language, and distribution','Late evidence should change the record visibly instead of silently altering the published story.','2026-08-31-crm-correction-provenance-log.png'],
 ['portfolio-review-omission-check','Portfolio review omission check','account-health-monitoring','find accounts excluded by filters, ownership gaps, or missing records','review population, exclusion rule, omitted account, omission reason, consequence, owner, and correction','The accounts absent from a review can matter more than the clean records inside it.','2026-08-31-portfolio-exception-budget.png'],
 ['commitment-acceptance-evidence-chain','Commitment acceptance evidence chain','contract-milestone-tracking','connect a completed action to the acceptance condition the client actually agreed','commitment, completion evidence, acceptance rule, verifier, response, exception, and reopen condition','Completion evidence answers what happened; acceptance evidence answers whether it met the agreed condition.','2026-08-31-client-commitment-sunset-review.png'],
];
export const september9BlogPosts=topics.map(t=>({slug:`philippines-account-management-${t[0]}`,title:`Philippines account management ${t[1].toLowerCase()}`,published:'2026-09-09' as const,excerpt:`A September 9, 2026 guide to ${t[3]}.`,minutes:11}));
export const september9RichArticles:Array<[string,RichArticle]>=topics.map(t=>[`philippines-account-management-${t[0]}`,makeSeptemberBlogArticle(t,'2026-09-09')]);
