import { makeSeptemberBlogArticle, type SeptemberBlogTopic } from './september7-blog-batch';
import type { RichArticle } from './rich-articles';

type Topic = { core: readonly [string,string,string,string,string,string,string,string,string] };

const topics: Topic[] = [
  {core:['onboarding-communication-channel-validation','Onboarding communication channel validation','client-onboarding-coordination','confirm which channels may be used for each client message before routine support begins','message type, approved channel, recipient role, sensitivity, sender authority, fallback route, evidence source, and review date','A kickoff note lists email, chat, and a ticket portal, but it does not say where an urgent service question belongs. The specialist tests the routing with the owner before sending live work.','Separate convenience from authorization. A client may prefer chat for scheduling while requiring the portal for service requests and email for formal approvals.','Close the check only when a named owner confirms the route, a sample message reaches the right queue, and the record shows what to do when that route is unavailable.','2026-08-31-stakeholder-absence-plan.png']},
  {core:['account-health-signal-suppression-log','Account health signal suppression log','account-health-monitoring','record why a noisy or invalid health signal is temporarily excluded without hiding risk','signal, source, suppression reason, evidence, approver, start time, expiry, replacement check, and reinstatement test','A delayed integration repeats the same overdue-task signal every hour. Removing it silently makes the dashboard calmer but destroys the audit trail.','Keep the raw observation visible, label its reliability, and add a temporary alternative check. Suppression changes presentation; it does not prove the account is healthy.','At expiry, reinstate the signal, extend the suppression with new evidence, or retire it through the metric-governance owner.','2026-08-31-portfolio-exception-budget.png']},
  {core:['renewal-stakeholder-availability-plan','Renewal stakeholder availability plan','renewal-administration','prepare for decision-maker absences before a renewal deadline becomes urgent','stakeholder, decision role, availability window, delegate, evidence needed, meeting target, notice deadline, and escalation owner','The commercial owner will be away during the week a client expects an answer. The account specialist can assemble the evidence and calendar options but cannot treat an informal delegate as authorized.','Plan separately for evidence review, internal commercial approval, client conversation, and formal notice. Each may require a different person and date.','Close the plan when authority is confirmed, required meetings are booked, and the contractual notice control remains visible beside the conversation schedule.','2026-08-31-renewal-evidence-freeze.png']},
  {core:['qbr-follow-up-dependency-sequence','QBR follow-up dependency sequence','customer-qbr-preparation','order QBR actions whose completion depends on earlier decisions or evidence','action, prerequisite, decision owner, work owner, earliest start, due date, client effect, and completion proof','A QBR produces six actions, but two require budget approval and one requires corrected source data. Assigning the same due date to all six hides the actual sequence.','Show a dependency path rather than a flat list. A preparatory action may finish while the dependent client commitment remains unapproved.','Close each node with its own evidence, then confirm that downstream dates and client updates were revised when an upstream decision changed.','2026-08-31-qbr-question-backlog.png']},
  {core:['crm-duplicate-contact-merge-decision','CRM duplicate contact merge decision','crm-account-maintenance','prepare evidence for merging duplicate contact records without losing history or permissions','candidate records, matching evidence, conflicting fields, activity history, consent state, access effect, decision owner, and rollback note','Two contacts share a name and company but use different email domains and hold different consent records. Similarity is a review trigger, not proof that they are one person.','The specialist may compare approved fields and prepare the conflict list. The CRM owner decides the merge and the privacy or security owner reviews material permission effects.','After approval, preserve provenance, test linked activity and routing, and retain a recovery reference rather than deleting the losing record without trace.','2026-08-31-crm-correction-provenance-log.png']},
  {core:['client-request-withdrawal-confirmation','Client request withdrawal confirmation','client-request-routing','confirm that a withdrawn client request stops the right work without closing related obligations','original request, withdrawal source, affected tasks, irreversible work, dependencies, owner approval, client confirmation, and closure proof','A client withdraws a reporting change after preparation has started. Stopping the draft may be safe, but an access change and supplier task already in motion need separate owners.','Treat withdrawal as a change event. Identify what can stop, what already happened, what requires reversal, and what still needs a client-facing update.','Close only when affected owners acknowledge the stop, residual effects are recorded, and the client receives an approved confirmation of what was and was not cancelled.','2026-08-31-client-silence-follow-up-rule.png']},
  {core:['expansion-discovery-question-boundary','Expansion discovery question boundary','upsell-opportunity-tracking','prepare useful discovery questions without turning operational support into an unapproved sales conversation','observed need, source language, current scope, question purpose, permitted audience, commercial owner, consent, and next step','A client mentions a recurring backlog during a service review. The support specialist records the problem but does not jump to pricing, capacity, or a proposed package.','Use questions that clarify impact, timing, and desired outcome. Commercial qualification, solution promises, and price discussion stay with the authorized relationship owner.','Close the record when the client either consents to a separate discovery step or the owner decides to handle the need inside current service or recovery work.','2026-08-31-client-metric-definition-card.png']},
  {core:['portfolio-review-sample-selection-rule','Portfolio review sample selection rule','account-reporting','choose a review sample that includes ordinary work and meaningful exceptions instead of only easy accounts','portfolio, population, period, sampling rule, risk strata, exclusions, reviewer, findings, and follow-up','A weekly review of five convenient accounts finds no errors, while high-risk accounts with missing notes never enter the sample. Convenience creates reassurance, not coverage.','Combine a small random sample with required exception categories such as new handoffs, overdue commitments, recent escalations, and material data corrections.','Record the population and exclusions before selection. Close the review when findings have owners and the next sample responds to repeated patterns without abandoning ordinary work.','2026-08-31-portfolio-exception-budget.png']},
  {core:['milestone-evidence-retention-index','Milestone evidence retention index','contract-milestone-tracking','keep accepted milestone proof findable for the required period without copying sensitive material broadly','milestone, acceptance source, evidence location, owner, access class, retention rule, review date, deletion authority, and retrieval test','A milestone is marked accepted, but its approval lives in one person’s mailbox. Copying the attachment into every tracker improves visibility while weakening control.','Index controlled evidence instead of duplicating it. Retention and deletion rules come from the authorized contract, legal, privacy, or records owner.','Test that an authorized reviewer can retrieve the proof, understand the acceptance state, and see the retention decision without exposing the underlying file to the whole account team.','2026-08-31-client-commitment-sunset-review.png']},
  {core:['feedback-response-expectation-clock','Feedback response expectation clock','customer-feedback-administration','set an honest next-update time for feedback that requires investigation or owner review','feedback source, acknowledgement time, client consequence, investigation owner, decision owner, next update, channel, and closure condition','A client raises a complex concern Friday afternoon. Promising a resolution Monday confuses responsiveness with the time needed for evidence and authority.','Commit first to acknowledgement and the next evidence-based update. Set a resolution target only when the responsible owner can support it.','If the review takes longer, update before the clock expires, explain the confirmed state, and preserve the original concern until the approved response and follow-up are complete.','2026-08-31-client-silence-follow-up-rule.png']},
  {core:['handoff-backout-criteria','Handoff backout criteria','implementation-handoff-support','define when an account transfer should pause or return to the prior owner during stabilization','account scope, trigger, evidence threshold, temporary owner, client message, recovery action, review time, and restart test','A new owner discovers missing billing context during the first live exception. Continuing may compound the gap, but silently returning every task creates two invisible owners.','Use narrow triggers such as unavailable required access, unresolved authority, corrupted source data, or a client-safety risk. Ordinary questions stay in the stabilization queue.','A backout names one temporary owner, protects open commitments, sends an approved update when needed, and ends with a documented restart or redesign decision.','2026-08-31-handoff-shadow-review.png']},
  {core:['escalation-de-escalation-evidence-check','Escalation de-escalation evidence check','escalation-coordination','confirm that an escalation can leave urgent handling without hiding unresolved client impact','trigger, current effect, mitigation evidence, unresolved risks, client commitment, approver, monitoring window, and re-escalation rule','Service is restored after an incident, but the client still lacks a corrected report and root-cause update. Technical recovery alone does not close the account escalation.','Separate severity reduction from closure. The specialist assembles evidence and open commitments; the accountable owner approves the new handling level and message.','Close urgent handling only with verified mitigation, owned residual work, a dated client update, and a clear threshold for returning the issue to escalation.','2026-08-31-escalation-audience-map.png']},
];

function build({core}: Topic): RichArticle {
  const [slug,title,service,purpose,fields,scenario,control,close,image]=core;
  const normalized=[slug,title,service,purpose,fields,scenario,image] as SeptemberBlogTopic;
  const base=makeSeptemberBlogArticle(normalized,'2026-09-24'); const subject=title.toLowerCase();
  return {...base,description:`A September 24, 2026 field guide to ${core[3]}, with a worked scenario, authority boundaries, and closure evidence.`,readMinutes:14,
    intro:[...base.intro,scenario],takeaways:[...base.takeaways,`Pilot the ${subject} on a small account set and review exceptions before expanding it.`],
    sections:base.sections.map((section,index)=>({...section,paragraphs:[...section.paragraphs,index%2?control:close,`For this ${subject}, preserve the source wording and time of each material change. Record the work owner separately from the person authorized to decide, then give the client a truthful next update rather than an unsupported promise.`]}))};
}

export const september24BlogPosts=topics.map(({core})=>({slug:`philippines-account-management-${core[0]}`,title:`Philippines account management ${core[1].toLowerCase()}`,published:'2026-09-24' as const,excerpt:`A September 24, 2026 guide to ${core[3]}.`,minutes:14}));
export const september24RichArticles:Array<[string,RichArticle]>=topics.map((topic)=>[`philippines-account-management-${topic.core[0]}`,build(topic)]);
