import { makeSeptemberBlogArticle, type SeptemberBlogTopic } from './september7-blog-batch';
import type { RichArticle } from './rich-articles';

type Topic = { core: readonly [string,string,string,string,string,string,string,string,string] };

const topics: Topic[] = [
  {core:['onboarding-source-system-readiness-check','Onboarding source system readiness check','client-onboarding-coordination','confirm that each approved source system is usable before recurring client support starts','system, permitted purpose, record owner, access state, test record, failure route, and review date','A login succeeds, but the specialist cannot see the account queue needed for the first client update. Access existence is not workflow readiness.','Separate convenience from authorization. A client may prefer chat for scheduling while requiring the portal for service requests and email for formal approvals.','Close the check only when a named owner confirms the route, a sample message reaches the right queue, and the record shows what to do when that route is unavailable.','2026-08-31-stakeholder-absence-plan.png']},
  {core:['account-health-evidence-age-review','Account health evidence age review','account-health-monitoring','review whether the evidence behind an account status is still current enough for the decision','signal, source date, freshness rule, present status, client consequence, owner, next observation, and review proof','A delayed integration repeats the same overdue-task signal every hour. Removing it silently makes the dashboard calmer but destroys the audit trail.','Keep the raw observation visible, label its reliability, and add a temporary alternative check. Suppression changes presentation; it does not prove the account is healthy.','At expiry, reinstate the signal, extend the suppression with new evidence, or retire it through the metric-governance owner.','2026-08-31-portfolio-exception-budget.png']},
  {core:['renewal-notice-evidence-reconciliation','Renewal notice evidence reconciliation','renewal-administration','reconcile contract notice terms with operational renewal dates before outreach begins','agreement version, notice clause, effective date, calendar entry, conflict, legal owner, commercial owner, and review proof','The commercial owner will be away during the week a client expects an answer. The account specialist can assemble the evidence and calendar options but cannot treat an informal delegate as authorized.','Plan separately for evidence review, internal commercial approval, client conversation, and formal notice. Each may require a different person and date.','Close the plan when authority is confirmed, required meetings are booked, and the contractual notice control remains visible beside the conversation schedule.','2026-08-31-renewal-evidence-freeze.png']},
  {core:['qbr-audience-decision-map','QBR audience decision map','customer-qbr-preparation','match each QBR section to the people who can use or decide it','agenda item, audience role, decision requested, evidence, sensitivity, presenter, follow-up owner, and completion proof','A QBR produces six actions, but two require budget approval and one requires corrected source data. Assigning the same due date to all six hides the actual sequence.','Show a dependency path rather than a flat list. A preparatory action may finish while the dependent client commitment remains unapproved.','Close each node with its own evidence, then confirm that downstream dates and client updates were revised when an upstream decision changed.','2026-08-31-qbr-question-backlog.png']},
  {core:['crm-relationship-role-change-audit','CRM relationship role change audit','crm-account-maintenance','update stakeholder roles without losing the history that explains prior approvals and messages','contact, former role, new role, effective date, source, access effect, open work, decision owner, and rollback note','Two contacts share a name and company but use different email domains and hold different consent records. Similarity is a review trigger, not proof that they are one person.','The specialist may compare approved fields and prepare the conflict list. The CRM owner decides the merge and the privacy or security owner reviews material permission effects.','After approval, preserve provenance, test linked activity and routing, and retain a recovery reference rather than deleting the losing record without trace.','2026-08-31-crm-correction-provenance-log.png']},
  {core:['client-request-clarification-window','Client request clarification window','client-request-routing','obtain missing facts before an ambiguous request becomes an unsupported commitment','request wording, ambiguity, client impact, clarification question, interim owner, response target, escalation trigger, and closure proof','A client withdraws a reporting change after preparation has started. Stopping the draft may be safe, but an access change and supplier task already in motion need separate owners.','Treat withdrawal as a change event. Identify what can stop, what already happened, what requires reversal, and what still needs a client-facing update.','Close only when affected owners acknowledge the stop, residual effects are recorded, and the client receives an approved confirmation of what was and was not cancelled.','2026-08-31-client-silence-follow-up-rule.png']},
  {core:['expansion-signal-evidence-threshold','Expansion signal evidence threshold','upsell-opportunity-tracking','decide when an observed service need is ready for owner review without turning every comment into a sales lead','observation, source wording, recurrence, operational impact, current scope, client consent, commercial owner, and next step','A client mentions a recurring backlog during a service review. The support specialist records the problem but does not jump to pricing, capacity, or a proposed package.','Use questions that clarify impact, timing, and desired outcome. Commercial qualification, solution promises, and price discussion stay with the authorized relationship owner.','Close the record when the client either consents to a separate discovery step or the owner decides to handle the need inside current service or recovery work.','2026-08-31-client-metric-definition-card.png']},
  {core:['portfolio-review-coverage-gap-log','Portfolio review coverage gap log','account-reporting','show which accounts or evidence could not be reviewed and what risk remains','review population, missing account, missing source, reason, consequence, owner, recovery date, findings, and follow-up','A weekly review of five convenient accounts finds no errors, while high-risk accounts with missing notes never enter the sample. Convenience creates reassurance, not coverage.','Combine a small random sample with required exception categories such as new handoffs, overdue commitments, recent escalations, and material data corrections.','Record the population and exclusions before selection. Close the review when findings have owners and the next sample responds to repeated patterns without abandoning ordinary work.','2026-08-31-portfolio-exception-budget.png']},
  {core:['milestone-acceptance-authority-check','Milestone acceptance authority check','contract-milestone-tracking','verify that milestone acceptance came from a person and channel authorized for that decision','milestone, acceptance wording, sender, authority source, channel, conditions, delivery evidence, owner, and review date','A milestone is marked accepted, but its approval lives in one person’s mailbox. Copying the attachment into every tracker improves visibility while weakening control.','Index controlled evidence instead of duplicating it. Retention and deletion rules come from the authorized contract, legal, privacy, or records owner.','Test that an authorized reviewer can retrieve the proof, understand the acceptance state, and see the retention decision without exposing the underlying file to the whole account team.','2026-08-31-client-commitment-sunset-review.png']},
  {core:['feedback-follow-up-audience-check','Feedback follow-up audience check','customer-feedback-administration','send a feedback response to the right recipients without exposing internal or sensitive context','feedback source, affected audience, response purpose, sensitivity, approver, channel, recipient check, next update, and closure condition','A client raises a complex concern Friday afternoon. Promising a resolution Monday confuses responsiveness with the time needed for evidence and authority.','Commit first to acknowledgement and the next evidence-based update. Set a resolution target only when the responsible owner can support it.','If the review takes longer, update before the clock expires, explain the confirmed state, and preserve the original concern until the approved response and follow-up are complete.','2026-08-31-client-silence-follow-up-rule.png']},
  {core:['handoff-first-week-exception-review','Handoff first week exception review','implementation-handoff-support','review early exceptions after an account handoff before they become the new normal','account, exception, source, client effect, temporary action, prior owner input, decision owner, review time, and restart test','A new owner discovers missing billing context during the first live exception. Continuing may compound the gap, but silently returning every task creates two invisible owners.','Use narrow triggers such as unavailable required access, unresolved authority, corrupted source data, or a client-safety risk. Ordinary questions stay in the stabilization queue.','A backout names one temporary owner, protects open commitments, sends an approved update when needed, and ends with a documented restart or redesign decision.','2026-08-31-handoff-shadow-review.png']},
  {core:['escalation-client-update-consistency-check','Escalation client update consistency check','escalation-coordination','ensure concurrent escalation updates use the same verified facts and ownership','update versions, evidence cutoff, recipients, confirmed state, open question, approver, next update, and re-escalation rule','Service is restored after an incident, but the client still lacks a corrected report and root-cause update. Technical recovery alone does not close the account escalation.','Separate severity reduction from closure. The specialist assembles evidence and open commitments; the accountable owner approves the new handling level and message.','Close urgent handling only with verified mitigation, owned residual work, a dated client update, and a clear threshold for returning the issue to escalation.','2026-08-31-escalation-audience-map.png']},
];

function build({core}: Topic): RichArticle {
  const [slug,title,service,purpose,fields,scenario,control,close,image]=core;
  const normalized=[slug,title,service,purpose,fields,scenario,image] as SeptemberBlogTopic;
  const base=makeSeptemberBlogArticle(normalized,'2026-09-26'); const subject=title.toLowerCase();
  return {...base,description:`A September 26, 2026 field guide to ${core[3]}, with a worked scenario, authority boundaries, and closure evidence.`,readMinutes:14,
    intro:[...base.intro,scenario],takeaways:[...base.takeaways,`Pilot the ${subject} on a small account set and review exceptions before expanding it.`],
    sections:base.sections.map((section,index)=>({...section,paragraphs:[...section.paragraphs,index%2?control:close,`For this ${subject}, preserve the source wording and time of each material change. Record the work owner separately from the person authorized to decide, then give the client a truthful next update rather than an unsupported promise.`]}))};
}

export const september26BlogPosts=topics.map(({core})=>({slug:`philippines-account-management-${core[0]}`,title:`Philippines account management ${core[1].toLowerCase()}`,published:'2026-09-26' as const,excerpt:`A September 26, 2026 guide to ${core[3]}.`,minutes:14}));
export const september26RichArticles:Array<[string,RichArticle]>=topics.map((topic)=>[`philippines-account-management-${topic.core[0]}`,build(topic)]);
