import type { RichArticle } from './rich-articles';

type Topic = readonly [string, string, string, string, string, string];
const topics: Topic[] = [
  ['account-timezone-coverage-boundary', 'Account timezone coverage boundary', 'client-onboarding-coordination', 'define what a distributed account team may handle during each coverage window without implying continuous decision authority', 'client timezone, coverage window, queue owner, permitted actions, unavailable approver, next handoff, and urgent exception route', '2026-08-31-stakeholder-absence-plan.png'],
  ['client-decision-latency-register', 'Client decision latency register', 'client-request-routing', 'separate time spent waiting for a client decision from internal delay while keeping the next useful action visible', 'decision request, sent date, client consequence, evidence supplied, response owner, follow-up rule, and alternate path', '2026-08-31-client-decision-expiry-register.png'],
  ['account-context-decay-check', 'Account context decay check', 'account-health-monitoring', 'identify account facts that have aged past their useful review window before they shape a new recommendation', 'account fact, source date, freshness rule, dependent decision, verification owner, temporary caution, and replacement evidence', '2026-08-31-client-metric-definition-card.png'],
  ['meeting-action-evidence-chain', 'Meeting action evidence chain', 'account-reporting', 'carry a meeting action from spoken agreement through assignment, execution, verification, and client acknowledgement', 'meeting reference, exact action, acceptance language, work owner, due date, completion artifact, and acknowledgement state', '2026-08-31-qbr-question-backlog.png'],
  ['stakeholder-role-change-scan', 'Stakeholder role change scan', 'crm-account-maintenance', 'recheck routing, approvals, access, and communication when a client stakeholder changes responsibilities', 'former role, effective date, replacement contact, affected approvals, access review, message owner, and confirmation source', '2026-08-31-stakeholder-absence-plan.png'],
  ['recurring-request-cause-brief', 'Recurring request cause brief', 'client-request-routing', 'examine why the same client request returns without treating repetition alone as proof of a process failure', 'request pattern, distinct occurrences, client setting, prior response, competing explanation, process owner, and next experiment', '2026-08-31-client-silence-follow-up-rule.png'],
  ['overdue-commitment-recovery-plan', 'Overdue commitment recovery plan', 'contract-milestone-tracking', 'recover an overdue client commitment with an honest current state, authorized reset, and verifiable completion path', 'original commitment, missed date, current evidence, client effect, recovery owner, approved update, and completion test', '2026-08-31-client-commitment-sunset-review.png'],
  ['service-scope-ambiguity-register', 'Service scope ambiguity register', 'implementation-handoff-support', 'hold disputed service expectations for owner interpretation without allowing account support to invent contractual meaning', 'client wording, controlling document, operational question, conflicting interpretation, interim boundary, decision owner, and response date', '2026-08-31-service-credit-preparation-boundary.png'],
  ['client-channel-authority-map', 'Client channel authority map', 'client-onboarding-coordination', 'show which communication channels may carry notices, approvals, routine updates, and informal discussion for an account', 'channel, message class, authorized sender, required recipient, retention location, fallback route, and review trigger', '2026-08-31-escalation-audience-map.png'],
  ['portfolio-attention-transfer-note', 'Portfolio attention transfer note', 'account-health-monitoring', 'transfer temporary monitoring responsibility between account managers without losing the reason for heightened attention', 'account condition, evidence snapshot, observation window, temporary owner, decision limits, client message, and return condition', '2026-08-31-portfolio-exception-budget.png'],
  ['renewal-assumption-challenge-sheet', 'Renewal assumption challenge sheet', 'renewal-administration', 'test internal renewal beliefs against client-confirmed evidence before they enter a decision packet', 'assumption, origin, supporting record, contrary signal, client question, commercial owner, and evidence cutoff', '2026-08-31-renewal-evidence-freeze.png'],
  ['qbr-dissent-resolution-record', 'QBR dissent resolution record', 'customer-qbr-preparation', 'preserve material disagreement about a review claim until the evidence boundary and approved wording are resolved', 'disputed claim, reviewer positions, source definition, affected slide, resolution owner, approved wording, and retained limitation', '2026-08-31-qbr-question-backlog.png'],
];

const sources = [
  { name: 'NIST Cybersecurity Framework 2.0', date: 'February 26, 2024', url: 'https://www.nist.gov/publications/cybersecurity-framework-csf-20', note: 'Governance and control vocabulary; not an account-performance benchmark.' },
  { name: 'ISO quality management principles', date: 'accessed September 3, 2026', url: 'https://www.iso.org/quality-management/principles', note: 'Supports evidence-based decisions and improvement.' },
  { name: 'NIST accountability glossary', date: 'accessed September 3, 2026', url: 'https://csrc.nist.gov/glossary/term/accountability', note: 'Supports traceable actions and ownership.' },
];

function make([short, name, service, purpose, fields]: Topic): RichArticle {
  const subject = name.toLowerCase();
  return {
    title: `Philippines account management ${subject}`,
    description: `Published September 3, 2026: a practical routine to ${purpose}.`, published: '2026-09-03', updated: '2026-09-03', readMinutes: 12,
    intro: [`Published September 3, 2026. A ${subject} helps a Philippines-based account team ${purpose}.`, `The working record should contain ${fields}. The distinctive test for this routine is simple: can a new reviewer reproduce the next action without relying on private memory?`],
    takeaways: [`Record ${fields}.`, `Tie the ${subject} to one client consequence and one decision.`, 'Keep preparation, approval, communication, verification, and closure as separate states.', 'Route commercial, legal, security, privacy, access, and scope choices to authorized owners.'],
    sections: [
      { heading: `Define the job of the ${subject}`, paragraphs: [`Write the account, operating window, triggering event, client consequence, and decision this record supports. Its job is to ${purpose}. Anything unrelated belongs in a separate record with its own owner.`, `Capture ${fields}. Label missing evidence as unknown and assign the smallest source check that can resolve it. This prevents a plausible recollection from becoming an operational fact.`] },
      { heading: 'Bind each statement to evidence', paragraphs: [`Link the controlling CRM record, agreement, approved message, meeting decision, or delivery artifact beside the fact it supports. Preserve the source date and relevant limitation; a source may be authoritative for scope but unable to prove current delivery.`, `For this ${subject}, retain conflicting sources rather than silently selecting one. Name the reconciliation owner, affected action, and rule used to determine which source controls.`] },
      { heading: 'Use observable workflow states', paragraphs: [`Use states such as captured, checking evidence, ready for decision, approved to communicate, awaiting response, verifying, and closed. Define the evidence needed to enter and leave each state.`, `A draft is not an approval, a sent message is not acceptance, and a completed task is not proof of the intended client outcome. The ${subject} should keep those distinctions visible.`] },
      { heading: 'Separate work from decision authority', paragraphs: [`A Philippines-based specialist may gather approved facts, maintain this record, prepare neutral wording, and route an exception. That does not authorize changes to terms, money, legal positions, security controls, access, or service scope.`, `Name the work owner and decision owner separately. If authority is delegated, record the exact decision class, effective window, exclusions, and expiry trigger.`] },
      { heading: 'Prepare the next client update', paragraphs: [`When the final answer is pending, say what was received, what is confirmed, what remains open, who owns the decision, and when the next approved update will arrive. Avoid reassurance that outruns the evidence.`, `Before sending, compare the message with the current ${subject}. Save the approved version and any client correction so the record and conversation remain aligned.`] },
      { heading: 'Protect access and history', paragraphs: [`Use named accounts and task-matched permissions. Link controlled evidence instead of copying sensitive client data into a broad note.`, `Append material corrections with the editor, date, source, reviewer, and affected downstream work. Silent rewriting would erase why an earlier action appeared reasonable.`] },
      { heading: 'Review the control in practice', paragraphs: [`During the daily scan, inspect new triggers and missed checks. Weekly, sample one routine item, one consequential exception, and one closed item for source quality, authority, communication, and outcome proof.`, `Ask a teammate to reconstruct the current decision from the record. Any coaching they require identifies a field, definition, or source link that needs improvement.`] },
      { heading: 'Close and define reopening', paragraphs: [`Close only when the stated action happened, the authorized owner accepted the result, required communication was sent, and the evidence meets the rule written at intake.`, `Set a route-specific reopening trigger: changed evidence, client correction, expired approval, failed verification, or a new consequence. That makes this ${subject} a durable operating control.`] },
    ],
    banners: [{ label: 'Evidence', title: 'Preserve the source boundary', body: 'Facts need dated, reviewable support.', href: `/services/${service}`, link: 'See related support' }, { label: 'Authority', title: 'Route the decision', body: 'Preparation does not grant approval.', href: '/services/account-reporting', link: 'See reporting support' }, { label: 'Closure', title: 'Verify the intended result', body: 'Define proof before closing.', href: '/contact-us', link: 'Contact Us' }],
    table: { caption: `${name} minimum control record`, headers: ['Layer', 'Required entry', 'Reviewer question'], rows: [['Boundary', 'Account, event, consequence', 'What decision is supported?'], ['Evidence', 'Source, date, limitation', 'Can the fact be reproduced?'], ['Authority', 'Work and decision owners', 'Who may approve the next step?'], ['Outcome', 'Close proof and reopen trigger', 'What would change this status?']] },
    chart: [{ label: 'Evidence', value: 100, color: '#e8c98e' }, { label: 'Authority', value: 75, color: '#b9dfce' }, { label: 'Outcome', value: 50, color: '#ffd9ce' }], chartMeta: { title: `${name} control path`, desc: 'Evidence, authority, and outcome form the review path.', heading: 'Three review layers', method: 'Process illustration, not measured performance.' },
    quote: { text: 'Accountability allows actions to be traced to an entity.', source: 'NIST accountability glossary', url: 'https://csrc.nist.gov/glossary/term/accountability' },
    script: [`We reviewed ${subject} against [source] on [date]. The confirmed fact is [fact]; [owner] is deciding [open issue].`, 'The next approved update is due [date]. We will close only when [route-specific proof] is available.'],
    faqs: [{ q: `What belongs in a ${subject}?`, a: `At minimum: ${fields}, plus the client consequence and closure rule.` }, { q: 'Who approves consequential action?', a: 'The named authorized owner approves commercial, legal, security, access, privacy, and scope decisions.' }, { q: 'What makes closure credible?', a: 'Evidence that matches the intake rule, owner acceptance, required communication, and a defined reopening trigger.' }], sources,
  };
}

export const september3BlogPosts = topics.map(t => ({ slug: `philippines-account-management-${t[0]}`, title: `Philippines account management ${t[1].toLowerCase()}`, published: '2026-09-03' as const, excerpt: `A September 3, 2026 guide to ${t[3]}.`, minutes: 12 }));
export const september3RichArticles: Array<[string, RichArticle]> = topics.map(t => [`philippines-account-management-${t[0]}`, make(t)]);
